-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity layers_test_conv_layer_Pipeline_VITIS_LOOP_46_4_VITIS_LOOP_47_5_VITIS_LOOP_48_6_VITIS_LOOyd2 is 
    generic(
             DataWidth     : integer := 2; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of layers_test_conv_layer_Pipeline_VITIS_LOOP_46_4_VITIS_LOOP_47_5_VITIS_LOOP_48_6_VITIS_LOOyd2 is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10", 1 => "10", 2 => "10", 3 => "10", 
    4 => "10", 5 => "10", 6 => "10", 7 => "10", 
    8 => "10", 9 => "10", 10 => "10", 11 => "10", 
    12 => "10", 13 => "10", 14 => "10", 15 => "10", 
    16 => "10", 17 => "10", 18 => "10", 19 => "10", 
    20 => "10", 21 => "10", 22 => "10", 23 => "10", 
    24 => "10", 25 => "10", 26 => "10", 27 => "10", 
    28 => "10", 29 => "10", 30 => "10", 31 => "10");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

