-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layers_test_pool_layer_32_7_2_2_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool1_to_pool2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    pool1_to_pool2_empty_n : IN STD_LOGIC;
    pool1_to_pool2_read : OUT STD_LOGIC;
    pool1_to_pool2_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
    pool1_to_pool2_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
    IN_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    IN_1_ce1 : OUT STD_LOGIC;
    IN_1_we1 : OUT STD_LOGIC;
    IN_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of layers_test_pool_layer_32_7_2_2_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_620 : STD_LOGIC_VECTOR (10 downto 0) := "11000100000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal pool1_to_pool2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln24_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_376 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icol_mid2_fu_204_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal icol_mid2_reg_381 : STD_LOGIC_VECTOR (2 downto 0);
    signal icol_mid2_reg_381_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln24_fu_212_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln24_reg_386 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln27_fu_292_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln27_reg_391 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln27_fu_298_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_reg_396 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln27_12_fu_332_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icol_fu_62 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln25_fu_220_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal irow_fu_66 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln24_2_fu_232_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ich_fu_74 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln23_2_fu_264_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten12_fu_78 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln23_2_fu_140_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten12_load : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal IN_1_we1_local : STD_LOGIC;
    signal IN_1_ce1_local : STD_LOGIC;
    signal icmp_ln25_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln23_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_fu_166_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln23_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln24_fu_192_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln24_2_fu_226_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln23_fu_258_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl7_fu_275_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln27_fu_271_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln27_fu_283_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln27_9_fu_289_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_307_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln27_10_fu_314_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln25_fu_317_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln27_11_fu_323_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln27_2_fu_326_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component layers_test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component layers_test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ich_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    ich_fu_74 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    ich_fu_74 <= select_ln23_2_fu_264_p3;
                end if;
            end if; 
        end if;
    end process;

    icol_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    icol_fu_62 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    icol_fu_62 <= add_ln25_fu_220_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln23_fu_134_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten12_fu_78 <= add_ln23_2_fu_140_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten12_fu_78 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_70 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten_fu_70 <= select_ln24_2_fu_232_p3;
                end if;
            end if; 
        end if;
    end process;

    irow_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    irow_fu_66 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    irow_fu_66 <= select_ln24_fu_212_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln27_reg_391 <= add_ln27_fu_292_p2;
                icol_mid2_reg_381_pp0_iter2_reg <= icol_mid2_reg_381;
                trunc_ln27_reg_396 <= trunc_ln27_fu_298_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln24_reg_376 <= icmp_ln24_fu_160_p2;
                icol_mid2_reg_381 <= icol_mid2_fu_204_p3;
                select_ln24_reg_386 <= select_ln24_fu_212_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    IN_1_address1 <= zext_ln27_12_fu_332_p1(11 - 1 downto 0);
    IN_1_ce1 <= IN_1_ce1_local;

    IN_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            IN_1_ce1_local <= ap_const_logic_1;
        else 
            IN_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    IN_1_d1 <= pool1_to_pool2_dout;
    IN_1_we1 <= IN_1_we1_local;

    IN_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            IN_1_we1_local <= ap_const_logic_1;
        else 
            IN_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln23_2_fu_140_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten12_load) + unsigned(ap_const_lv11_1));
    add_ln23_fu_258_p2 <= std_logic_vector(unsigned(ich_fu_74) + unsigned(ap_const_lv6_1));
    add_ln24_2_fu_226_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_70) + unsigned(ap_const_lv6_1));
    add_ln24_fu_192_p2 <= std_logic_vector(unsigned(select_ln23_fu_166_p3) + unsigned(ap_const_lv3_1));
    add_ln25_fu_220_p2 <= std_logic_vector(unsigned(icol_mid2_fu_204_p3) + unsigned(ap_const_lv3_1));
    add_ln27_2_fu_326_p2 <= std_logic_vector(unsigned(sub_ln25_fu_317_p2) + unsigned(zext_ln27_11_fu_323_p1));
    add_ln27_fu_292_p2 <= std_logic_vector(unsigned(sub_ln27_fu_283_p2) + unsigned(zext_ln27_9_fu_289_p1));
    and_ln23_fu_186_p2 <= (xor_ln23_fu_174_p2 and icmp_ln25_fu_180_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, pool1_to_pool2_empty_n)
    begin
                ap_block_pp0_stage0_11001 <= ((pool1_to_pool2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter3, pool1_to_pool2_empty_n)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((pool1_to_pool2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, pool1_to_pool2_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((pool1_to_pool2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln23_fu_134_p2)
    begin
        if (((icmp_ln23_fu_134_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten12_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten12_fu_78, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten12_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten12_load <= indvar_flatten12_fu_78;
        end if; 
    end process;

    empty_fu_198_p2 <= (icmp_ln24_fu_160_p2 or and_ln23_fu_186_p2);
    icmp_ln23_fu_134_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten12_load = ap_const_lv11_620) else "0";
    icmp_ln24_fu_160_p2 <= "1" when (indvar_flatten_fu_70 = ap_const_lv6_31) else "0";
    icmp_ln25_fu_180_p2 <= "1" when (icol_fu_62 = ap_const_lv3_7) else "0";
    icol_mid2_fu_204_p3 <= 
        ap_const_lv3_0 when (empty_fu_198_p2(0) = '1') else 
        icol_fu_62;
    p_shl7_fu_275_p3 <= (select_ln23_2_fu_264_p3 & ap_const_lv3_0);

    pool1_to_pool2_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, pool1_to_pool2_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            pool1_to_pool2_blk_n <= pool1_to_pool2_empty_n;
        else 
            pool1_to_pool2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    pool1_to_pool2_read_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            pool1_to_pool2_read <= ap_const_logic_1;
        else 
            pool1_to_pool2_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln23_2_fu_264_p3 <= 
        add_ln23_fu_258_p2 when (icmp_ln24_reg_376(0) = '1') else 
        ich_fu_74;
    select_ln23_fu_166_p3 <= 
        ap_const_lv3_0 when (icmp_ln24_fu_160_p2(0) = '1') else 
        irow_fu_66;
    select_ln24_2_fu_232_p3 <= 
        ap_const_lv6_1 when (icmp_ln24_fu_160_p2(0) = '1') else 
        add_ln24_2_fu_226_p2;
    select_ln24_fu_212_p3 <= 
        add_ln24_fu_192_p2 when (and_ln23_fu_186_p2(0) = '1') else 
        select_ln23_fu_166_p3;
    sub_ln25_fu_317_p2 <= std_logic_vector(unsigned(tmp_fu_307_p3) - unsigned(zext_ln27_10_fu_314_p1));
    sub_ln27_fu_283_p2 <= std_logic_vector(unsigned(p_shl7_fu_275_p3) - unsigned(zext_ln27_fu_271_p1));
    tmp_fu_307_p3 <= (trunc_ln27_reg_396 & ap_const_lv3_0);
    trunc_ln27_fu_298_p1 <= add_ln27_fu_292_p2(8 - 1 downto 0);
    xor_ln23_fu_174_p2 <= (icmp_ln24_fu_160_p2 xor ap_const_lv1_1);
    zext_ln27_10_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln27_reg_391),11));
    zext_ln27_11_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icol_mid2_reg_381_pp0_iter2_reg),11));
    zext_ln27_12_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln27_2_fu_326_p2),64));
    zext_ln27_9_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_reg_386),9));
    zext_ln27_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_2_fu_264_p3),9));
end behav;
