-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layers_test_argmax_10_Pipeline_VITIS_LOOP_79_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    max : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
    void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
    max_idx_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_idx_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of layers_test_argmax_10_Pipeline_VITIS_LOOP_79_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln79_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_1_reg_345 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln82_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_reg_354 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_6_fu_210_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_6_reg_359 : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_2_fu_218_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_2_reg_365 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_idx_fu_70 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal max_idx_3_fu_295_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal max_04_fu_74 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal max_8_fu_303_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_max_04_load : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_78 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_2_fu_246_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal curr_fu_176_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_fu_176_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal curr_2_fu_218_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln83_fu_260_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_274_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal max_idx_2_fu_283_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln82_1_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln78_fu_291_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal max_idx_1_fu_263_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal curr_fu_176_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_fu_176_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_fu_176_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_fu_176_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_fu_176_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_2_fu_218_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_2_fu_218_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_2_fu_218_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_2_fu_218_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal curr_2_fu_218_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component layers_test_sparsemux_11_4_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component layers_test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_11_4_8_1_1_U3438 : component layers_test_sparsemux_11_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0010",
        din1_WIDTH => 8,
        CASE2 => "0100",
        din2_WIDTH => 8,
        CASE3 => "0110",
        din3_WIDTH => 8,
        CASE4 => "1000",
        din4_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => max,
        din1 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_load,
        din2 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_load,
        din3 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_load,
        din4 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_load,
        def => curr_fu_176_p11,
        sel => ap_sig_allocacmp_i_1,
        dout => curr_fu_176_p13);

    sparsemux_11_4_8_1_1_U3439 : component layers_test_sparsemux_11_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0010",
        din1_WIDTH => 8,
        CASE2 => "0100",
        din2_WIDTH => 8,
        CASE3 => "0110",
        din3_WIDTH => 8,
        CASE4 => "1000",
        din4_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_load,
        din1 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_load,
        din2 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_load,
        din3 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_load,
        din4 => void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_load,
        def => curr_2_fu_218_p11,
        sel => ap_sig_allocacmp_i_1,
        dout => curr_2_fu_218_p13);

    flow_control_loop_pipe_sequential_init_U : component layers_test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln79_fu_167_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_78 <= i_2_fu_246_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_78 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    max_04_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    max_04_fu_74 <= max;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    max_04_fu_74 <= max_8_fu_303_p3;
                end if;
            end if; 
        end if;
    end process;

    max_idx_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    max_idx_fu_70 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    max_idx_fu_70 <= max_idx_3_fu_295_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                curr_2_reg_365 <= curr_2_fu_218_p13;
                i_1_reg_345 <= ap_sig_allocacmp_i_1;
                icmp_ln82_reg_354 <= icmp_ln82_fu_204_p2;
                max_6_reg_359 <= max_6_fu_210_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln79_fu_167_p2)
    begin
        if (((icmp_ln79_fu_167_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_78)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_78;
        end if; 
    end process;


    ap_sig_allocacmp_max_04_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, max, ap_block_pp0_stage0, ap_loop_init, max_04_fu_74, max_8_fu_303_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_max_04_load <= max;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_max_04_load <= max_8_fu_303_p3;
            else 
                ap_sig_allocacmp_max_04_load <= max_04_fu_74;
            end if;
        else 
            ap_sig_allocacmp_max_04_load <= max_04_fu_74;
        end if; 
    end process;

    curr_2_fu_218_p11 <= "XXXXXXXX";
    curr_fu_176_p11 <= "XXXXXXXX";
    i_2_fu_246_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_2));
    icmp_ln79_fu_167_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(ap_const_lv4_A)) else "0";
    icmp_ln82_1_fu_270_p2 <= "1" when (signed(curr_2_reg_365) > signed(max_6_reg_359)) else "0";
    icmp_ln82_fu_204_p2 <= "1" when (signed(curr_fu_176_p13) > signed(ap_sig_allocacmp_max_04_load)) else "0";
    max_6_fu_210_p3 <= 
        curr_fu_176_p13 when (icmp_ln82_fu_204_p2(0) = '1') else 
        ap_sig_allocacmp_max_04_load;
    max_8_fu_303_p3 <= 
        curr_2_reg_365 when (icmp_ln82_1_fu_270_p2(0) = '1') else 
        max_6_reg_359;
    max_idx_1_fu_263_p3 <= 
        zext_ln83_fu_260_p1 when (icmp_ln82_reg_354(0) = '1') else 
        max_idx_fu_70;
    max_idx_2_fu_283_p3 <= (tmp_fu_274_p4 & ap_const_lv1_1);
    max_idx_3_fu_295_p3 <= 
        zext_ln78_fu_291_p1 when (icmp_ln82_1_fu_270_p2(0) = '1') else 
        max_idx_1_fu_263_p3;
    max_idx_out <= max_idx_fu_70;

    max_idx_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln79_fu_167_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln79_fu_167_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_idx_out_ap_vld <= ap_const_logic_1;
        else 
            max_idx_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_274_p4 <= i_1_reg_345(3 downto 1);
    zext_ln78_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(max_idx_2_fu_283_p3),8));
    zext_ln83_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_345),8));
end behav;
