-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool0_to_conv1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool0_to_conv1_full_n : IN STD_LOGIC;
    pool0_to_conv1_write : OUT STD_LOGIC;
    pool0_to_conv1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pool0_to_conv1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    IN_r_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    IN_r_ce0 : OUT STD_LOGIC;
    IN_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    IN_r_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    IN_r_ce1 : OUT STD_LOGIC;
    IN_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1880 : STD_LOGIC_VECTOR (12 downto 0) := "1100010000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv7_38 : STD_LOGIC_VECTOR (6 downto 0) := "0111000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln41_2_reg_933 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_2_reg_933_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_reg_937 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_reg_937_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op149_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln35_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal pool0_to_conv1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal icmp_ln35_reg_839 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln35_reg_839_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_reg_843 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln36_reg_843_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_reg_852 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_reg_852_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_858 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_2_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_2_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_2_reg_863_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_48_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_48_reg_870 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_48_reg_870_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten38_mid295_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten38_mid295_reg_876 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten23_mid260_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten23_mid260_reg_881 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln36_fu_341_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln36_reg_889 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_50_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_50_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln38_fu_565_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_reg_899 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln38_fu_571_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln38_reg_904 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_575_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_reg_909 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln41_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln41_reg_914 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln41_reg_914_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln46_fu_609_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln46_reg_918 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln46_fu_615_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_reg_923 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln44_fu_623_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln44_reg_928 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln41_2_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_2_reg_933_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_reg_937_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal IN_load_reg_951 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln38_8_fu_700_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_6_fu_738_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_col_fu_84 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln41_fu_629_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_row_fu_88 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln40_fu_520_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten21_fu_92 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln40_2_fu_364_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ocol_fu_96 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln37_fu_475_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten36_fu_100 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln37_1_fu_263_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal orow_fu_104 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten61_fu_108 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln36_1_fu_277_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal och_fu_112 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln35_2_fu_417_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten96_fu_116 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln35_1_fu_210_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten96_load : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal max_2_fu_120 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal max_5_fu_756_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal IN_r_ce1_local : STD_LOGIC;
    signal IN_r_ce0_local : STD_LOGIC;
    signal add_ln37_1_fu_257_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln36_1_fu_271_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln35_fu_301_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten38_not_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_1_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln36_fu_314_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_49_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_1_fu_358_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal first_iter_3138_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln35_fu_394_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln35_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ocol_mid243_fu_424_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal first_iter_3_mid254_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_mid256_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten23_mid260_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln37_fu_441_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_row_mid228_fu_447_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_51_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_mid235_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_52_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_fu_482_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal first_iter_3_mid1_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_mid233_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_536_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_528_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln38_fu_544_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_554_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln38_fu_548_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln38_5_fu_561_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal k_col_mid2_fu_498_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal first_iter_3_mid2_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_1_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln40_fu_595_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_fu_599_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln46_fu_605_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln41_fu_619_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_9_fu_667_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_674_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_6_fu_681_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln38_2_fu_685_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln38_7_fu_691_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln38_1_fu_694_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_11_fu_705_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_fu_712_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_4_fu_719_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln41_fu_723_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_5_fu_729_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln46_1_fu_732_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln46_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component layers_test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component layers_test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten21_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    indvar_flatten21_fu_92 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln35_reg_839_pp0_iter1_reg = ap_const_lv1_0))) then 
                    indvar_flatten21_fu_92 <= select_ln40_2_fu_364_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten36_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten36_fu_100 <= ap_const_lv7_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_reg_839 = ap_const_lv1_0))) then 
                    indvar_flatten36_fu_100 <= select_ln37_1_fu_263_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten61_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten61_fu_108 <= ap_const_lv10_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_reg_839 = ap_const_lv1_0))) then 
                    indvar_flatten61_fu_108 <= select_ln36_1_fu_277_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten96_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln35_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten96_fu_116 <= add_ln35_1_fu_210_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten96_fu_116 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    k_col_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    k_col_fu_84 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    k_col_fu_84 <= add_ln41_fu_629_p2;
                end if;
            end if; 
        end if;
    end process;

    k_row_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    k_row_fu_88 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    k_row_fu_88 <= select_ln40_fu_520_p3;
                end if;
            end if; 
        end if;
    end process;

    max_2_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_const_lv1_1 = and_ln41_reg_914_pp0_iter4_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
                    max_2_fu_120 <= IN_r_q1;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    max_2_fu_120 <= max_5_fu_756_p3;
                end if;
            end if; 
        end if;
    end process;

    och_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    och_fu_112 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    och_fu_112 <= select_ln35_2_fu_417_p3;
                end if;
            end if; 
        end if;
    end process;

    ocol_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ocol_fu_96 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    ocol_fu_96 <= select_ln37_fu_475_p3;
                end if;
            end if; 
        end if;
    end process;

    orow_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    orow_fu_104 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln35_reg_839_pp0_iter1_reg = ap_const_lv1_0))) then 
                    orow_fu_104 <= select_ln36_fu_341_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                IN_load_reg_951 <= IN_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                    add_ln38_reg_899(8 downto 1) <= add_ln38_fu_565_p2(8 downto 1);
                add_ln44_reg_928 <= add_ln44_fu_623_p2;
                add_ln46_reg_918 <= add_ln46_fu_609_p2;
                and_ln35_2_reg_863_pp0_iter2_reg <= and_ln35_2_reg_863;
                and_ln41_reg_914 <= and_ln41_fu_589_p2;
                and_ln41_reg_914_pp0_iter4_reg <= and_ln41_reg_914;
                empty_48_reg_870_pp0_iter2_reg <= empty_48_reg_870;
                empty_50_reg_894 <= empty_50_fu_353_p2;
                exitcond_flatten23_mid260_reg_881 <= exitcond_flatten23_mid260_fu_335_p2;
                icmp_ln36_reg_843_pp0_iter2_reg <= icmp_ln36_reg_843;
                icmp_ln40_1_reg_937 <= icmp_ln40_1_fu_641_p2;
                icmp_ln40_1_reg_937_pp0_iter4_reg <= icmp_ln40_1_reg_937;
                icmp_ln40_1_reg_937_pp0_iter5_reg <= icmp_ln40_1_reg_937_pp0_iter4_reg;
                icmp_ln41_2_reg_933 <= icmp_ln41_2_fu_635_p2;
                icmp_ln41_2_reg_933_pp0_iter4_reg <= icmp_ln41_2_reg_933;
                icmp_ln41_2_reg_933_pp0_iter5_reg <= icmp_ln41_2_reg_933_pp0_iter4_reg;
                not_exitcond_flatten38_mid295_reg_876 <= not_exitcond_flatten38_mid295_fu_325_p2;
                select_ln36_reg_889 <= select_ln36_fu_341_p3;
                    shl_ln_reg_909(4 downto 1) <= shl_ln_fu_575_p3(4 downto 1);
                    trunc_ln38_reg_904(7 downto 1) <= trunc_ln38_fu_571_p1(7 downto 1);
                trunc_ln46_reg_923 <= trunc_ln46_fu_615_p1;
                xor_ln35_reg_852_pp0_iter2_reg <= xor_ln35_reg_852;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln35_2_reg_863 <= and_ln35_2_fu_245_p2;
                empty_48_reg_870 <= empty_48_fu_251_p2;
                icmp_ln36_reg_843 <= icmp_ln36_fu_227_p2;
                icmp_ln37_reg_858 <= icmp_ln37_fu_239_p2;
                xor_ln35_reg_852 <= xor_ln35_fu_233_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln35_reg_839 <= icmp_ln35_fu_204_p2;
                icmp_ln35_reg_839_pp0_iter1_reg <= icmp_ln35_reg_839;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if;
        end if;
    end process;
    add_ln38_reg_899(0) <= '0';
    trunc_ln38_reg_904(0) <= '0';
    shl_ln_reg_909(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    IN_r_address0 <= zext_ln46_6_fu_738_p1(13 - 1 downto 0);
    IN_r_address1 <= zext_ln38_8_fu_700_p1(13 - 1 downto 0);
    IN_r_ce0 <= IN_r_ce0_local;

    IN_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            IN_r_ce0_local <= ap_const_logic_1;
        else 
            IN_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    IN_r_ce1 <= IN_r_ce1_local;

    IN_r_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            IN_r_ce1_local <= ap_const_logic_1;
        else 
            IN_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln35_1_fu_210_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten96_load) + unsigned(ap_const_lv13_1));
    add_ln35_fu_394_p2 <= std_logic_vector(unsigned(och_fu_112) + unsigned(ap_const_lv4_1));
    add_ln36_1_fu_271_p2 <= std_logic_vector(unsigned(indvar_flatten61_fu_108) + unsigned(ap_const_lv10_1));
    add_ln36_fu_314_p2 <= std_logic_vector(unsigned(select_ln35_fu_301_p3) + unsigned(ap_const_lv4_1));
    add_ln37_1_fu_257_p2 <= std_logic_vector(unsigned(indvar_flatten36_fu_100) + unsigned(ap_const_lv7_1));
    add_ln37_fu_441_p2 <= std_logic_vector(unsigned(ocol_mid243_fu_424_p3) + unsigned(ap_const_lv4_1));
    add_ln38_1_fu_694_p2 <= std_logic_vector(unsigned(sub_ln38_2_fu_685_p2) + unsigned(zext_ln38_7_fu_691_p1));
    add_ln38_fu_565_p2 <= std_logic_vector(unsigned(sub_ln38_fu_548_p2) + unsigned(zext_ln38_5_fu_561_p1));
    add_ln40_1_fu_358_p2 <= std_logic_vector(unsigned(indvar_flatten21_fu_92) + unsigned(ap_const_lv4_1));
    add_ln40_fu_482_p2 <= std_logic_vector(unsigned(k_row_mid228_fu_447_p3) + unsigned(ap_const_lv2_1));
    add_ln41_fu_629_p2 <= std_logic_vector(unsigned(k_col_mid2_fu_498_p3) + unsigned(ap_const_lv2_1));
    add_ln44_fu_623_p2 <= std_logic_vector(unsigned(shl_ln_fu_575_p3) + unsigned(zext_ln41_fu_619_p1));
    add_ln46_1_fu_732_p2 <= std_logic_vector(unsigned(sub_ln41_fu_723_p2) + unsigned(zext_ln46_5_fu_729_p1));
    add_ln46_fu_609_p2 <= std_logic_vector(unsigned(sub_ln38_fu_548_p2) + unsigned(zext_ln46_fu_605_p1));
    and_ln35_1_fu_330_p2 <= (xor_ln35_reg_852 and icmp_ln40_fu_308_p2);
    and_ln35_2_fu_245_p2 <= (xor_ln35_fu_233_p2 and icmp_ln37_fu_239_p2);
    and_ln35_fu_436_p2 <= (xor_ln35_reg_852_pp0_iter2_reg and icmp_ln41_fu_411_p2);
    and_ln41_fu_589_p2 <= (icmp_ln41_1_fu_583_p2 and first_iter_3_mid2_fu_512_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter6_grp1_assign_proc : process(pool0_to_conv1_full_n, ap_predicate_op149_write_state7)
    begin
                ap_block_state7_pp0_stage0_iter6_grp1 <= ((ap_predicate_op149_write_state7 = ap_const_boolean_1) and (pool0_to_conv1_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln35_fu_204_p2)
    begin
        if (((icmp_ln35_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln35_reg_839_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln35_reg_839_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op149_write_state7_assign_proc : process(icmp_ln41_2_reg_933_pp0_iter5_reg, icmp_ln40_1_reg_937_pp0_iter5_reg)
    begin
                ap_predicate_op149_write_state7 <= ((icmp_ln40_1_reg_937_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln41_2_reg_933_pp0_iter5_reg = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten96_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten96_fu_116, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten96_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten96_load <= indvar_flatten96_fu_116;
        end if; 
    end process;

    empty_48_fu_251_p2 <= (icmp_ln36_fu_227_p2 or and_ln35_2_fu_245_p2);
    empty_49_fu_348_p2 <= (exitcond_flatten23_mid260_fu_335_p2 or and_ln35_2_reg_863);
    empty_50_fu_353_p2 <= (icmp_ln36_reg_843 or empty_49_fu_348_p2);
    empty_51_fu_488_p2 <= (exitcond_flatten23_mid260_reg_881 or empty_48_reg_870_pp0_iter2_reg);
    empty_52_fu_492_p2 <= (icmp_ln41_mid235_fu_469_p2 or empty_51_fu_488_p2);
    empty_fu_599_p2 <= std_logic_vector(unsigned(tmp_fu_554_p3) + unsigned(zext_ln40_fu_595_p1));
    exitcond_flatten23_mid260_fu_335_p2 <= (not_exitcond_flatten38_mid295_fu_325_p2 and and_ln35_1_fu_330_p2);
    exitcond_flatten38_not_fu_320_p2 <= (icmp_ln37_reg_858 xor ap_const_lv1_1);
    first_iter_3138_fu_400_p2 <= "1" when (k_row_fu_88 = ap_const_lv2_0) else "0";
    first_iter_3_mid1_fu_506_p2 <= "1" when (add_ln40_fu_482_p2 = ap_const_lv2_0) else "0";
    first_iter_3_mid233_fu_454_p2 <= (first_iter_3_mid254_fu_431_p2 or exitcond_flatten23_mid260_reg_881);
    first_iter_3_mid254_fu_431_p2 <= (or_ln35_fu_406_p2 or and_ln35_2_reg_863_pp0_iter2_reg);
    first_iter_3_mid2_fu_512_p3 <= 
        first_iter_3_mid1_fu_506_p2 when (icmp_ln41_mid235_fu_469_p2(0) = '1') else 
        first_iter_3_mid233_fu_454_p2;
    icmp_ln35_fu_204_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten96_load = ap_const_lv13_1880) else "0";
    icmp_ln36_fu_227_p2 <= "1" when (indvar_flatten61_fu_108 = ap_const_lv10_310) else "0";
    icmp_ln37_fu_239_p2 <= "1" when (indvar_flatten36_fu_100 = ap_const_lv7_38) else "0";
    icmp_ln40_1_fu_641_p2 <= "1" when (select_ln40_fu_520_p3 = ap_const_lv2_1) else "0";
    icmp_ln40_fu_308_p2 <= "1" when (indvar_flatten21_fu_92 = ap_const_lv4_4) else "0";
    icmp_ln41_1_fu_583_p2 <= "1" when (k_col_mid2_fu_498_p3 = ap_const_lv2_0) else "0";
    icmp_ln41_2_fu_635_p2 <= "1" when (add_ln41_fu_629_p2 = ap_const_lv2_2) else "0";
    icmp_ln41_fu_411_p2 <= "1" when (k_col_fu_84 = ap_const_lv2_2) else "0";
    icmp_ln41_mid235_fu_469_p2 <= (not_exitcond_flatten23_mid260_fu_459_p2 and icmp_ln41_mid256_fu_464_p2);
    icmp_ln41_mid256_fu_464_p2 <= (not_exitcond_flatten38_mid295_reg_876 and and_ln35_fu_436_p2);
    icmp_ln46_fu_751_p2 <= "1" when (signed(max_2_fu_120) < signed(IN_load_reg_951)) else "0";
    k_col_mid2_fu_498_p3 <= 
        ap_const_lv2_0 when (empty_52_fu_492_p2(0) = '1') else 
        k_col_fu_84;
    k_row_mid228_fu_447_p3 <= 
        ap_const_lv2_0 when (empty_50_reg_894(0) = '1') else 
        k_row_fu_88;
    max_5_fu_756_p3 <= 
        IN_load_reg_951 when (icmp_ln46_fu_751_p2(0) = '1') else 
        max_2_fu_120;
    not_exitcond_flatten23_mid260_fu_459_p2 <= (exitcond_flatten23_mid260_reg_881 xor ap_const_lv1_1);
    not_exitcond_flatten38_mid295_fu_325_p2 <= (icmp_ln36_reg_843 or exitcond_flatten38_not_fu_320_p2);
    ocol_mid243_fu_424_p3 <= 
        ap_const_lv4_0 when (empty_48_reg_870_pp0_iter2_reg(0) = '1') else 
        ocol_fu_96;
    or_ln35_fu_406_p2 <= (icmp_ln36_reg_843_pp0_iter2_reg or first_iter_3138_fu_400_p2);
    p_shl_fu_528_p3 <= (select_ln35_2_fu_417_p3 & ap_const_lv5_0);

    pool0_to_conv1_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, pool0_to_conv1_full_n, ap_predicate_op149_write_state7, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op149_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            pool0_to_conv1_blk_n <= pool0_to_conv1_full_n;
        else 
            pool0_to_conv1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pool0_to_conv1_din <= 
        IN_load_reg_951 when (icmp_ln46_fu_751_p2(0) = '1') else 
        max_2_fu_120;

    pool0_to_conv1_write_assign_proc : process(ap_enable_reg_pp0_iter6, ap_predicate_op149_write_state7, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op149_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            pool0_to_conv1_write <= ap_const_logic_1;
        else 
            pool0_to_conv1_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln35_2_fu_417_p3 <= 
        add_ln35_fu_394_p2 when (icmp_ln36_reg_843_pp0_iter2_reg(0) = '1') else 
        och_fu_112;
    select_ln35_fu_301_p3 <= 
        ap_const_lv4_0 when (icmp_ln36_reg_843(0) = '1') else 
        orow_fu_104;
    select_ln36_1_fu_277_p3 <= 
        ap_const_lv10_1 when (icmp_ln36_fu_227_p2(0) = '1') else 
        add_ln36_1_fu_271_p2;
    select_ln36_fu_341_p3 <= 
        add_ln36_fu_314_p2 when (and_ln35_2_reg_863(0) = '1') else 
        select_ln35_fu_301_p3;
    select_ln37_1_fu_263_p3 <= 
        ap_const_lv7_1 when (empty_48_fu_251_p2(0) = '1') else 
        add_ln37_1_fu_257_p2;
    select_ln37_fu_475_p3 <= 
        add_ln37_fu_441_p2 when (exitcond_flatten23_mid260_reg_881(0) = '1') else 
        ocol_mid243_fu_424_p3;
    select_ln40_2_fu_364_p3 <= 
        ap_const_lv4_1 when (empty_50_fu_353_p2(0) = '1') else 
        add_ln40_1_fu_358_p2;
    select_ln40_fu_520_p3 <= 
        add_ln40_fu_482_p2 when (icmp_ln41_mid235_fu_469_p2(0) = '1') else 
        k_row_mid228_fu_447_p3;
    shl_ln_fu_575_p3 <= (select_ln37_fu_475_p3 & ap_const_lv1_0);
    sub_ln38_2_fu_685_p2 <= std_logic_vector(unsigned(tmp_10_fu_674_p3) - unsigned(zext_ln38_6_fu_681_p1));
    sub_ln38_fu_548_p2 <= std_logic_vector(unsigned(p_shl_fu_528_p3) - unsigned(zext_ln38_fu_544_p1));
    sub_ln41_fu_723_p2 <= std_logic_vector(unsigned(tmp_12_fu_712_p3) - unsigned(zext_ln46_4_fu_719_p1));
    tmp_10_fu_674_p3 <= (trunc_ln38_reg_904 & ap_const_lv5_0);
    tmp_11_fu_705_p3 <= (add_ln46_reg_918 & ap_const_lv2_0);
    tmp_12_fu_712_p3 <= (trunc_ln46_reg_923 & ap_const_lv5_0);
    tmp_8_fu_536_p3 <= (select_ln35_2_fu_417_p3 & ap_const_lv2_0);
    tmp_9_fu_667_p3 <= (add_ln38_reg_899 & ap_const_lv2_0);
    tmp_fu_554_p3 <= (select_ln36_reg_889 & ap_const_lv1_0);
    trunc_ln38_fu_571_p1 <= add_ln38_fu_565_p2(8 - 1 downto 0);
    trunc_ln46_fu_615_p1 <= add_ln46_fu_609_p2(8 - 1 downto 0);
    xor_ln35_fu_233_p2 <= (icmp_ln36_fu_227_p2 xor ap_const_lv1_1);
    zext_ln38_5_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_554_p3),9));
    zext_ln38_6_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_667_p3),13));
    zext_ln38_7_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_reg_909),13));
    zext_ln38_8_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln38_1_fu_694_p2),64));
    zext_ln38_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_536_p3),9));
    zext_ln40_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln40_fu_520_p3),5));
    zext_ln41_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_col_mid2_fu_498_p3),5));
    zext_ln46_4_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_705_p3),13));
    zext_ln46_5_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln44_reg_928),13));
    zext_ln46_6_fu_738_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_1_fu_732_p2),64));
    zext_ln46_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_599_p2),9));
end behav;
