-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layers_test is
port (
    stream_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC );
end;


architecture behav of layers_test is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "layers_test_layers_test,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.038000,HLS_SYN_LAT=51800,HLS_SYN_TPT=51777,HLS_SYN_MEM=41,HLS_SYN_DSP=0,HLS_SYN_FF=13125,HLS_SYN_LUT=33433,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal axis_to_nn_784_U0_ap_start : STD_LOGIC;
    signal axis_to_nn_784_U0_ap_done : STD_LOGIC;
    signal axis_to_nn_784_U0_ap_continue : STD_LOGIC;
    signal axis_to_nn_784_U0_ap_idle : STD_LOGIC;
    signal axis_to_nn_784_U0_ap_ready : STD_LOGIC;
    signal axis_to_nn_784_U0_input_to_conv0_din : STD_LOGIC_VECTOR (7 downto 0);
    signal axis_to_nn_784_U0_input_to_conv0_write : STD_LOGIC;
    signal axis_to_nn_784_U0_start_out : STD_LOGIC;
    signal axis_to_nn_784_U0_start_write : STD_LOGIC;
    signal axis_to_nn_784_U0_stream_in_TREADY : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_ap_start : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_ap_done : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_ap_continue : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_ap_idle : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_ap_ready : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_start_out : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_start_write : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_input_to_conv0_read : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din : STD_LOGIC_VECTOR (7 downto 0);
    signal conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write : STD_LOGIC;
    signal conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_8_28_2_2_U0_ap_start : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_ap_done : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_ap_continue : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_ap_idle : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_ap_ready : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_start_out : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_start_write : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_conv0_to_pool0_read : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_pool0_to_conv1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal pool_layer_8_28_2_2_U0_pool0_to_conv1_write : STD_LOGIC;
    signal pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_layer_8_14_3_1_32_U0_ap_start : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_ap_done : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_ap_continue : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_ap_idle : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_ap_ready : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_start_out : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_start_write : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write : STD_LOGIC;
    signal conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_32_14_2_2_U0_ap_start : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_ap_done : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_ap_continue : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_ap_idle : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_ap_ready : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_start_out : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_start_write : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_conv1_to_pool1_read : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_pool1_to_pool2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal pool_layer_32_14_2_2_U0_pool1_to_pool2_write : STD_LOGIC;
    signal pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_32_7_2_2_U0_ap_start : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_ap_done : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_ap_continue : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_ap_idle : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_ap_ready : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_start_out : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_start_write : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_pool1_to_pool2_read : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_pool2_to_fc0_din : STD_LOGIC_VECTOR (7 downto 0);
    signal pool_layer_32_7_2_2_U0_pool2_to_fc0_write : STD_LOGIC;
    signal pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal fc_layer_288_10_U0_ap_start : STD_LOGIC;
    signal fc_layer_288_10_U0_ap_done : STD_LOGIC;
    signal fc_layer_288_10_U0_ap_continue : STD_LOGIC;
    signal fc_layer_288_10_U0_ap_idle : STD_LOGIC;
    signal fc_layer_288_10_U0_ap_ready : STD_LOGIC;
    signal fc_layer_288_10_U0_start_out : STD_LOGIC;
    signal fc_layer_288_10_U0_start_write : STD_LOGIC;
    signal fc_layer_288_10_U0_pool2_to_fc0_read : STD_LOGIC;
    signal fc_layer_288_10_U0_fc0_to_argmax0_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fc_layer_288_10_U0_fc0_to_argmax0_write : STD_LOGIC;
    signal argmax_10_U0_ap_start : STD_LOGIC;
    signal argmax_10_U0_ap_done : STD_LOGIC;
    signal argmax_10_U0_ap_continue : STD_LOGIC;
    signal argmax_10_U0_ap_idle : STD_LOGIC;
    signal argmax_10_U0_ap_ready : STD_LOGIC;
    signal argmax_10_U0_start_out : STD_LOGIC;
    signal argmax_10_U0_start_write : STD_LOGIC;
    signal argmax_10_U0_fc0_to_argmax0_read : STD_LOGIC;
    signal argmax_10_U0_argmax0_to_output_din : STD_LOGIC_VECTOR (7 downto 0);
    signal argmax_10_U0_argmax0_to_output_write : STD_LOGIC;
    signal nn_to_axis_1_U0_ap_start : STD_LOGIC;
    signal nn_to_axis_1_U0_ap_done : STD_LOGIC;
    signal nn_to_axis_1_U0_ap_continue : STD_LOGIC;
    signal nn_to_axis_1_U0_ap_idle : STD_LOGIC;
    signal nn_to_axis_1_U0_ap_ready : STD_LOGIC;
    signal nn_to_axis_1_U0_argmax0_to_output_read : STD_LOGIC;
    signal nn_to_axis_1_U0_stream_out_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal nn_to_axis_1_U0_stream_out_TVALID : STD_LOGIC;
    signal nn_to_axis_1_U0_stream_out_TKEEP : STD_LOGIC_VECTOR (0 downto 0);
    signal nn_to_axis_1_U0_stream_out_TSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal nn_to_axis_1_U0_stream_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal input_to_conv0_full_n : STD_LOGIC;
    signal input_to_conv0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal input_to_conv0_empty_n : STD_LOGIC;
    signal input_to_conv0_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal input_to_conv0_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal conv0_to_pool0_full_n : STD_LOGIC;
    signal conv0_to_pool0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal conv0_to_pool0_empty_n : STD_LOGIC;
    signal conv0_to_pool0_num_data_valid : STD_LOGIC_VECTOR (14 downto 0);
    signal conv0_to_pool0_fifo_cap : STD_LOGIC_VECTOR (14 downto 0);
    signal pool0_to_conv1_full_n : STD_LOGIC;
    signal pool0_to_conv1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal pool0_to_conv1_empty_n : STD_LOGIC;
    signal pool0_to_conv1_num_data_valid : STD_LOGIC_VECTOR (11 downto 0);
    signal pool0_to_conv1_fifo_cap : STD_LOGIC_VECTOR (11 downto 0);
    signal conv1_to_pool1_full_n : STD_LOGIC;
    signal conv1_to_pool1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal conv1_to_pool1_empty_n : STD_LOGIC;
    signal conv1_to_pool1_num_data_valid : STD_LOGIC_VECTOR (14 downto 0);
    signal conv1_to_pool1_fifo_cap : STD_LOGIC_VECTOR (14 downto 0);
    signal pool1_to_pool2_full_n : STD_LOGIC;
    signal pool1_to_pool2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal pool1_to_pool2_empty_n : STD_LOGIC;
    signal pool1_to_pool2_num_data_valid : STD_LOGIC_VECTOR (11 downto 0);
    signal pool1_to_pool2_fifo_cap : STD_LOGIC_VECTOR (11 downto 0);
    signal pool2_to_fc0_full_n : STD_LOGIC;
    signal pool2_to_fc0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal pool2_to_fc0_empty_n : STD_LOGIC;
    signal pool2_to_fc0_num_data_valid : STD_LOGIC_VECTOR (12 downto 0);
    signal pool2_to_fc0_fifo_cap : STD_LOGIC_VECTOR (12 downto 0);
    signal fc0_to_argmax0_full_n : STD_LOGIC;
    signal fc0_to_argmax0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal fc0_to_argmax0_empty_n : STD_LOGIC;
    signal fc0_to_argmax0_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal fc0_to_argmax0_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal argmax0_to_output_full_n : STD_LOGIC;
    signal argmax0_to_output_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal argmax0_to_output_empty_n : STD_LOGIC;
    signal argmax0_to_output_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal argmax0_to_output_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal start_for_conv_layer_1_28_3_1_8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_layer_1_28_3_1_8_U0_full_n : STD_LOGIC;
    signal start_for_conv_layer_1_28_3_1_8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_layer_1_28_3_1_8_U0_empty_n : STD_LOGIC;
    signal start_for_pool_layer_8_28_2_2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_8_28_2_2_U0_full_n : STD_LOGIC;
    signal start_for_pool_layer_8_28_2_2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_8_28_2_2_U0_empty_n : STD_LOGIC;
    signal start_for_conv_layer_8_14_3_1_32_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_layer_8_14_3_1_32_U0_full_n : STD_LOGIC;
    signal start_for_conv_layer_8_14_3_1_32_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_layer_8_14_3_1_32_U0_empty_n : STD_LOGIC;
    signal start_for_pool_layer_32_14_2_2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_32_14_2_2_U0_full_n : STD_LOGIC;
    signal start_for_pool_layer_32_14_2_2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_32_14_2_2_U0_empty_n : STD_LOGIC;
    signal start_for_pool_layer_32_7_2_2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_32_7_2_2_U0_full_n : STD_LOGIC;
    signal start_for_pool_layer_32_7_2_2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pool_layer_32_7_2_2_U0_empty_n : STD_LOGIC;
    signal start_for_fc_layer_288_10_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fc_layer_288_10_U0_full_n : STD_LOGIC;
    signal start_for_fc_layer_288_10_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fc_layer_288_10_U0_empty_n : STD_LOGIC;
    signal start_for_argmax_10_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_argmax_10_U0_full_n : STD_LOGIC;
    signal start_for_argmax_10_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_argmax_10_U0_empty_n : STD_LOGIC;
    signal start_for_nn_to_axis_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_nn_to_axis_1_U0_full_n : STD_LOGIC;
    signal start_for_nn_to_axis_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_nn_to_axis_1_U0_empty_n : STD_LOGIC;

    component layers_test_axis_to_nn_784_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_TVALID : IN STD_LOGIC;
        input_to_conv0_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_to_conv0_full_n : IN STD_LOGIC;
        input_to_conv0_write : OUT STD_LOGIC;
        input_to_conv0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        input_to_conv0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        stream_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_in_TREADY : OUT STD_LOGIC;
        stream_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component layers_test_conv_layer_1_28_3_1_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_to_conv0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        input_to_conv0_empty_n : IN STD_LOGIC;
        input_to_conv0_read : OUT STD_LOGIC;
        input_to_conv0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        input_to_conv0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        conv0_to_pool0_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        conv0_to_pool0_full_n : IN STD_LOGIC;
        conv0_to_pool0_write : OUT STD_LOGIC;
        conv0_to_pool0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        conv0_to_pool0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component layers_test_pool_layer_8_28_2_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        conv0_to_pool0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        conv0_to_pool0_empty_n : IN STD_LOGIC;
        conv0_to_pool0_read : OUT STD_LOGIC;
        conv0_to_pool0_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        conv0_to_pool0_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        pool0_to_conv1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        pool0_to_conv1_full_n : IN STD_LOGIC;
        pool0_to_conv1_write : OUT STD_LOGIC;
        pool0_to_conv1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        pool0_to_conv1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component layers_test_conv_layer_8_14_3_1_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        pool0_to_conv1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        pool0_to_conv1_empty_n : IN STD_LOGIC;
        pool0_to_conv1_read : OUT STD_LOGIC;
        pool0_to_conv1_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
        pool0_to_conv1_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
        conv1_to_pool1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        conv1_to_pool1_full_n : IN STD_LOGIC;
        conv1_to_pool1_write : OUT STD_LOGIC;
        conv1_to_pool1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        conv1_to_pool1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component layers_test_pool_layer_32_14_2_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        conv1_to_pool1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        conv1_to_pool1_empty_n : IN STD_LOGIC;
        conv1_to_pool1_read : OUT STD_LOGIC;
        conv1_to_pool1_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
        conv1_to_pool1_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
        pool1_to_pool2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        pool1_to_pool2_full_n : IN STD_LOGIC;
        pool1_to_pool2_write : OUT STD_LOGIC;
        pool1_to_pool2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        pool1_to_pool2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component layers_test_pool_layer_32_7_2_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        pool1_to_pool2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        pool1_to_pool2_empty_n : IN STD_LOGIC;
        pool1_to_pool2_read : OUT STD_LOGIC;
        pool1_to_pool2_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
        pool1_to_pool2_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
        pool2_to_fc0_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        pool2_to_fc0_full_n : IN STD_LOGIC;
        pool2_to_fc0_write : OUT STD_LOGIC;
        pool2_to_fc0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        pool2_to_fc0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component layers_test_fc_layer_288_10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        pool2_to_fc0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        pool2_to_fc0_empty_n : IN STD_LOGIC;
        pool2_to_fc0_read : OUT STD_LOGIC;
        pool2_to_fc0_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        pool2_to_fc0_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        fc0_to_argmax0_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        fc0_to_argmax0_full_n : IN STD_LOGIC;
        fc0_to_argmax0_write : OUT STD_LOGIC;
        fc0_to_argmax0_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        fc0_to_argmax0_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component layers_test_argmax_10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        fc0_to_argmax0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        fc0_to_argmax0_empty_n : IN STD_LOGIC;
        fc0_to_argmax0_read : OUT STD_LOGIC;
        fc0_to_argmax0_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        fc0_to_argmax0_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        argmax0_to_output_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        argmax0_to_output_full_n : IN STD_LOGIC;
        argmax0_to_output_write : OUT STD_LOGIC;
        argmax0_to_output_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        argmax0_to_output_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component layers_test_nn_to_axis_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        argmax0_to_output_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        argmax0_to_output_empty_n : IN STD_LOGIC;
        argmax0_to_output_read : OUT STD_LOGIC;
        argmax0_to_output_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        argmax0_to_output_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_out_TVALID : OUT STD_LOGIC;
        stream_out_TREADY : IN STD_LOGIC;
        stream_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component layers_test_fifo_w8_d1000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component layers_test_fifo_w8_d10000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (14 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component layers_test_fifo_w8_d2000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component layers_test_fifo_w8_d3000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component layers_test_fifo_w8_d100_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component layers_test_fifo_w8_d10_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component layers_test_start_for_conv_layer_1_28_3_1_8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_pool_layer_8_28_2_2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_conv_layer_8_14_3_1_32_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_pool_layer_32_14_2_2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_pool_layer_32_7_2_2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_fc_layer_288_10_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_argmax_10_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component layers_test_start_for_nn_to_axis_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    axis_to_nn_784_U0 : component layers_test_axis_to_nn_784_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => axis_to_nn_784_U0_ap_start,
        start_full_n => start_for_conv_layer_1_28_3_1_8_U0_full_n,
        ap_done => axis_to_nn_784_U0_ap_done,
        ap_continue => axis_to_nn_784_U0_ap_continue,
        ap_idle => axis_to_nn_784_U0_ap_idle,
        ap_ready => axis_to_nn_784_U0_ap_ready,
        stream_in_TVALID => stream_in_TVALID,
        input_to_conv0_din => axis_to_nn_784_U0_input_to_conv0_din,
        input_to_conv0_full_n => input_to_conv0_full_n,
        input_to_conv0_write => axis_to_nn_784_U0_input_to_conv0_write,
        input_to_conv0_num_data_valid => input_to_conv0_num_data_valid,
        input_to_conv0_fifo_cap => input_to_conv0_fifo_cap,
        start_out => axis_to_nn_784_U0_start_out,
        start_write => axis_to_nn_784_U0_start_write,
        stream_in_TDATA => stream_in_TDATA,
        stream_in_TREADY => axis_to_nn_784_U0_stream_in_TREADY,
        stream_in_TKEEP => stream_in_TKEEP,
        stream_in_TSTRB => stream_in_TSTRB,
        stream_in_TLAST => stream_in_TLAST);

    conv_layer_1_28_3_1_8_U0 : component layers_test_conv_layer_1_28_3_1_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_layer_1_28_3_1_8_U0_ap_start,
        start_full_n => start_for_pool_layer_8_28_2_2_U0_full_n,
        ap_done => conv_layer_1_28_3_1_8_U0_ap_done,
        ap_continue => conv_layer_1_28_3_1_8_U0_ap_continue,
        ap_idle => conv_layer_1_28_3_1_8_U0_ap_idle,
        ap_ready => conv_layer_1_28_3_1_8_U0_ap_ready,
        start_out => conv_layer_1_28_3_1_8_U0_start_out,
        start_write => conv_layer_1_28_3_1_8_U0_start_write,
        input_to_conv0_dout => input_to_conv0_dout,
        input_to_conv0_empty_n => input_to_conv0_empty_n,
        input_to_conv0_read => conv_layer_1_28_3_1_8_U0_input_to_conv0_read,
        input_to_conv0_num_data_valid => input_to_conv0_num_data_valid,
        input_to_conv0_fifo_cap => input_to_conv0_fifo_cap,
        conv0_to_pool0_din => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din,
        conv0_to_pool0_full_n => conv0_to_pool0_full_n,
        conv0_to_pool0_write => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write,
        conv0_to_pool0_num_data_valid => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid,
        conv0_to_pool0_fifo_cap => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap);

    pool_layer_8_28_2_2_U0 : component layers_test_pool_layer_8_28_2_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pool_layer_8_28_2_2_U0_ap_start,
        start_full_n => start_for_conv_layer_8_14_3_1_32_U0_full_n,
        ap_done => pool_layer_8_28_2_2_U0_ap_done,
        ap_continue => pool_layer_8_28_2_2_U0_ap_continue,
        ap_idle => pool_layer_8_28_2_2_U0_ap_idle,
        ap_ready => pool_layer_8_28_2_2_U0_ap_ready,
        start_out => pool_layer_8_28_2_2_U0_start_out,
        start_write => pool_layer_8_28_2_2_U0_start_write,
        conv0_to_pool0_dout => conv0_to_pool0_dout,
        conv0_to_pool0_empty_n => conv0_to_pool0_empty_n,
        conv0_to_pool0_read => pool_layer_8_28_2_2_U0_conv0_to_pool0_read,
        conv0_to_pool0_num_data_valid => conv0_to_pool0_num_data_valid,
        conv0_to_pool0_fifo_cap => conv0_to_pool0_fifo_cap,
        pool0_to_conv1_din => pool_layer_8_28_2_2_U0_pool0_to_conv1_din,
        pool0_to_conv1_full_n => pool0_to_conv1_full_n,
        pool0_to_conv1_write => pool_layer_8_28_2_2_U0_pool0_to_conv1_write,
        pool0_to_conv1_num_data_valid => pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid,
        pool0_to_conv1_fifo_cap => pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap);

    conv_layer_8_14_3_1_32_U0 : component layers_test_conv_layer_8_14_3_1_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_layer_8_14_3_1_32_U0_ap_start,
        start_full_n => start_for_pool_layer_32_14_2_2_U0_full_n,
        ap_done => conv_layer_8_14_3_1_32_U0_ap_done,
        ap_continue => conv_layer_8_14_3_1_32_U0_ap_continue,
        ap_idle => conv_layer_8_14_3_1_32_U0_ap_idle,
        ap_ready => conv_layer_8_14_3_1_32_U0_ap_ready,
        start_out => conv_layer_8_14_3_1_32_U0_start_out,
        start_write => conv_layer_8_14_3_1_32_U0_start_write,
        pool0_to_conv1_dout => pool0_to_conv1_dout,
        pool0_to_conv1_empty_n => pool0_to_conv1_empty_n,
        pool0_to_conv1_read => conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read,
        pool0_to_conv1_num_data_valid => pool0_to_conv1_num_data_valid,
        pool0_to_conv1_fifo_cap => pool0_to_conv1_fifo_cap,
        conv1_to_pool1_din => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din,
        conv1_to_pool1_full_n => conv1_to_pool1_full_n,
        conv1_to_pool1_write => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write,
        conv1_to_pool1_num_data_valid => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid,
        conv1_to_pool1_fifo_cap => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap);

    pool_layer_32_14_2_2_U0 : component layers_test_pool_layer_32_14_2_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pool_layer_32_14_2_2_U0_ap_start,
        start_full_n => start_for_pool_layer_32_7_2_2_U0_full_n,
        ap_done => pool_layer_32_14_2_2_U0_ap_done,
        ap_continue => pool_layer_32_14_2_2_U0_ap_continue,
        ap_idle => pool_layer_32_14_2_2_U0_ap_idle,
        ap_ready => pool_layer_32_14_2_2_U0_ap_ready,
        start_out => pool_layer_32_14_2_2_U0_start_out,
        start_write => pool_layer_32_14_2_2_U0_start_write,
        conv1_to_pool1_dout => conv1_to_pool1_dout,
        conv1_to_pool1_empty_n => conv1_to_pool1_empty_n,
        conv1_to_pool1_read => pool_layer_32_14_2_2_U0_conv1_to_pool1_read,
        conv1_to_pool1_num_data_valid => conv1_to_pool1_num_data_valid,
        conv1_to_pool1_fifo_cap => conv1_to_pool1_fifo_cap,
        pool1_to_pool2_din => pool_layer_32_14_2_2_U0_pool1_to_pool2_din,
        pool1_to_pool2_full_n => pool1_to_pool2_full_n,
        pool1_to_pool2_write => pool_layer_32_14_2_2_U0_pool1_to_pool2_write,
        pool1_to_pool2_num_data_valid => pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid,
        pool1_to_pool2_fifo_cap => pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap);

    pool_layer_32_7_2_2_U0 : component layers_test_pool_layer_32_7_2_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pool_layer_32_7_2_2_U0_ap_start,
        start_full_n => start_for_fc_layer_288_10_U0_full_n,
        ap_done => pool_layer_32_7_2_2_U0_ap_done,
        ap_continue => pool_layer_32_7_2_2_U0_ap_continue,
        ap_idle => pool_layer_32_7_2_2_U0_ap_idle,
        ap_ready => pool_layer_32_7_2_2_U0_ap_ready,
        start_out => pool_layer_32_7_2_2_U0_start_out,
        start_write => pool_layer_32_7_2_2_U0_start_write,
        pool1_to_pool2_dout => pool1_to_pool2_dout,
        pool1_to_pool2_empty_n => pool1_to_pool2_empty_n,
        pool1_to_pool2_read => pool_layer_32_7_2_2_U0_pool1_to_pool2_read,
        pool1_to_pool2_num_data_valid => pool1_to_pool2_num_data_valid,
        pool1_to_pool2_fifo_cap => pool1_to_pool2_fifo_cap,
        pool2_to_fc0_din => pool_layer_32_7_2_2_U0_pool2_to_fc0_din,
        pool2_to_fc0_full_n => pool2_to_fc0_full_n,
        pool2_to_fc0_write => pool_layer_32_7_2_2_U0_pool2_to_fc0_write,
        pool2_to_fc0_num_data_valid => pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid,
        pool2_to_fc0_fifo_cap => pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap);

    fc_layer_288_10_U0 : component layers_test_fc_layer_288_10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fc_layer_288_10_U0_ap_start,
        start_full_n => start_for_argmax_10_U0_full_n,
        ap_done => fc_layer_288_10_U0_ap_done,
        ap_continue => fc_layer_288_10_U0_ap_continue,
        ap_idle => fc_layer_288_10_U0_ap_idle,
        ap_ready => fc_layer_288_10_U0_ap_ready,
        start_out => fc_layer_288_10_U0_start_out,
        start_write => fc_layer_288_10_U0_start_write,
        pool2_to_fc0_dout => pool2_to_fc0_dout,
        pool2_to_fc0_empty_n => pool2_to_fc0_empty_n,
        pool2_to_fc0_read => fc_layer_288_10_U0_pool2_to_fc0_read,
        pool2_to_fc0_num_data_valid => pool2_to_fc0_num_data_valid,
        pool2_to_fc0_fifo_cap => pool2_to_fc0_fifo_cap,
        fc0_to_argmax0_din => fc_layer_288_10_U0_fc0_to_argmax0_din,
        fc0_to_argmax0_full_n => fc0_to_argmax0_full_n,
        fc0_to_argmax0_write => fc_layer_288_10_U0_fc0_to_argmax0_write,
        fc0_to_argmax0_num_data_valid => fc0_to_argmax0_num_data_valid,
        fc0_to_argmax0_fifo_cap => fc0_to_argmax0_fifo_cap);

    argmax_10_U0 : component layers_test_argmax_10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => argmax_10_U0_ap_start,
        start_full_n => start_for_nn_to_axis_1_U0_full_n,
        ap_done => argmax_10_U0_ap_done,
        ap_continue => argmax_10_U0_ap_continue,
        ap_idle => argmax_10_U0_ap_idle,
        ap_ready => argmax_10_U0_ap_ready,
        start_out => argmax_10_U0_start_out,
        start_write => argmax_10_U0_start_write,
        fc0_to_argmax0_dout => fc0_to_argmax0_dout,
        fc0_to_argmax0_empty_n => fc0_to_argmax0_empty_n,
        fc0_to_argmax0_read => argmax_10_U0_fc0_to_argmax0_read,
        fc0_to_argmax0_num_data_valid => fc0_to_argmax0_num_data_valid,
        fc0_to_argmax0_fifo_cap => fc0_to_argmax0_fifo_cap,
        argmax0_to_output_din => argmax_10_U0_argmax0_to_output_din,
        argmax0_to_output_full_n => argmax0_to_output_full_n,
        argmax0_to_output_write => argmax_10_U0_argmax0_to_output_write,
        argmax0_to_output_num_data_valid => argmax0_to_output_num_data_valid,
        argmax0_to_output_fifo_cap => argmax0_to_output_fifo_cap);

    nn_to_axis_1_U0 : component layers_test_nn_to_axis_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => nn_to_axis_1_U0_ap_start,
        ap_done => nn_to_axis_1_U0_ap_done,
        ap_continue => nn_to_axis_1_U0_ap_continue,
        ap_idle => nn_to_axis_1_U0_ap_idle,
        ap_ready => nn_to_axis_1_U0_ap_ready,
        argmax0_to_output_dout => argmax0_to_output_dout,
        argmax0_to_output_empty_n => argmax0_to_output_empty_n,
        argmax0_to_output_read => nn_to_axis_1_U0_argmax0_to_output_read,
        argmax0_to_output_num_data_valid => argmax0_to_output_num_data_valid,
        argmax0_to_output_fifo_cap => argmax0_to_output_fifo_cap,
        stream_out_TDATA => nn_to_axis_1_U0_stream_out_TDATA,
        stream_out_TVALID => nn_to_axis_1_U0_stream_out_TVALID,
        stream_out_TREADY => stream_out_TREADY,
        stream_out_TKEEP => nn_to_axis_1_U0_stream_out_TKEEP,
        stream_out_TSTRB => nn_to_axis_1_U0_stream_out_TSTRB,
        stream_out_TLAST => nn_to_axis_1_U0_stream_out_TLAST);

    input_to_conv0_U : component layers_test_fifo_w8_d1000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_nn_784_U0_input_to_conv0_din,
        if_full_n => input_to_conv0_full_n,
        if_write => axis_to_nn_784_U0_input_to_conv0_write,
        if_dout => input_to_conv0_dout,
        if_empty_n => input_to_conv0_empty_n,
        if_read => conv_layer_1_28_3_1_8_U0_input_to_conv0_read,
        if_num_data_valid => input_to_conv0_num_data_valid,
        if_fifo_cap => input_to_conv0_fifo_cap);

    conv0_to_pool0_U : component layers_test_fifo_w8_d10000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din,
        if_full_n => conv0_to_pool0_full_n,
        if_write => conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write,
        if_dout => conv0_to_pool0_dout,
        if_empty_n => conv0_to_pool0_empty_n,
        if_read => pool_layer_8_28_2_2_U0_conv0_to_pool0_read,
        if_num_data_valid => conv0_to_pool0_num_data_valid,
        if_fifo_cap => conv0_to_pool0_fifo_cap);

    pool0_to_conv1_U : component layers_test_fifo_w8_d2000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pool_layer_8_28_2_2_U0_pool0_to_conv1_din,
        if_full_n => pool0_to_conv1_full_n,
        if_write => pool_layer_8_28_2_2_U0_pool0_to_conv1_write,
        if_dout => pool0_to_conv1_dout,
        if_empty_n => pool0_to_conv1_empty_n,
        if_read => conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read,
        if_num_data_valid => pool0_to_conv1_num_data_valid,
        if_fifo_cap => pool0_to_conv1_fifo_cap);

    conv1_to_pool1_U : component layers_test_fifo_w8_d10000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din,
        if_full_n => conv1_to_pool1_full_n,
        if_write => conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write,
        if_dout => conv1_to_pool1_dout,
        if_empty_n => conv1_to_pool1_empty_n,
        if_read => pool_layer_32_14_2_2_U0_conv1_to_pool1_read,
        if_num_data_valid => conv1_to_pool1_num_data_valid,
        if_fifo_cap => conv1_to_pool1_fifo_cap);

    pool1_to_pool2_U : component layers_test_fifo_w8_d2000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pool_layer_32_14_2_2_U0_pool1_to_pool2_din,
        if_full_n => pool1_to_pool2_full_n,
        if_write => pool_layer_32_14_2_2_U0_pool1_to_pool2_write,
        if_dout => pool1_to_pool2_dout,
        if_empty_n => pool1_to_pool2_empty_n,
        if_read => pool_layer_32_7_2_2_U0_pool1_to_pool2_read,
        if_num_data_valid => pool1_to_pool2_num_data_valid,
        if_fifo_cap => pool1_to_pool2_fifo_cap);

    pool2_to_fc0_U : component layers_test_fifo_w8_d3000_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pool_layer_32_7_2_2_U0_pool2_to_fc0_din,
        if_full_n => pool2_to_fc0_full_n,
        if_write => pool_layer_32_7_2_2_U0_pool2_to_fc0_write,
        if_dout => pool2_to_fc0_dout,
        if_empty_n => pool2_to_fc0_empty_n,
        if_read => fc_layer_288_10_U0_pool2_to_fc0_read,
        if_num_data_valid => pool2_to_fc0_num_data_valid,
        if_fifo_cap => pool2_to_fc0_fifo_cap);

    fc0_to_argmax0_U : component layers_test_fifo_w8_d100_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fc_layer_288_10_U0_fc0_to_argmax0_din,
        if_full_n => fc0_to_argmax0_full_n,
        if_write => fc_layer_288_10_U0_fc0_to_argmax0_write,
        if_dout => fc0_to_argmax0_dout,
        if_empty_n => fc0_to_argmax0_empty_n,
        if_read => argmax_10_U0_fc0_to_argmax0_read,
        if_num_data_valid => fc0_to_argmax0_num_data_valid,
        if_fifo_cap => fc0_to_argmax0_fifo_cap);

    argmax0_to_output_U : component layers_test_fifo_w8_d10_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => argmax_10_U0_argmax0_to_output_din,
        if_full_n => argmax0_to_output_full_n,
        if_write => argmax_10_U0_argmax0_to_output_write,
        if_dout => argmax0_to_output_dout,
        if_empty_n => argmax0_to_output_empty_n,
        if_read => nn_to_axis_1_U0_argmax0_to_output_read,
        if_num_data_valid => argmax0_to_output_num_data_valid,
        if_fifo_cap => argmax0_to_output_fifo_cap);

    start_for_conv_layer_1_28_3_1_8_U0_U : component layers_test_start_for_conv_layer_1_28_3_1_8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_layer_1_28_3_1_8_U0_din,
        if_full_n => start_for_conv_layer_1_28_3_1_8_U0_full_n,
        if_write => axis_to_nn_784_U0_start_write,
        if_dout => start_for_conv_layer_1_28_3_1_8_U0_dout,
        if_empty_n => start_for_conv_layer_1_28_3_1_8_U0_empty_n,
        if_read => conv_layer_1_28_3_1_8_U0_ap_ready);

    start_for_pool_layer_8_28_2_2_U0_U : component layers_test_start_for_pool_layer_8_28_2_2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pool_layer_8_28_2_2_U0_din,
        if_full_n => start_for_pool_layer_8_28_2_2_U0_full_n,
        if_write => conv_layer_1_28_3_1_8_U0_start_write,
        if_dout => start_for_pool_layer_8_28_2_2_U0_dout,
        if_empty_n => start_for_pool_layer_8_28_2_2_U0_empty_n,
        if_read => pool_layer_8_28_2_2_U0_ap_ready);

    start_for_conv_layer_8_14_3_1_32_U0_U : component layers_test_start_for_conv_layer_8_14_3_1_32_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_layer_8_14_3_1_32_U0_din,
        if_full_n => start_for_conv_layer_8_14_3_1_32_U0_full_n,
        if_write => pool_layer_8_28_2_2_U0_start_write,
        if_dout => start_for_conv_layer_8_14_3_1_32_U0_dout,
        if_empty_n => start_for_conv_layer_8_14_3_1_32_U0_empty_n,
        if_read => conv_layer_8_14_3_1_32_U0_ap_ready);

    start_for_pool_layer_32_14_2_2_U0_U : component layers_test_start_for_pool_layer_32_14_2_2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pool_layer_32_14_2_2_U0_din,
        if_full_n => start_for_pool_layer_32_14_2_2_U0_full_n,
        if_write => conv_layer_8_14_3_1_32_U0_start_write,
        if_dout => start_for_pool_layer_32_14_2_2_U0_dout,
        if_empty_n => start_for_pool_layer_32_14_2_2_U0_empty_n,
        if_read => pool_layer_32_14_2_2_U0_ap_ready);

    start_for_pool_layer_32_7_2_2_U0_U : component layers_test_start_for_pool_layer_32_7_2_2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pool_layer_32_7_2_2_U0_din,
        if_full_n => start_for_pool_layer_32_7_2_2_U0_full_n,
        if_write => pool_layer_32_14_2_2_U0_start_write,
        if_dout => start_for_pool_layer_32_7_2_2_U0_dout,
        if_empty_n => start_for_pool_layer_32_7_2_2_U0_empty_n,
        if_read => pool_layer_32_7_2_2_U0_ap_ready);

    start_for_fc_layer_288_10_U0_U : component layers_test_start_for_fc_layer_288_10_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fc_layer_288_10_U0_din,
        if_full_n => start_for_fc_layer_288_10_U0_full_n,
        if_write => pool_layer_32_7_2_2_U0_start_write,
        if_dout => start_for_fc_layer_288_10_U0_dout,
        if_empty_n => start_for_fc_layer_288_10_U0_empty_n,
        if_read => fc_layer_288_10_U0_ap_ready);

    start_for_argmax_10_U0_U : component layers_test_start_for_argmax_10_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_argmax_10_U0_din,
        if_full_n => start_for_argmax_10_U0_full_n,
        if_write => fc_layer_288_10_U0_start_write,
        if_dout => start_for_argmax_10_U0_dout,
        if_empty_n => start_for_argmax_10_U0_empty_n,
        if_read => argmax_10_U0_ap_ready);

    start_for_nn_to_axis_1_U0_U : component layers_test_start_for_nn_to_axis_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_nn_to_axis_1_U0_din,
        if_full_n => start_for_nn_to_axis_1_U0_full_n,
        if_write => argmax_10_U0_start_write,
        if_dout => start_for_nn_to_axis_1_U0_dout,
        if_empty_n => start_for_nn_to_axis_1_U0_empty_n,
        if_read => nn_to_axis_1_U0_ap_ready);





    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    argmax_10_U0_ap_continue <= ap_const_logic_1;
    argmax_10_U0_ap_start <= start_for_argmax_10_U0_empty_n;
    axis_to_nn_784_U0_ap_continue <= ap_const_logic_1;
    axis_to_nn_784_U0_ap_start <= ap_const_logic_1;
    conv_layer_1_28_3_1_8_U0_ap_continue <= ap_const_logic_1;
    conv_layer_1_28_3_1_8_U0_ap_start <= start_for_conv_layer_1_28_3_1_8_U0_empty_n;
    conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(conv0_to_pool0_fifo_cap),15))),32));
    conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(conv0_to_pool0_num_data_valid),15))),32));
    conv_layer_8_14_3_1_32_U0_ap_continue <= ap_const_logic_1;
    conv_layer_8_14_3_1_32_U0_ap_start <= start_for_conv_layer_8_14_3_1_32_U0_empty_n;
    conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(conv1_to_pool1_fifo_cap),15))),32));
    conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(conv1_to_pool1_num_data_valid),15))),32));
    fc_layer_288_10_U0_ap_continue <= ap_const_logic_1;
    fc_layer_288_10_U0_ap_start <= start_for_fc_layer_288_10_U0_empty_n;
    nn_to_axis_1_U0_ap_continue <= ap_const_logic_1;
    nn_to_axis_1_U0_ap_start <= start_for_nn_to_axis_1_U0_empty_n;
    pool_layer_32_14_2_2_U0_ap_continue <= ap_const_logic_1;
    pool_layer_32_14_2_2_U0_ap_start <= start_for_pool_layer_32_14_2_2_U0_empty_n;
    pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool1_to_pool2_fifo_cap),12))),32));
    pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool1_to_pool2_num_data_valid),12))),32));
    pool_layer_32_7_2_2_U0_ap_continue <= ap_const_logic_1;
    pool_layer_32_7_2_2_U0_ap_start <= start_for_pool_layer_32_7_2_2_U0_empty_n;
    pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool2_to_fc0_fifo_cap),13))),32));
    pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool2_to_fc0_num_data_valid),13))),32));
    pool_layer_8_28_2_2_U0_ap_continue <= ap_const_logic_1;
    pool_layer_8_28_2_2_U0_ap_start <= start_for_pool_layer_8_28_2_2_U0_empty_n;
    pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool0_to_conv1_fifo_cap),12))),32));
    pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(pool0_to_conv1_num_data_valid),12))),32));
    start_for_argmax_10_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_conv_layer_1_28_3_1_8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_conv_layer_8_14_3_1_32_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_fc_layer_288_10_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_nn_to_axis_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pool_layer_32_14_2_2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pool_layer_32_7_2_2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pool_layer_8_28_2_2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    stream_in_TREADY <= axis_to_nn_784_U0_stream_in_TREADY;
    stream_out_TDATA <= nn_to_axis_1_U0_stream_out_TDATA;
    stream_out_TKEEP <= nn_to_axis_1_U0_stream_out_TKEEP;
    stream_out_TLAST <= nn_to_axis_1_U0_stream_out_TLAST;
    stream_out_TSTRB <= nn_to_axis_1_U0_stream_out_TSTRB;
    stream_out_TVALID <= nn_to_axis_1_U0_stream_out_TVALID;
end behav;
