-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity layers_test_conv_layer_Pipeline_VITIS_LOOP_46_4_VITIS_LOOP_47_5_VITIS_LOOP_48_6_VITIS_LOOxdS is 
    generic(
             DataWidth     : integer := 21; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of layers_test_conv_layer_Pipeline_VITIS_LOOP_46_4_VITIS_LOOP_47_5_VITIS_LOOP_48_6_VITIS_LOOxdS is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "101000001010100001011", 1 => "100101101110010111100", 2 => "100111010001000110000", 3 => "100010111001001100111", 
    4 => "101101111010000100100", 5 => "111011011001011001110", 6 => "110100010111111010000", 7 => "100000000001010100111", 
    8 => "100110110100110100010", 9 => "100100000101001001100", 10 => "101010101000000101000", 11 => "110111100011111111010", 
    12 => "010101001000110001001", 13 => "101110000001010100011", 14 => "100000001101101111101", 15 => "000111010111101110010", 
    16 => "101111101001001011100", 17 => "010110111000101010101", 18 => "011110100001100100111", 19 => "100101011011001111010", 
    20 => "100101011101111000000", 21 => "011100011011001011111", 22 => "011011101101001000010", 23 => "110010101101101010010", 
    24 => "100100011010100100011", 25 => "100000111101101010110", 26 => "100101100000001000101", 27 => "101101010101111010101", 
    28 => "100101100010011011101", 29 => "100101011010010110001", 30 => "100011101011000010011", 31 => "011100110100110000000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "distributed"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "distributed";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

