// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_pool_layer_8_28_2_2_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv0_to_pool0_dout,
        conv0_to_pool0_empty_n,
        conv0_to_pool0_read,
        conv0_to_pool0_num_data_valid,
        conv0_to_pool0_fifo_cap,
        IN_r_address1,
        IN_r_ce1,
        IN_r_we1,
        IN_r_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] conv0_to_pool0_dout;
input   conv0_to_pool0_empty_n;
output   conv0_to_pool0_read;
input  [14:0] conv0_to_pool0_num_data_valid;
input  [14:0] conv0_to_pool0_fifo_cap;
output  [12:0] IN_r_address1;
output   IN_r_ce1;
output   IN_r_we1;
output  [7:0] IN_r_d1;

reg ap_idle;
reg conv0_to_pool0_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln23_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    conv0_to_pool0_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln24_fu_159_p2;
reg   [0:0] icmp_ln24_reg_399;
reg   [0:0] icmp_ln24_reg_399_pp0_iter1_reg;
wire   [4:0] icol_mid2_fu_230_p3;
reg   [4:0] icol_mid2_reg_407;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [4:0] icol_mid2_reg_407_pp0_iter2_reg;
wire   [4:0] select_ln24_fu_238_p3;
reg   [4:0] select_ln24_reg_412;
wire   [8:0] add_ln27_fu_307_p2;
reg   [8:0] add_ln27_reg_417;
wire   [7:0] trunc_ln27_fu_313_p1;
reg   [7:0] trunc_ln27_reg_422;
wire   [63:0] zext_ln27_8_fu_355_p1;
reg   [4:0] icol_fu_72;
wire   [4:0] add_ln25_fu_246_p2;
wire    ap_loop_init;
reg   [4:0] irow_fu_76;
reg   [9:0] indvar_flatten_fu_80;
wire   [9:0] select_ln24_1_fu_171_p3;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [3:0] ich_fu_84;
wire   [3:0] select_ln23_1_fu_271_p3;
reg   [12:0] indvar_flatten14_fu_88;
wire   [12:0] add_ln23_1_fu_150_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten14_load;
reg    IN_r_we1_local;
reg    IN_r_ce1_local;
wire   [9:0] add_ln24_1_fu_165_p2;
wire   [0:0] icmp_ln25_fu_207_p2;
wire   [0:0] xor_ln23_fu_202_p2;
wire   [4:0] select_ln23_fu_195_p3;
wire   [0:0] and_ln23_fu_213_p2;
wire   [0:0] empty_fu_225_p2;
wire   [4:0] add_ln24_fu_219_p2;
wire   [3:0] add_ln23_fu_265_p2;
wire   [5:0] tmp_fu_286_p3;
wire   [8:0] p_shl8_fu_278_p3;
wire   [8:0] zext_ln27_fu_294_p1;
wire   [8:0] sub_ln27_fu_298_p2;
wire   [8:0] zext_ln27_5_fu_304_p1;
wire   [10:0] tmp_15_fu_322_p3;
wire   [12:0] tmp_16_fu_329_p3;
wire   [12:0] zext_ln27_6_fu_336_p1;
wire   [12:0] sub_ln25_fu_340_p2;
wire   [12:0] zext_ln27_7_fu_346_p1;
wire   [12:0] add_ln27_1_fu_349_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 icol_fu_72 = 5'd0;
#0 irow_fu_76 = 5'd0;
#0 indvar_flatten_fu_80 = 10'd0;
#0 ich_fu_84 = 4'd0;
#0 indvar_flatten14_fu_88 = 13'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            ich_fu_84 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ich_fu_84 <= select_ln23_1_fu_271_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            icol_fu_72 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            icol_fu_72 <= add_ln25_fu_246_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln23_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten14_fu_88 <= add_ln23_1_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_88 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln23_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_80 <= select_ln24_1_fu_171_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_80 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            irow_fu_76 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            irow_fu_76 <= select_ln24_fu_238_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln27_reg_417 <= add_ln27_fu_307_p2;
        icol_mid2_reg_407_pp0_iter2_reg <= icol_mid2_reg_407;
        trunc_ln27_reg_422 <= trunc_ln27_fu_313_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln24_reg_399 <= icmp_ln24_fu_159_p2;
        icmp_ln24_reg_399_pp0_iter1_reg <= icmp_ln24_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icol_mid2_reg_407 <= icol_mid2_fu_230_p3;
        select_ln24_reg_412 <= select_ln24_fu_238_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        IN_r_ce1_local = 1'b1;
    end else begin
        IN_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        IN_r_we1_local = 1'b1;
    end else begin
        IN_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten14_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten14_load = indvar_flatten14_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv0_to_pool0_blk_n = conv0_to_pool0_empty_n;
    end else begin
        conv0_to_pool0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv0_to_pool0_read = 1'b1;
    end else begin
        conv0_to_pool0_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_r_address1 = zext_ln27_8_fu_355_p1;

assign IN_r_ce1 = IN_r_ce1_local;

assign IN_r_d1 = conv0_to_pool0_dout;

assign IN_r_we1 = IN_r_we1_local;

assign add_ln23_1_fu_150_p2 = (ap_sig_allocacmp_indvar_flatten14_load + 13'd1);

assign add_ln23_fu_265_p2 = (ich_fu_84 + 4'd1);

assign add_ln24_1_fu_165_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln24_fu_219_p2 = (select_ln23_fu_195_p3 + 5'd1);

assign add_ln25_fu_246_p2 = (icol_mid2_fu_230_p3 + 5'd1);

assign add_ln27_1_fu_349_p2 = (sub_ln25_fu_340_p2 + zext_ln27_7_fu_346_p1);

assign add_ln27_fu_307_p2 = (sub_ln27_fu_298_p2 + zext_ln27_5_fu_304_p1);

assign and_ln23_fu_213_p2 = (xor_ln23_fu_202_p2 & icmp_ln25_fu_207_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((conv0_to_pool0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((conv0_to_pool0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((conv0_to_pool0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_225_p2 = (icmp_ln24_reg_399 | and_ln23_fu_213_p2);

assign icmp_ln23_fu_144_p2 = ((ap_sig_allocacmp_indvar_flatten14_load == 13'd6272) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_159_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_207_p2 = ((icol_fu_72 == 5'd28) ? 1'b1 : 1'b0);

assign icol_mid2_fu_230_p3 = ((empty_fu_225_p2[0:0] == 1'b1) ? 5'd0 : icol_fu_72);

assign p_shl8_fu_278_p3 = {{select_ln23_1_fu_271_p3}, {5'd0}};

assign select_ln23_1_fu_271_p3 = ((icmp_ln24_reg_399_pp0_iter1_reg[0:0] == 1'b1) ? add_ln23_fu_265_p2 : ich_fu_84);

assign select_ln23_fu_195_p3 = ((icmp_ln24_reg_399[0:0] == 1'b1) ? 5'd0 : irow_fu_76);

assign select_ln24_1_fu_171_p3 = ((icmp_ln24_fu_159_p2[0:0] == 1'b1) ? 10'd1 : add_ln24_1_fu_165_p2);

assign select_ln24_fu_238_p3 = ((and_ln23_fu_213_p2[0:0] == 1'b1) ? add_ln24_fu_219_p2 : select_ln23_fu_195_p3);

assign sub_ln25_fu_340_p2 = (tmp_16_fu_329_p3 - zext_ln27_6_fu_336_p1);

assign sub_ln27_fu_298_p2 = (p_shl8_fu_278_p3 - zext_ln27_fu_294_p1);

assign tmp_15_fu_322_p3 = {{add_ln27_reg_417}, {2'd0}};

assign tmp_16_fu_329_p3 = {{trunc_ln27_reg_422}, {5'd0}};

assign tmp_fu_286_p3 = {{select_ln23_1_fu_271_p3}, {2'd0}};

assign trunc_ln27_fu_313_p1 = add_ln27_fu_307_p2[7:0];

assign xor_ln23_fu_202_p2 = (icmp_ln24_reg_399 ^ 1'd1);

assign zext_ln27_5_fu_304_p1 = select_ln24_reg_412;

assign zext_ln27_6_fu_336_p1 = tmp_15_fu_322_p3;

assign zext_ln27_7_fu_346_p1 = icol_mid2_reg_407_pp0_iter2_reg;

assign zext_ln27_8_fu_355_p1 = add_ln27_1_fu_349_p2;

assign zext_ln27_fu_294_p1 = tmp_fu_286_p3;

endmodule //layers_test_pool_layer_8_28_2_2_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3
