// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="layers_test_layers_test,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.038000,HLS_SYN_LAT=51800,HLS_SYN_TPT=51777,HLS_SYN_MEM=41,HLS_SYN_DSP=0,HLS_SYN_FF=13125,HLS_SYN_LUT=33433,HLS_VERSION=2024_2}" *)

module layers_test (
        stream_in_TDATA,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TLAST,
        stream_out_TDATA,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TLAST,
        ap_clk,
        ap_rst_n,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);


input  [7:0] stream_in_TDATA;
input  [0:0] stream_in_TKEEP;
input  [0:0] stream_in_TSTRB;
input  [0:0] stream_in_TLAST;
output  [7:0] stream_out_TDATA;
output  [0:0] stream_out_TKEEP;
output  [0:0] stream_out_TSTRB;
output  [0:0] stream_out_TLAST;
input   ap_clk;
input   ap_rst_n;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    axis_to_nn_784_U0_ap_start;
wire    axis_to_nn_784_U0_ap_done;
wire    axis_to_nn_784_U0_ap_continue;
wire    axis_to_nn_784_U0_ap_idle;
wire    axis_to_nn_784_U0_ap_ready;
wire   [7:0] axis_to_nn_784_U0_input_to_conv0_din;
wire    axis_to_nn_784_U0_input_to_conv0_write;
wire    axis_to_nn_784_U0_start_out;
wire    axis_to_nn_784_U0_start_write;
wire    axis_to_nn_784_U0_stream_in_TREADY;
wire    conv_layer_1_28_3_1_8_U0_ap_start;
wire    conv_layer_1_28_3_1_8_U0_ap_done;
wire    conv_layer_1_28_3_1_8_U0_ap_continue;
wire    conv_layer_1_28_3_1_8_U0_ap_idle;
wire    conv_layer_1_28_3_1_8_U0_ap_ready;
wire    conv_layer_1_28_3_1_8_U0_start_out;
wire    conv_layer_1_28_3_1_8_U0_start_write;
wire    conv_layer_1_28_3_1_8_U0_input_to_conv0_read;
wire   [7:0] conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din;
wire    conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write;
wire   [31:0] conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid;
wire   [31:0] conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap;
wire    pool_layer_8_28_2_2_U0_ap_start;
wire    pool_layer_8_28_2_2_U0_ap_done;
wire    pool_layer_8_28_2_2_U0_ap_continue;
wire    pool_layer_8_28_2_2_U0_ap_idle;
wire    pool_layer_8_28_2_2_U0_ap_ready;
wire    pool_layer_8_28_2_2_U0_start_out;
wire    pool_layer_8_28_2_2_U0_start_write;
wire    pool_layer_8_28_2_2_U0_conv0_to_pool0_read;
wire   [7:0] pool_layer_8_28_2_2_U0_pool0_to_conv1_din;
wire    pool_layer_8_28_2_2_U0_pool0_to_conv1_write;
wire   [31:0] pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid;
wire   [31:0] pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap;
wire    conv_layer_8_14_3_1_32_U0_ap_start;
wire    conv_layer_8_14_3_1_32_U0_ap_done;
wire    conv_layer_8_14_3_1_32_U0_ap_continue;
wire    conv_layer_8_14_3_1_32_U0_ap_idle;
wire    conv_layer_8_14_3_1_32_U0_ap_ready;
wire    conv_layer_8_14_3_1_32_U0_start_out;
wire    conv_layer_8_14_3_1_32_U0_start_write;
wire    conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read;
wire   [7:0] conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din;
wire    conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write;
wire   [31:0] conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid;
wire   [31:0] conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap;
wire    pool_layer_32_14_2_2_U0_ap_start;
wire    pool_layer_32_14_2_2_U0_ap_done;
wire    pool_layer_32_14_2_2_U0_ap_continue;
wire    pool_layer_32_14_2_2_U0_ap_idle;
wire    pool_layer_32_14_2_2_U0_ap_ready;
wire    pool_layer_32_14_2_2_U0_start_out;
wire    pool_layer_32_14_2_2_U0_start_write;
wire    pool_layer_32_14_2_2_U0_conv1_to_pool1_read;
wire   [7:0] pool_layer_32_14_2_2_U0_pool1_to_pool2_din;
wire    pool_layer_32_14_2_2_U0_pool1_to_pool2_write;
wire   [31:0] pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid;
wire   [31:0] pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap;
wire    pool_layer_32_7_2_2_U0_ap_start;
wire    pool_layer_32_7_2_2_U0_ap_done;
wire    pool_layer_32_7_2_2_U0_ap_continue;
wire    pool_layer_32_7_2_2_U0_ap_idle;
wire    pool_layer_32_7_2_2_U0_ap_ready;
wire    pool_layer_32_7_2_2_U0_start_out;
wire    pool_layer_32_7_2_2_U0_start_write;
wire    pool_layer_32_7_2_2_U0_pool1_to_pool2_read;
wire   [7:0] pool_layer_32_7_2_2_U0_pool2_to_fc0_din;
wire    pool_layer_32_7_2_2_U0_pool2_to_fc0_write;
wire   [31:0] pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid;
wire   [31:0] pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap;
wire    fc_layer_288_10_U0_ap_start;
wire    fc_layer_288_10_U0_ap_done;
wire    fc_layer_288_10_U0_ap_continue;
wire    fc_layer_288_10_U0_ap_idle;
wire    fc_layer_288_10_U0_ap_ready;
wire    fc_layer_288_10_U0_start_out;
wire    fc_layer_288_10_U0_start_write;
wire    fc_layer_288_10_U0_pool2_to_fc0_read;
wire   [7:0] fc_layer_288_10_U0_fc0_to_argmax0_din;
wire    fc_layer_288_10_U0_fc0_to_argmax0_write;
wire    argmax_10_U0_ap_start;
wire    argmax_10_U0_ap_done;
wire    argmax_10_U0_ap_continue;
wire    argmax_10_U0_ap_idle;
wire    argmax_10_U0_ap_ready;
wire    argmax_10_U0_start_out;
wire    argmax_10_U0_start_write;
wire    argmax_10_U0_fc0_to_argmax0_read;
wire   [7:0] argmax_10_U0_argmax0_to_output_din;
wire    argmax_10_U0_argmax0_to_output_write;
wire    nn_to_axis_1_U0_ap_start;
wire    nn_to_axis_1_U0_ap_done;
wire    nn_to_axis_1_U0_ap_continue;
wire    nn_to_axis_1_U0_ap_idle;
wire    nn_to_axis_1_U0_ap_ready;
wire    nn_to_axis_1_U0_argmax0_to_output_read;
wire   [7:0] nn_to_axis_1_U0_stream_out_TDATA;
wire    nn_to_axis_1_U0_stream_out_TVALID;
wire   [0:0] nn_to_axis_1_U0_stream_out_TKEEP;
wire   [0:0] nn_to_axis_1_U0_stream_out_TSTRB;
wire   [0:0] nn_to_axis_1_U0_stream_out_TLAST;
wire    input_to_conv0_full_n;
wire   [7:0] input_to_conv0_dout;
wire    input_to_conv0_empty_n;
wire   [10:0] input_to_conv0_num_data_valid;
wire   [10:0] input_to_conv0_fifo_cap;
wire    conv0_to_pool0_full_n;
wire   [7:0] conv0_to_pool0_dout;
wire    conv0_to_pool0_empty_n;
wire   [14:0] conv0_to_pool0_num_data_valid;
wire   [14:0] conv0_to_pool0_fifo_cap;
wire    pool0_to_conv1_full_n;
wire   [7:0] pool0_to_conv1_dout;
wire    pool0_to_conv1_empty_n;
wire   [11:0] pool0_to_conv1_num_data_valid;
wire   [11:0] pool0_to_conv1_fifo_cap;
wire    conv1_to_pool1_full_n;
wire   [7:0] conv1_to_pool1_dout;
wire    conv1_to_pool1_empty_n;
wire   [14:0] conv1_to_pool1_num_data_valid;
wire   [14:0] conv1_to_pool1_fifo_cap;
wire    pool1_to_pool2_full_n;
wire   [7:0] pool1_to_pool2_dout;
wire    pool1_to_pool2_empty_n;
wire   [11:0] pool1_to_pool2_num_data_valid;
wire   [11:0] pool1_to_pool2_fifo_cap;
wire    pool2_to_fc0_full_n;
wire   [7:0] pool2_to_fc0_dout;
wire    pool2_to_fc0_empty_n;
wire   [12:0] pool2_to_fc0_num_data_valid;
wire   [12:0] pool2_to_fc0_fifo_cap;
wire    fc0_to_argmax0_full_n;
wire   [7:0] fc0_to_argmax0_dout;
wire    fc0_to_argmax0_empty_n;
wire   [7:0] fc0_to_argmax0_num_data_valid;
wire   [7:0] fc0_to_argmax0_fifo_cap;
wire    argmax0_to_output_full_n;
wire   [7:0] argmax0_to_output_dout;
wire    argmax0_to_output_empty_n;
wire   [4:0] argmax0_to_output_num_data_valid;
wire   [4:0] argmax0_to_output_fifo_cap;
wire   [0:0] start_for_conv_layer_1_28_3_1_8_U0_din;
wire    start_for_conv_layer_1_28_3_1_8_U0_full_n;
wire   [0:0] start_for_conv_layer_1_28_3_1_8_U0_dout;
wire    start_for_conv_layer_1_28_3_1_8_U0_empty_n;
wire   [0:0] start_for_pool_layer_8_28_2_2_U0_din;
wire    start_for_pool_layer_8_28_2_2_U0_full_n;
wire   [0:0] start_for_pool_layer_8_28_2_2_U0_dout;
wire    start_for_pool_layer_8_28_2_2_U0_empty_n;
wire   [0:0] start_for_conv_layer_8_14_3_1_32_U0_din;
wire    start_for_conv_layer_8_14_3_1_32_U0_full_n;
wire   [0:0] start_for_conv_layer_8_14_3_1_32_U0_dout;
wire    start_for_conv_layer_8_14_3_1_32_U0_empty_n;
wire   [0:0] start_for_pool_layer_32_14_2_2_U0_din;
wire    start_for_pool_layer_32_14_2_2_U0_full_n;
wire   [0:0] start_for_pool_layer_32_14_2_2_U0_dout;
wire    start_for_pool_layer_32_14_2_2_U0_empty_n;
wire   [0:0] start_for_pool_layer_32_7_2_2_U0_din;
wire    start_for_pool_layer_32_7_2_2_U0_full_n;
wire   [0:0] start_for_pool_layer_32_7_2_2_U0_dout;
wire    start_for_pool_layer_32_7_2_2_U0_empty_n;
wire   [0:0] start_for_fc_layer_288_10_U0_din;
wire    start_for_fc_layer_288_10_U0_full_n;
wire   [0:0] start_for_fc_layer_288_10_U0_dout;
wire    start_for_fc_layer_288_10_U0_empty_n;
wire   [0:0] start_for_argmax_10_U0_din;
wire    start_for_argmax_10_U0_full_n;
wire   [0:0] start_for_argmax_10_U0_dout;
wire    start_for_argmax_10_U0_empty_n;
wire   [0:0] start_for_nn_to_axis_1_U0_din;
wire    start_for_nn_to_axis_1_U0_full_n;
wire   [0:0] start_for_nn_to_axis_1_U0_dout;
wire    start_for_nn_to_axis_1_U0_empty_n;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

layers_test_axis_to_nn_784_s axis_to_nn_784_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_nn_784_U0_ap_start),
    .start_full_n(start_for_conv_layer_1_28_3_1_8_U0_full_n),
    .ap_done(axis_to_nn_784_U0_ap_done),
    .ap_continue(axis_to_nn_784_U0_ap_continue),
    .ap_idle(axis_to_nn_784_U0_ap_idle),
    .ap_ready(axis_to_nn_784_U0_ap_ready),
    .stream_in_TVALID(stream_in_TVALID),
    .input_to_conv0_din(axis_to_nn_784_U0_input_to_conv0_din),
    .input_to_conv0_full_n(input_to_conv0_full_n),
    .input_to_conv0_write(axis_to_nn_784_U0_input_to_conv0_write),
    .input_to_conv0_num_data_valid(input_to_conv0_num_data_valid),
    .input_to_conv0_fifo_cap(input_to_conv0_fifo_cap),
    .start_out(axis_to_nn_784_U0_start_out),
    .start_write(axis_to_nn_784_U0_start_write),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TREADY(axis_to_nn_784_U0_stream_in_TREADY),
    .stream_in_TKEEP(stream_in_TKEEP),
    .stream_in_TSTRB(stream_in_TSTRB),
    .stream_in_TLAST(stream_in_TLAST)
);

layers_test_conv_layer_1_28_3_1_8_s conv_layer_1_28_3_1_8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_layer_1_28_3_1_8_U0_ap_start),
    .start_full_n(start_for_pool_layer_8_28_2_2_U0_full_n),
    .ap_done(conv_layer_1_28_3_1_8_U0_ap_done),
    .ap_continue(conv_layer_1_28_3_1_8_U0_ap_continue),
    .ap_idle(conv_layer_1_28_3_1_8_U0_ap_idle),
    .ap_ready(conv_layer_1_28_3_1_8_U0_ap_ready),
    .start_out(conv_layer_1_28_3_1_8_U0_start_out),
    .start_write(conv_layer_1_28_3_1_8_U0_start_write),
    .input_to_conv0_dout(input_to_conv0_dout),
    .input_to_conv0_empty_n(input_to_conv0_empty_n),
    .input_to_conv0_read(conv_layer_1_28_3_1_8_U0_input_to_conv0_read),
    .input_to_conv0_num_data_valid(input_to_conv0_num_data_valid),
    .input_to_conv0_fifo_cap(input_to_conv0_fifo_cap),
    .conv0_to_pool0_din(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din),
    .conv0_to_pool0_full_n(conv0_to_pool0_full_n),
    .conv0_to_pool0_write(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write),
    .conv0_to_pool0_num_data_valid(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid),
    .conv0_to_pool0_fifo_cap(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap)
);

layers_test_pool_layer_8_28_2_2_s pool_layer_8_28_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pool_layer_8_28_2_2_U0_ap_start),
    .start_full_n(start_for_conv_layer_8_14_3_1_32_U0_full_n),
    .ap_done(pool_layer_8_28_2_2_U0_ap_done),
    .ap_continue(pool_layer_8_28_2_2_U0_ap_continue),
    .ap_idle(pool_layer_8_28_2_2_U0_ap_idle),
    .ap_ready(pool_layer_8_28_2_2_U0_ap_ready),
    .start_out(pool_layer_8_28_2_2_U0_start_out),
    .start_write(pool_layer_8_28_2_2_U0_start_write),
    .conv0_to_pool0_dout(conv0_to_pool0_dout),
    .conv0_to_pool0_empty_n(conv0_to_pool0_empty_n),
    .conv0_to_pool0_read(pool_layer_8_28_2_2_U0_conv0_to_pool0_read),
    .conv0_to_pool0_num_data_valid(conv0_to_pool0_num_data_valid),
    .conv0_to_pool0_fifo_cap(conv0_to_pool0_fifo_cap),
    .pool0_to_conv1_din(pool_layer_8_28_2_2_U0_pool0_to_conv1_din),
    .pool0_to_conv1_full_n(pool0_to_conv1_full_n),
    .pool0_to_conv1_write(pool_layer_8_28_2_2_U0_pool0_to_conv1_write),
    .pool0_to_conv1_num_data_valid(pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid),
    .pool0_to_conv1_fifo_cap(pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap)
);

layers_test_conv_layer_8_14_3_1_32_s conv_layer_8_14_3_1_32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_layer_8_14_3_1_32_U0_ap_start),
    .start_full_n(start_for_pool_layer_32_14_2_2_U0_full_n),
    .ap_done(conv_layer_8_14_3_1_32_U0_ap_done),
    .ap_continue(conv_layer_8_14_3_1_32_U0_ap_continue),
    .ap_idle(conv_layer_8_14_3_1_32_U0_ap_idle),
    .ap_ready(conv_layer_8_14_3_1_32_U0_ap_ready),
    .start_out(conv_layer_8_14_3_1_32_U0_start_out),
    .start_write(conv_layer_8_14_3_1_32_U0_start_write),
    .pool0_to_conv1_dout(pool0_to_conv1_dout),
    .pool0_to_conv1_empty_n(pool0_to_conv1_empty_n),
    .pool0_to_conv1_read(conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read),
    .pool0_to_conv1_num_data_valid(pool0_to_conv1_num_data_valid),
    .pool0_to_conv1_fifo_cap(pool0_to_conv1_fifo_cap),
    .conv1_to_pool1_din(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din),
    .conv1_to_pool1_full_n(conv1_to_pool1_full_n),
    .conv1_to_pool1_write(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write),
    .conv1_to_pool1_num_data_valid(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid),
    .conv1_to_pool1_fifo_cap(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap)
);

layers_test_pool_layer_32_14_2_2_s pool_layer_32_14_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pool_layer_32_14_2_2_U0_ap_start),
    .start_full_n(start_for_pool_layer_32_7_2_2_U0_full_n),
    .ap_done(pool_layer_32_14_2_2_U0_ap_done),
    .ap_continue(pool_layer_32_14_2_2_U0_ap_continue),
    .ap_idle(pool_layer_32_14_2_2_U0_ap_idle),
    .ap_ready(pool_layer_32_14_2_2_U0_ap_ready),
    .start_out(pool_layer_32_14_2_2_U0_start_out),
    .start_write(pool_layer_32_14_2_2_U0_start_write),
    .conv1_to_pool1_dout(conv1_to_pool1_dout),
    .conv1_to_pool1_empty_n(conv1_to_pool1_empty_n),
    .conv1_to_pool1_read(pool_layer_32_14_2_2_U0_conv1_to_pool1_read),
    .conv1_to_pool1_num_data_valid(conv1_to_pool1_num_data_valid),
    .conv1_to_pool1_fifo_cap(conv1_to_pool1_fifo_cap),
    .pool1_to_pool2_din(pool_layer_32_14_2_2_U0_pool1_to_pool2_din),
    .pool1_to_pool2_full_n(pool1_to_pool2_full_n),
    .pool1_to_pool2_write(pool_layer_32_14_2_2_U0_pool1_to_pool2_write),
    .pool1_to_pool2_num_data_valid(pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid),
    .pool1_to_pool2_fifo_cap(pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap)
);

layers_test_pool_layer_32_7_2_2_s pool_layer_32_7_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pool_layer_32_7_2_2_U0_ap_start),
    .start_full_n(start_for_fc_layer_288_10_U0_full_n),
    .ap_done(pool_layer_32_7_2_2_U0_ap_done),
    .ap_continue(pool_layer_32_7_2_2_U0_ap_continue),
    .ap_idle(pool_layer_32_7_2_2_U0_ap_idle),
    .ap_ready(pool_layer_32_7_2_2_U0_ap_ready),
    .start_out(pool_layer_32_7_2_2_U0_start_out),
    .start_write(pool_layer_32_7_2_2_U0_start_write),
    .pool1_to_pool2_dout(pool1_to_pool2_dout),
    .pool1_to_pool2_empty_n(pool1_to_pool2_empty_n),
    .pool1_to_pool2_read(pool_layer_32_7_2_2_U0_pool1_to_pool2_read),
    .pool1_to_pool2_num_data_valid(pool1_to_pool2_num_data_valid),
    .pool1_to_pool2_fifo_cap(pool1_to_pool2_fifo_cap),
    .pool2_to_fc0_din(pool_layer_32_7_2_2_U0_pool2_to_fc0_din),
    .pool2_to_fc0_full_n(pool2_to_fc0_full_n),
    .pool2_to_fc0_write(pool_layer_32_7_2_2_U0_pool2_to_fc0_write),
    .pool2_to_fc0_num_data_valid(pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid),
    .pool2_to_fc0_fifo_cap(pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap)
);

layers_test_fc_layer_288_10_s fc_layer_288_10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fc_layer_288_10_U0_ap_start),
    .start_full_n(start_for_argmax_10_U0_full_n),
    .ap_done(fc_layer_288_10_U0_ap_done),
    .ap_continue(fc_layer_288_10_U0_ap_continue),
    .ap_idle(fc_layer_288_10_U0_ap_idle),
    .ap_ready(fc_layer_288_10_U0_ap_ready),
    .start_out(fc_layer_288_10_U0_start_out),
    .start_write(fc_layer_288_10_U0_start_write),
    .pool2_to_fc0_dout(pool2_to_fc0_dout),
    .pool2_to_fc0_empty_n(pool2_to_fc0_empty_n),
    .pool2_to_fc0_read(fc_layer_288_10_U0_pool2_to_fc0_read),
    .pool2_to_fc0_num_data_valid(pool2_to_fc0_num_data_valid),
    .pool2_to_fc0_fifo_cap(pool2_to_fc0_fifo_cap),
    .fc0_to_argmax0_din(fc_layer_288_10_U0_fc0_to_argmax0_din),
    .fc0_to_argmax0_full_n(fc0_to_argmax0_full_n),
    .fc0_to_argmax0_write(fc_layer_288_10_U0_fc0_to_argmax0_write),
    .fc0_to_argmax0_num_data_valid(fc0_to_argmax0_num_data_valid),
    .fc0_to_argmax0_fifo_cap(fc0_to_argmax0_fifo_cap)
);

layers_test_argmax_10_s argmax_10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(argmax_10_U0_ap_start),
    .start_full_n(start_for_nn_to_axis_1_U0_full_n),
    .ap_done(argmax_10_U0_ap_done),
    .ap_continue(argmax_10_U0_ap_continue),
    .ap_idle(argmax_10_U0_ap_idle),
    .ap_ready(argmax_10_U0_ap_ready),
    .start_out(argmax_10_U0_start_out),
    .start_write(argmax_10_U0_start_write),
    .fc0_to_argmax0_dout(fc0_to_argmax0_dout),
    .fc0_to_argmax0_empty_n(fc0_to_argmax0_empty_n),
    .fc0_to_argmax0_read(argmax_10_U0_fc0_to_argmax0_read),
    .fc0_to_argmax0_num_data_valid(fc0_to_argmax0_num_data_valid),
    .fc0_to_argmax0_fifo_cap(fc0_to_argmax0_fifo_cap),
    .argmax0_to_output_din(argmax_10_U0_argmax0_to_output_din),
    .argmax0_to_output_full_n(argmax0_to_output_full_n),
    .argmax0_to_output_write(argmax_10_U0_argmax0_to_output_write),
    .argmax0_to_output_num_data_valid(argmax0_to_output_num_data_valid),
    .argmax0_to_output_fifo_cap(argmax0_to_output_fifo_cap)
);

layers_test_nn_to_axis_1_s nn_to_axis_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(nn_to_axis_1_U0_ap_start),
    .ap_done(nn_to_axis_1_U0_ap_done),
    .ap_continue(nn_to_axis_1_U0_ap_continue),
    .ap_idle(nn_to_axis_1_U0_ap_idle),
    .ap_ready(nn_to_axis_1_U0_ap_ready),
    .argmax0_to_output_dout(argmax0_to_output_dout),
    .argmax0_to_output_empty_n(argmax0_to_output_empty_n),
    .argmax0_to_output_read(nn_to_axis_1_U0_argmax0_to_output_read),
    .argmax0_to_output_num_data_valid(argmax0_to_output_num_data_valid),
    .argmax0_to_output_fifo_cap(argmax0_to_output_fifo_cap),
    .stream_out_TDATA(nn_to_axis_1_U0_stream_out_TDATA),
    .stream_out_TVALID(nn_to_axis_1_U0_stream_out_TVALID),
    .stream_out_TREADY(stream_out_TREADY),
    .stream_out_TKEEP(nn_to_axis_1_U0_stream_out_TKEEP),
    .stream_out_TSTRB(nn_to_axis_1_U0_stream_out_TSTRB),
    .stream_out_TLAST(nn_to_axis_1_U0_stream_out_TLAST)
);

layers_test_fifo_w8_d1000_A input_to_conv0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_nn_784_U0_input_to_conv0_din),
    .if_full_n(input_to_conv0_full_n),
    .if_write(axis_to_nn_784_U0_input_to_conv0_write),
    .if_dout(input_to_conv0_dout),
    .if_empty_n(input_to_conv0_empty_n),
    .if_read(conv_layer_1_28_3_1_8_U0_input_to_conv0_read),
    .if_num_data_valid(input_to_conv0_num_data_valid),
    .if_fifo_cap(input_to_conv0_fifo_cap)
);

layers_test_fifo_w8_d10000_A conv0_to_pool0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_din),
    .if_full_n(conv0_to_pool0_full_n),
    .if_write(conv_layer_1_28_3_1_8_U0_conv0_to_pool0_write),
    .if_dout(conv0_to_pool0_dout),
    .if_empty_n(conv0_to_pool0_empty_n),
    .if_read(pool_layer_8_28_2_2_U0_conv0_to_pool0_read),
    .if_num_data_valid(conv0_to_pool0_num_data_valid),
    .if_fifo_cap(conv0_to_pool0_fifo_cap)
);

layers_test_fifo_w8_d2000_A pool0_to_conv1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pool_layer_8_28_2_2_U0_pool0_to_conv1_din),
    .if_full_n(pool0_to_conv1_full_n),
    .if_write(pool_layer_8_28_2_2_U0_pool0_to_conv1_write),
    .if_dout(pool0_to_conv1_dout),
    .if_empty_n(pool0_to_conv1_empty_n),
    .if_read(conv_layer_8_14_3_1_32_U0_pool0_to_conv1_read),
    .if_num_data_valid(pool0_to_conv1_num_data_valid),
    .if_fifo_cap(pool0_to_conv1_fifo_cap)
);

layers_test_fifo_w8_d10000_A conv1_to_pool1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_din),
    .if_full_n(conv1_to_pool1_full_n),
    .if_write(conv_layer_8_14_3_1_32_U0_conv1_to_pool1_write),
    .if_dout(conv1_to_pool1_dout),
    .if_empty_n(conv1_to_pool1_empty_n),
    .if_read(pool_layer_32_14_2_2_U0_conv1_to_pool1_read),
    .if_num_data_valid(conv1_to_pool1_num_data_valid),
    .if_fifo_cap(conv1_to_pool1_fifo_cap)
);

layers_test_fifo_w8_d2000_A pool1_to_pool2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pool_layer_32_14_2_2_U0_pool1_to_pool2_din),
    .if_full_n(pool1_to_pool2_full_n),
    .if_write(pool_layer_32_14_2_2_U0_pool1_to_pool2_write),
    .if_dout(pool1_to_pool2_dout),
    .if_empty_n(pool1_to_pool2_empty_n),
    .if_read(pool_layer_32_7_2_2_U0_pool1_to_pool2_read),
    .if_num_data_valid(pool1_to_pool2_num_data_valid),
    .if_fifo_cap(pool1_to_pool2_fifo_cap)
);

layers_test_fifo_w8_d3000_A pool2_to_fc0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pool_layer_32_7_2_2_U0_pool2_to_fc0_din),
    .if_full_n(pool2_to_fc0_full_n),
    .if_write(pool_layer_32_7_2_2_U0_pool2_to_fc0_write),
    .if_dout(pool2_to_fc0_dout),
    .if_empty_n(pool2_to_fc0_empty_n),
    .if_read(fc_layer_288_10_U0_pool2_to_fc0_read),
    .if_num_data_valid(pool2_to_fc0_num_data_valid),
    .if_fifo_cap(pool2_to_fc0_fifo_cap)
);

layers_test_fifo_w8_d100_S fc0_to_argmax0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fc_layer_288_10_U0_fc0_to_argmax0_din),
    .if_full_n(fc0_to_argmax0_full_n),
    .if_write(fc_layer_288_10_U0_fc0_to_argmax0_write),
    .if_dout(fc0_to_argmax0_dout),
    .if_empty_n(fc0_to_argmax0_empty_n),
    .if_read(argmax_10_U0_fc0_to_argmax0_read),
    .if_num_data_valid(fc0_to_argmax0_num_data_valid),
    .if_fifo_cap(fc0_to_argmax0_fifo_cap)
);

layers_test_fifo_w8_d10_S argmax0_to_output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(argmax_10_U0_argmax0_to_output_din),
    .if_full_n(argmax0_to_output_full_n),
    .if_write(argmax_10_U0_argmax0_to_output_write),
    .if_dout(argmax0_to_output_dout),
    .if_empty_n(argmax0_to_output_empty_n),
    .if_read(nn_to_axis_1_U0_argmax0_to_output_read),
    .if_num_data_valid(argmax0_to_output_num_data_valid),
    .if_fifo_cap(argmax0_to_output_fifo_cap)
);

layers_test_start_for_conv_layer_1_28_3_1_8_U0 start_for_conv_layer_1_28_3_1_8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_layer_1_28_3_1_8_U0_din),
    .if_full_n(start_for_conv_layer_1_28_3_1_8_U0_full_n),
    .if_write(axis_to_nn_784_U0_start_write),
    .if_dout(start_for_conv_layer_1_28_3_1_8_U0_dout),
    .if_empty_n(start_for_conv_layer_1_28_3_1_8_U0_empty_n),
    .if_read(conv_layer_1_28_3_1_8_U0_ap_ready)
);

layers_test_start_for_pool_layer_8_28_2_2_U0 start_for_pool_layer_8_28_2_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pool_layer_8_28_2_2_U0_din),
    .if_full_n(start_for_pool_layer_8_28_2_2_U0_full_n),
    .if_write(conv_layer_1_28_3_1_8_U0_start_write),
    .if_dout(start_for_pool_layer_8_28_2_2_U0_dout),
    .if_empty_n(start_for_pool_layer_8_28_2_2_U0_empty_n),
    .if_read(pool_layer_8_28_2_2_U0_ap_ready)
);

layers_test_start_for_conv_layer_8_14_3_1_32_U0 start_for_conv_layer_8_14_3_1_32_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_layer_8_14_3_1_32_U0_din),
    .if_full_n(start_for_conv_layer_8_14_3_1_32_U0_full_n),
    .if_write(pool_layer_8_28_2_2_U0_start_write),
    .if_dout(start_for_conv_layer_8_14_3_1_32_U0_dout),
    .if_empty_n(start_for_conv_layer_8_14_3_1_32_U0_empty_n),
    .if_read(conv_layer_8_14_3_1_32_U0_ap_ready)
);

layers_test_start_for_pool_layer_32_14_2_2_U0 start_for_pool_layer_32_14_2_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pool_layer_32_14_2_2_U0_din),
    .if_full_n(start_for_pool_layer_32_14_2_2_U0_full_n),
    .if_write(conv_layer_8_14_3_1_32_U0_start_write),
    .if_dout(start_for_pool_layer_32_14_2_2_U0_dout),
    .if_empty_n(start_for_pool_layer_32_14_2_2_U0_empty_n),
    .if_read(pool_layer_32_14_2_2_U0_ap_ready)
);

layers_test_start_for_pool_layer_32_7_2_2_U0 start_for_pool_layer_32_7_2_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pool_layer_32_7_2_2_U0_din),
    .if_full_n(start_for_pool_layer_32_7_2_2_U0_full_n),
    .if_write(pool_layer_32_14_2_2_U0_start_write),
    .if_dout(start_for_pool_layer_32_7_2_2_U0_dout),
    .if_empty_n(start_for_pool_layer_32_7_2_2_U0_empty_n),
    .if_read(pool_layer_32_7_2_2_U0_ap_ready)
);

layers_test_start_for_fc_layer_288_10_U0 start_for_fc_layer_288_10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fc_layer_288_10_U0_din),
    .if_full_n(start_for_fc_layer_288_10_U0_full_n),
    .if_write(pool_layer_32_7_2_2_U0_start_write),
    .if_dout(start_for_fc_layer_288_10_U0_dout),
    .if_empty_n(start_for_fc_layer_288_10_U0_empty_n),
    .if_read(fc_layer_288_10_U0_ap_ready)
);

layers_test_start_for_argmax_10_U0 start_for_argmax_10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_argmax_10_U0_din),
    .if_full_n(start_for_argmax_10_U0_full_n),
    .if_write(fc_layer_288_10_U0_start_write),
    .if_dout(start_for_argmax_10_U0_dout),
    .if_empty_n(start_for_argmax_10_U0_empty_n),
    .if_read(argmax_10_U0_ap_ready)
);

layers_test_start_for_nn_to_axis_1_U0 start_for_nn_to_axis_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_nn_to_axis_1_U0_din),
    .if_full_n(start_for_nn_to_axis_1_U0_full_n),
    .if_write(argmax_10_U0_start_write),
    .if_dout(start_for_nn_to_axis_1_U0_dout),
    .if_empty_n(start_for_nn_to_axis_1_U0_empty_n),
    .if_read(nn_to_axis_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign argmax_10_U0_ap_continue = 1'b1;

assign argmax_10_U0_ap_start = start_for_argmax_10_U0_empty_n;

assign axis_to_nn_784_U0_ap_continue = 1'b1;

assign axis_to_nn_784_U0_ap_start = 1'b1;

assign conv_layer_1_28_3_1_8_U0_ap_continue = 1'b1;

assign conv_layer_1_28_3_1_8_U0_ap_start = start_for_conv_layer_1_28_3_1_8_U0_empty_n;

assign conv_layer_1_28_3_1_8_U0_conv0_to_pool0_fifo_cap = conv0_to_pool0_fifo_cap;

assign conv_layer_1_28_3_1_8_U0_conv0_to_pool0_num_data_valid = conv0_to_pool0_num_data_valid;

assign conv_layer_8_14_3_1_32_U0_ap_continue = 1'b1;

assign conv_layer_8_14_3_1_32_U0_ap_start = start_for_conv_layer_8_14_3_1_32_U0_empty_n;

assign conv_layer_8_14_3_1_32_U0_conv1_to_pool1_fifo_cap = conv1_to_pool1_fifo_cap;

assign conv_layer_8_14_3_1_32_U0_conv1_to_pool1_num_data_valid = conv1_to_pool1_num_data_valid;

assign fc_layer_288_10_U0_ap_continue = 1'b1;

assign fc_layer_288_10_U0_ap_start = start_for_fc_layer_288_10_U0_empty_n;

assign nn_to_axis_1_U0_ap_continue = 1'b1;

assign nn_to_axis_1_U0_ap_start = start_for_nn_to_axis_1_U0_empty_n;

assign pool_layer_32_14_2_2_U0_ap_continue = 1'b1;

assign pool_layer_32_14_2_2_U0_ap_start = start_for_pool_layer_32_14_2_2_U0_empty_n;

assign pool_layer_32_14_2_2_U0_pool1_to_pool2_fifo_cap = pool1_to_pool2_fifo_cap;

assign pool_layer_32_14_2_2_U0_pool1_to_pool2_num_data_valid = pool1_to_pool2_num_data_valid;

assign pool_layer_32_7_2_2_U0_ap_continue = 1'b1;

assign pool_layer_32_7_2_2_U0_ap_start = start_for_pool_layer_32_7_2_2_U0_empty_n;

assign pool_layer_32_7_2_2_U0_pool2_to_fc0_fifo_cap = pool2_to_fc0_fifo_cap;

assign pool_layer_32_7_2_2_U0_pool2_to_fc0_num_data_valid = pool2_to_fc0_num_data_valid;

assign pool_layer_8_28_2_2_U0_ap_continue = 1'b1;

assign pool_layer_8_28_2_2_U0_ap_start = start_for_pool_layer_8_28_2_2_U0_empty_n;

assign pool_layer_8_28_2_2_U0_pool0_to_conv1_fifo_cap = pool0_to_conv1_fifo_cap;

assign pool_layer_8_28_2_2_U0_pool0_to_conv1_num_data_valid = pool0_to_conv1_num_data_valid;

assign start_for_argmax_10_U0_din = 1'b1;

assign start_for_conv_layer_1_28_3_1_8_U0_din = 1'b1;

assign start_for_conv_layer_8_14_3_1_32_U0_din = 1'b1;

assign start_for_fc_layer_288_10_U0_din = 1'b1;

assign start_for_nn_to_axis_1_U0_din = 1'b1;

assign start_for_pool_layer_32_14_2_2_U0_din = 1'b1;

assign start_for_pool_layer_32_7_2_2_U0_din = 1'b1;

assign start_for_pool_layer_8_28_2_2_U0_din = 1'b1;

assign stream_in_TREADY = axis_to_nn_784_U0_stream_in_TREADY;

assign stream_out_TDATA = nn_to_axis_1_U0_stream_out_TDATA;

assign stream_out_TKEEP = nn_to_axis_1_U0_stream_out_TKEEP;

assign stream_out_TLAST = nn_to_axis_1_U0_stream_out_TLAST;

assign stream_out_TSTRB = nn_to_axis_1_U0_stream_out_TSTRB;

assign stream_out_TVALID = nn_to_axis_1_U0_stream_out_TVALID;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "layers_test_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "layers_test_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //layers_test

