// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_argmax_10_Pipeline_VITIS_LOOP_79_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        max,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_load,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_load,
        max_idx_out,
        max_idx_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] max;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_load;
input  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_load;
output  [7:0] max_idx_out;
output   max_idx_out_ap_vld;

reg ap_idle;
reg max_idx_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln79_fu_167_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] i_1_reg_345;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln82_fu_204_p2;
reg   [0:0] icmp_ln82_reg_354;
wire   [7:0] max_6_fu_210_p3;
reg   [7:0] max_6_reg_359;
wire   [7:0] curr_2_fu_218_p13;
reg   [7:0] curr_2_reg_365;
reg   [7:0] max_idx_fu_70;
wire   [7:0] max_idx_3_fu_295_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [7:0] max_04_fu_74;
wire   [7:0] max_8_fu_303_p3;
reg   [7:0] ap_sig_allocacmp_max_04_load;
reg   [3:0] i_fu_78;
wire   [3:0] i_2_fu_246_p2;
reg   [3:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] curr_fu_176_p11;
wire   [7:0] curr_fu_176_p13;
wire   [7:0] curr_2_fu_218_p11;
wire   [7:0] zext_ln83_fu_260_p1;
wire   [2:0] tmp_fu_274_p4;
wire   [3:0] max_idx_2_fu_283_p3;
wire   [0:0] icmp_ln82_1_fu_270_p2;
wire   [7:0] zext_ln78_fu_291_p1;
wire   [7:0] max_idx_1_fu_263_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] curr_fu_176_p1;
wire   [3:0] curr_fu_176_p3;
wire   [3:0] curr_fu_176_p5;
wire   [3:0] curr_fu_176_p7;
wire  signed [3:0] curr_fu_176_p9;
wire   [3:0] curr_2_fu_218_p1;
wire   [3:0] curr_2_fu_218_p3;
wire   [3:0] curr_2_fu_218_p5;
wire   [3:0] curr_2_fu_218_p7;
wire  signed [3:0] curr_2_fu_218_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 max_idx_fu_70 = 8'd0;
#0 max_04_fu_74 = 8'd0;
#0 i_fu_78 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) layers_test_sparsemux_11_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h4 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h8 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_11_4_8_1_1_U3438(
    .din0(max),
    .din1(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_load),
    .din2(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_load),
    .din3(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_load),
    .din4(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_load),
    .def(curr_fu_176_p11),
    .sel(ap_sig_allocacmp_i_1),
    .dout(curr_fu_176_p13)
);

(* dissolve_hierarchy = "yes" *) layers_test_sparsemux_11_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h4 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h8 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_11_4_8_1_1_U3439(
    .din0(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_load),
    .din1(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_load),
    .din2(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_load),
    .din3(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_load),
    .din4(void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_load),
    .def(curr_2_fu_218_p11),
    .sel(ap_sig_allocacmp_i_1),
    .dout(curr_2_fu_218_p13)
);

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_167_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_78 <= i_2_fu_246_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_78 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_04_fu_74 <= max;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_04_fu_74 <= max_8_fu_303_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_idx_fu_70 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_idx_fu_70 <= max_idx_3_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        curr_2_reg_365 <= curr_2_fu_218_p13;
        i_1_reg_345 <= ap_sig_allocacmp_i_1;
        icmp_ln82_reg_354 <= icmp_ln82_fu_204_p2;
        max_6_reg_359 <= max_6_fu_210_p3;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_167_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_max_04_load = max;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_max_04_load = max_8_fu_303_p3;
        end else begin
            ap_sig_allocacmp_max_04_load = max_04_fu_74;
        end
    end else begin
        ap_sig_allocacmp_max_04_load = max_04_fu_74;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln79_fu_167_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_idx_out_ap_vld = 1'b1;
    end else begin
        max_idx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign curr_2_fu_218_p11 = 'bx;

assign curr_fu_176_p11 = 'bx;

assign i_2_fu_246_p2 = (ap_sig_allocacmp_i_1 + 4'd2);

assign icmp_ln79_fu_167_p2 = ((ap_sig_allocacmp_i_1 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln82_1_fu_270_p2 = (($signed(curr_2_reg_365) > $signed(max_6_reg_359)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_204_p2 = (($signed(curr_fu_176_p13) > $signed(ap_sig_allocacmp_max_04_load)) ? 1'b1 : 1'b0);

assign max_6_fu_210_p3 = ((icmp_ln82_fu_204_p2[0:0] == 1'b1) ? curr_fu_176_p13 : ap_sig_allocacmp_max_04_load);

assign max_8_fu_303_p3 = ((icmp_ln82_1_fu_270_p2[0:0] == 1'b1) ? curr_2_reg_365 : max_6_reg_359);

assign max_idx_1_fu_263_p3 = ((icmp_ln82_reg_354[0:0] == 1'b1) ? zext_ln83_fu_260_p1 : max_idx_fu_70);

assign max_idx_2_fu_283_p3 = {{tmp_fu_274_p4}, {1'd1}};

assign max_idx_3_fu_295_p3 = ((icmp_ln82_1_fu_270_p2[0:0] == 1'b1) ? zext_ln78_fu_291_p1 : max_idx_1_fu_263_p3);

assign max_idx_out = max_idx_fu_70;

assign tmp_fu_274_p4 = {{i_1_reg_345[3:1]}};

assign zext_ln78_fu_291_p1 = max_idx_2_fu_283_p3;

assign zext_ln83_fu_260_p1 = i_1_reg_345;

endmodule //layers_test_argmax_10_Pipeline_VITIS_LOOP_79_2
