// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool1_to_pool2_din,
        pool1_to_pool2_full_n,
        pool1_to_pool2_write,
        pool1_to_pool2_num_data_valid,
        pool1_to_pool2_fifo_cap,
        IN_2_address0,
        IN_2_ce0,
        IN_2_q0,
        IN_2_address1,
        IN_2_ce1,
        IN_2_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] pool1_to_pool2_din;
input   pool1_to_pool2_full_n;
output   pool1_to_pool2_write;
input  [31:0] pool1_to_pool2_num_data_valid;
input  [31:0] pool1_to_pool2_fifo_cap;
output  [12:0] IN_2_address0;
output   IN_2_ce0;
input  [7:0] IN_2_q0;
output  [12:0] IN_2_address1;
output   IN_2_ce1;
input  [7:0] IN_2_q1;

reg ap_idle;
reg pool1_to_pool2_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln41_2_reg_931;
reg   [0:0] icmp_ln41_2_reg_931_pp0_iter5_reg;
reg   [0:0] icmp_ln40_1_reg_935;
reg   [0:0] icmp_ln40_1_reg_935_pp0_iter5_reg;
reg    ap_predicate_op149_write_state7;
reg    ap_block_state7_pp0_stage0_iter6_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_209_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pool1_to_pool2_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [0:0] icmp_ln35_reg_840;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln35_reg_840_pp0_iter1_reg;
wire   [0:0] icmp_ln36_fu_221_p2;
reg   [0:0] icmp_ln36_reg_844;
reg   [0:0] icmp_ln36_reg_844_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_844_pp0_iter2_reg;
wire   [0:0] xor_ln35_fu_254_p2;
reg   [0:0] xor_ln35_reg_855;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] xor_ln35_reg_855_pp0_iter2_reg;
wire   [0:0] icmp_ln37_fu_259_p2;
reg   [0:0] icmp_ln37_reg_861;
wire   [0:0] and_ln35_1_fu_265_p2;
reg   [0:0] and_ln35_1_reg_866;
reg   [0:0] and_ln35_1_reg_866_pp0_iter2_reg;
wire   [0:0] empty_38_fu_271_p2;
reg   [0:0] empty_38_reg_873;
reg   [0:0] empty_38_reg_873_pp0_iter2_reg;
wire   [0:0] not_exitcond_flatten38_mid295_fu_309_p2;
reg   [0:0] not_exitcond_flatten38_mid295_reg_879;
wire   [0:0] exitcond_flatten23_mid260_fu_319_p2;
reg   [0:0] exitcond_flatten23_mid260_reg_884;
wire   [0:0] empty_40_fu_330_p2;
reg   [0:0] empty_40_reg_892;
wire   [9:0] add_ln38_fu_561_p2;
reg   [9:0] add_ln38_reg_897;
wire   [8:0] trunc_ln38_fu_567_p1;
reg   [8:0] trunc_ln38_reg_902;
wire   [3:0] shl_ln_fu_571_p3;
reg   [3:0] shl_ln_reg_907;
wire   [0:0] and_ln41_fu_585_p2;
reg   [0:0] and_ln41_reg_912;
reg   [0:0] and_ln41_reg_912_pp0_iter4_reg;
wire   [9:0] add_ln46_fu_605_p2;
reg   [9:0] add_ln46_reg_916;
wire   [8:0] trunc_ln46_fu_611_p1;
reg   [8:0] trunc_ln46_reg_921;
wire   [3:0] add_ln44_fu_619_p2;
reg   [3:0] add_ln44_reg_926;
wire   [0:0] icmp_ln41_2_fu_631_p2;
reg   [0:0] icmp_ln41_2_reg_931_pp0_iter4_reg;
wire   [0:0] icmp_ln40_1_fu_637_p2;
reg   [0:0] icmp_ln40_1_reg_935_pp0_iter4_reg;
reg   [7:0] IN_2_load_reg_949;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln38_4_fu_701_p1;
wire   [63:0] zext_ln46_3_fu_739_p1;
reg   [1:0] k_col_fu_86;
wire   [1:0] add_ln41_fu_625_p2;
wire    ap_loop_init;
reg   [1:0] k_row_fu_90;
wire   [1:0] select_ln40_fu_515_p3;
reg   [3:0] indvar_flatten21_fu_94;
wire   [3:0] select_ln40_1_fu_341_p3;
reg   [2:0] ocol_fu_98;
wire   [2:0] select_ln37_fu_470_p3;
reg   [5:0] indvar_flatten36_fu_102;
wire   [5:0] select_ln37_1_fu_282_p3;
reg   [2:0] orow_fu_106;
wire   [2:0] select_ln36_fu_429_p3;
reg   [7:0] indvar_flatten61_fu_110;
wire   [7:0] select_ln36_1_fu_233_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten61_load;
wire    ap_block_pp0_stage0;
reg   [5:0] och_fu_114;
wire   [5:0] select_ln35_1_fu_399_p3;
reg   [12:0] indvar_flatten96_fu_118;
wire   [12:0] add_ln35_1_fu_215_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten96_load;
reg   [7:0] max_1_fu_122;
wire   [7:0] max_3_fu_757_p3;
reg    ap_block_pp0_stage0_01001_grp1;
reg    IN_2_ce1_local;
reg    IN_2_ce0_local;
wire   [7:0] add_ln36_1_fu_227_p2;
wire   [5:0] add_ln37_1_fu_276_p2;
wire   [0:0] exitcond_flatten38_not_fu_304_p2;
wire   [0:0] icmp_ln40_fu_298_p2;
wire   [0:0] and_ln35_2_fu_314_p2;
wire   [0:0] empty_39_fu_325_p2;
wire   [3:0] add_ln40_1_fu_335_p2;
wire   [0:0] first_iter_3138_fu_382_p2;
wire   [5:0] add_ln35_fu_369_p2;
wire   [2:0] select_ln35_fu_375_p3;
wire   [0:0] or_ln35_fu_388_p2;
wire   [0:0] icmp_ln41_fu_393_p2;
wire   [2:0] add_ln36_fu_406_p2;
wire   [2:0] ocol_mid243_fu_412_p3;
wire   [0:0] first_iter_3_mid254_fu_419_p2;
wire   [0:0] and_ln35_fu_424_p2;
wire   [0:0] icmp_ln41_mid256_fu_459_p2;
wire   [0:0] not_exitcond_flatten23_mid260_fu_454_p2;
wire   [2:0] add_ln37_fu_436_p2;
wire   [1:0] k_row_mid228_fu_442_p3;
wire   [0:0] empty_41_fu_483_p2;
wire   [0:0] icmp_ln41_mid235_fu_464_p2;
wire   [0:0] empty_42_fu_487_p2;
wire   [1:0] add_ln40_fu_477_p2;
wire   [0:0] first_iter_3_mid1_fu_501_p2;
wire   [0:0] first_iter_3_mid233_fu_449_p2;
wire   [6:0] tmp_1_fu_531_p3;
wire   [9:0] p_shl_fu_523_p3;
wire   [9:0] zext_ln38_fu_539_p1;
wire   [3:0] tmp_fu_549_p3;
wire   [9:0] sub_ln38_fu_543_p2;
wire   [9:0] zext_ln38_1_fu_557_p1;
wire   [1:0] k_col_mid2_fu_493_p3;
wire   [0:0] first_iter_3_mid2_fu_507_p3;
wire   [0:0] icmp_ln41_1_fu_579_p2;
wire   [3:0] zext_ln40_fu_591_p1;
wire   [3:0] empty_fu_595_p2;
wire   [9:0] zext_ln46_fu_601_p1;
wire   [3:0] zext_ln41_fu_615_p1;
wire   [10:0] tmp_2_fu_668_p3;
wire   [12:0] tmp_3_fu_675_p3;
wire   [12:0] zext_ln38_2_fu_682_p1;
wire   [12:0] sub_ln38_1_fu_686_p2;
wire   [12:0] zext_ln38_3_fu_692_p1;
wire   [12:0] add_ln38_1_fu_695_p2;
wire   [10:0] tmp_4_fu_706_p3;
wire   [12:0] tmp_5_fu_713_p3;
wire   [12:0] zext_ln46_1_fu_720_p1;
wire   [12:0] sub_ln41_fu_724_p2;
wire   [12:0] zext_ln46_2_fu_730_p1;
wire   [12:0] add_ln46_1_fu_733_p2;
wire   [0:0] icmp_ln46_fu_752_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 k_col_fu_86 = 2'd0;
#0 k_row_fu_90 = 2'd0;
#0 indvar_flatten21_fu_94 = 4'd0;
#0 ocol_fu_98 = 3'd0;
#0 indvar_flatten36_fu_102 = 6'd0;
#0 orow_fu_106 = 3'd0;
#0 indvar_flatten61_fu_110 = 8'd0;
#0 och_fu_114 = 6'd0;
#0 indvar_flatten96_fu_118 = 13'd0;
#0 max_1_fu_122 = 8'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten21_fu_94 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_840_pp0_iter1_reg == 1'd0))) begin
            indvar_flatten21_fu_94 <= select_ln40_1_fu_341_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten36_fu_102 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_reg_840 == 1'd0))) begin
            indvar_flatten36_fu_102 <= select_ln37_1_fu_282_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten61_fu_110 <= select_ln36_1_fu_233_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten61_fu_110 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten96_fu_118 <= add_ln35_1_fu_215_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten96_fu_118 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_col_fu_86 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_col_fu_86 <= add_ln41_fu_625_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_row_fu_90 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_row_fu_90 <= select_ln40_fu_515_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'd1 == and_ln41_reg_912_pp0_iter4_reg) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            max_1_fu_122 <= IN_2_q1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            max_1_fu_122 <= max_3_fu_757_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            och_fu_114 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            och_fu_114 <= select_ln35_1_fu_399_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ocol_fu_98 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ocol_fu_98 <= select_ln37_fu_470_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            orow_fu_106 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            orow_fu_106 <= select_ln36_fu_429_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        IN_2_load_reg_949 <= IN_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln38_reg_897[9 : 1] <= add_ln38_fu_561_p2[9 : 1];
        add_ln44_reg_926 <= add_ln44_fu_619_p2;
        add_ln46_reg_916 <= add_ln46_fu_605_p2;
        and_ln35_1_reg_866_pp0_iter2_reg <= and_ln35_1_reg_866;
        and_ln41_reg_912 <= and_ln41_fu_585_p2;
        and_ln41_reg_912_pp0_iter4_reg <= and_ln41_reg_912;
        empty_38_reg_873_pp0_iter2_reg <= empty_38_reg_873;
        empty_40_reg_892 <= empty_40_fu_330_p2;
        exitcond_flatten23_mid260_reg_884 <= exitcond_flatten23_mid260_fu_319_p2;
        icmp_ln40_1_reg_935 <= icmp_ln40_1_fu_637_p2;
        icmp_ln40_1_reg_935_pp0_iter4_reg <= icmp_ln40_1_reg_935;
        icmp_ln40_1_reg_935_pp0_iter5_reg <= icmp_ln40_1_reg_935_pp0_iter4_reg;
        icmp_ln41_2_reg_931 <= icmp_ln41_2_fu_631_p2;
        icmp_ln41_2_reg_931_pp0_iter4_reg <= icmp_ln41_2_reg_931;
        icmp_ln41_2_reg_931_pp0_iter5_reg <= icmp_ln41_2_reg_931_pp0_iter4_reg;
        not_exitcond_flatten38_mid295_reg_879 <= not_exitcond_flatten38_mid295_fu_309_p2;
        shl_ln_reg_907[3 : 1] <= shl_ln_fu_571_p3[3 : 1];
        trunc_ln38_reg_902[8 : 1] <= trunc_ln38_fu_567_p1[8 : 1];
        trunc_ln46_reg_921 <= trunc_ln46_fu_611_p1;
        xor_ln35_reg_855_pp0_iter2_reg <= xor_ln35_reg_855;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln35_1_reg_866 <= and_ln35_1_fu_265_p2;
        empty_38_reg_873 <= empty_38_fu_271_p2;
        icmp_ln37_reg_861 <= icmp_ln37_fu_259_p2;
        xor_ln35_reg_855 <= xor_ln35_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln35_reg_840 <= icmp_ln35_fu_209_p2;
        icmp_ln35_reg_840_pp0_iter1_reg <= icmp_ln35_reg_840;
        icmp_ln36_reg_844 <= icmp_ln36_fu_221_p2;
        icmp_ln36_reg_844_pp0_iter1_reg <= icmp_ln36_reg_844;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln36_reg_844_pp0_iter2_reg <= icmp_ln36_reg_844_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        IN_2_ce0_local = 1'b1;
    end else begin
        IN_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        IN_2_ce1_local = 1'b1;
    end else begin
        IN_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_209_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_840_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten61_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten61_load = indvar_flatten61_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten96_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten96_load = indvar_flatten96_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op149_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        pool1_to_pool2_blk_n = pool1_to_pool2_full_n;
    end else begin
        pool1_to_pool2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op149_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        pool1_to_pool2_write = 1'b1;
    end else begin
        pool1_to_pool2_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_2_address0 = zext_ln46_3_fu_739_p1;

assign IN_2_address1 = zext_ln38_4_fu_701_p1;

assign IN_2_ce0 = IN_2_ce0_local;

assign IN_2_ce1 = IN_2_ce1_local;

assign add_ln35_1_fu_215_p2 = (ap_sig_allocacmp_indvar_flatten96_load + 13'd1);

assign add_ln35_fu_369_p2 = (och_fu_114 + 6'd1);

assign add_ln36_1_fu_227_p2 = (ap_sig_allocacmp_indvar_flatten61_load + 8'd1);

assign add_ln36_fu_406_p2 = (select_ln35_fu_375_p3 + 3'd1);

assign add_ln37_1_fu_276_p2 = (indvar_flatten36_fu_102 + 6'd1);

assign add_ln37_fu_436_p2 = (ocol_mid243_fu_412_p3 + 3'd1);

assign add_ln38_1_fu_695_p2 = (sub_ln38_1_fu_686_p2 + zext_ln38_3_fu_692_p1);

assign add_ln38_fu_561_p2 = (sub_ln38_fu_543_p2 + zext_ln38_1_fu_557_p1);

assign add_ln40_1_fu_335_p2 = (indvar_flatten21_fu_94 + 4'd1);

assign add_ln40_fu_477_p2 = (k_row_mid228_fu_442_p3 + 2'd1);

assign add_ln41_fu_625_p2 = (k_col_mid2_fu_493_p3 + 2'd1);

assign add_ln44_fu_619_p2 = (shl_ln_fu_571_p3 + zext_ln41_fu_615_p1);

assign add_ln46_1_fu_733_p2 = (sub_ln41_fu_724_p2 + zext_ln46_2_fu_730_p1);

assign add_ln46_fu_605_p2 = (sub_ln38_fu_543_p2 + zext_ln46_fu_601_p1);

assign and_ln35_1_fu_265_p2 = (xor_ln35_fu_254_p2 & icmp_ln37_fu_259_p2);

assign and_ln35_2_fu_314_p2 = (xor_ln35_reg_855 & icmp_ln40_fu_298_p2);

assign and_ln35_fu_424_p2 = (xor_ln35_reg_855_pp0_iter2_reg & icmp_ln41_fu_393_p2);

assign and_ln41_fu_585_p2 = (icmp_ln41_1_fu_579_p2 & first_iter_3_mid2_fu_507_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6_grp1 = ((ap_predicate_op149_write_state7 == 1'b1) & (pool1_to_pool2_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op149_write_state7 = ((icmp_ln40_1_reg_935_pp0_iter5_reg == 1'd1) & (icmp_ln41_2_reg_931_pp0_iter5_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign empty_38_fu_271_p2 = (icmp_ln36_reg_844 | and_ln35_1_fu_265_p2);

assign empty_39_fu_325_p2 = (exitcond_flatten23_mid260_fu_319_p2 | and_ln35_1_reg_866);

assign empty_40_fu_330_p2 = (icmp_ln36_reg_844_pp0_iter1_reg | empty_39_fu_325_p2);

assign empty_41_fu_483_p2 = (exitcond_flatten23_mid260_reg_884 | empty_38_reg_873_pp0_iter2_reg);

assign empty_42_fu_487_p2 = (icmp_ln41_mid235_fu_464_p2 | empty_41_fu_483_p2);

assign empty_fu_595_p2 = (tmp_fu_549_p3 + zext_ln40_fu_591_p1);

assign exitcond_flatten23_mid260_fu_319_p2 = (not_exitcond_flatten38_mid295_fu_309_p2 & and_ln35_2_fu_314_p2);

assign exitcond_flatten38_not_fu_304_p2 = (icmp_ln37_reg_861 ^ 1'd1);

assign first_iter_3138_fu_382_p2 = ((k_row_fu_90 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid1_fu_501_p2 = ((add_ln40_fu_477_p2 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid233_fu_449_p2 = (first_iter_3_mid254_fu_419_p2 | exitcond_flatten23_mid260_reg_884);

assign first_iter_3_mid254_fu_419_p2 = (or_ln35_fu_388_p2 | and_ln35_1_reg_866_pp0_iter2_reg);

assign first_iter_3_mid2_fu_507_p3 = ((icmp_ln41_mid235_fu_464_p2[0:0] == 1'b1) ? first_iter_3_mid1_fu_501_p2 : first_iter_3_mid233_fu_449_p2);

assign icmp_ln35_fu_209_p2 = ((ap_sig_allocacmp_indvar_flatten96_load == 13'd6272) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_221_p2 = ((ap_sig_allocacmp_indvar_flatten61_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_259_p2 = ((indvar_flatten36_fu_102 == 6'd28) ? 1'b1 : 1'b0);

assign icmp_ln40_1_fu_637_p2 = ((select_ln40_fu_515_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_298_p2 = ((indvar_flatten21_fu_94 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln41_1_fu_579_p2 = ((k_col_mid2_fu_493_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_2_fu_631_p2 = ((add_ln41_fu_625_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_393_p2 = ((k_col_fu_86 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_mid235_fu_464_p2 = (not_exitcond_flatten23_mid260_fu_454_p2 & icmp_ln41_mid256_fu_459_p2);

assign icmp_ln41_mid256_fu_459_p2 = (not_exitcond_flatten38_mid295_reg_879 & and_ln35_fu_424_p2);

assign icmp_ln46_fu_752_p2 = (($signed(max_1_fu_122) < $signed(IN_2_load_reg_949)) ? 1'b1 : 1'b0);

assign k_col_mid2_fu_493_p3 = ((empty_42_fu_487_p2[0:0] == 1'b1) ? 2'd0 : k_col_fu_86);

assign k_row_mid228_fu_442_p3 = ((empty_40_reg_892[0:0] == 1'b1) ? 2'd0 : k_row_fu_90);

assign max_3_fu_757_p3 = ((icmp_ln46_fu_752_p2[0:0] == 1'b1) ? IN_2_load_reg_949 : max_1_fu_122);

assign not_exitcond_flatten23_mid260_fu_454_p2 = (exitcond_flatten23_mid260_reg_884 ^ 1'd1);

assign not_exitcond_flatten38_mid295_fu_309_p2 = (icmp_ln36_reg_844_pp0_iter1_reg | exitcond_flatten38_not_fu_304_p2);

assign ocol_mid243_fu_412_p3 = ((empty_38_reg_873_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : ocol_fu_98);

assign or_ln35_fu_388_p2 = (icmp_ln36_reg_844_pp0_iter2_reg | first_iter_3138_fu_382_p2);

assign p_shl_fu_523_p3 = {{select_ln35_1_fu_399_p3}, {4'd0}};

assign pool1_to_pool2_din = ((icmp_ln46_fu_752_p2[0:0] == 1'b1) ? IN_2_load_reg_949 : max_1_fu_122);

assign select_ln35_1_fu_399_p3 = ((icmp_ln36_reg_844_pp0_iter2_reg[0:0] == 1'b1) ? add_ln35_fu_369_p2 : och_fu_114);

assign select_ln35_fu_375_p3 = ((icmp_ln36_reg_844_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : orow_fu_106);

assign select_ln36_1_fu_233_p3 = ((icmp_ln36_fu_221_p2[0:0] == 1'b1) ? 8'd1 : add_ln36_1_fu_227_p2);

assign select_ln36_fu_429_p3 = ((and_ln35_1_reg_866_pp0_iter2_reg[0:0] == 1'b1) ? add_ln36_fu_406_p2 : select_ln35_fu_375_p3);

assign select_ln37_1_fu_282_p3 = ((empty_38_fu_271_p2[0:0] == 1'b1) ? 6'd1 : add_ln37_1_fu_276_p2);

assign select_ln37_fu_470_p3 = ((exitcond_flatten23_mid260_reg_884[0:0] == 1'b1) ? add_ln37_fu_436_p2 : ocol_mid243_fu_412_p3);

assign select_ln40_1_fu_341_p3 = ((empty_40_fu_330_p2[0:0] == 1'b1) ? 4'd1 : add_ln40_1_fu_335_p2);

assign select_ln40_fu_515_p3 = ((icmp_ln41_mid235_fu_464_p2[0:0] == 1'b1) ? add_ln40_fu_477_p2 : k_row_mid228_fu_442_p3);

assign shl_ln_fu_571_p3 = {{select_ln37_fu_470_p3}, {1'd0}};

assign sub_ln38_1_fu_686_p2 = (tmp_3_fu_675_p3 - zext_ln38_2_fu_682_p1);

assign sub_ln38_fu_543_p2 = (p_shl_fu_523_p3 - zext_ln38_fu_539_p1);

assign sub_ln41_fu_724_p2 = (tmp_5_fu_713_p3 - zext_ln46_1_fu_720_p1);

assign tmp_1_fu_531_p3 = {{select_ln35_1_fu_399_p3}, {1'd0}};

assign tmp_2_fu_668_p3 = {{add_ln38_reg_897}, {1'd0}};

assign tmp_3_fu_675_p3 = {{trunc_ln38_reg_902}, {4'd0}};

assign tmp_4_fu_706_p3 = {{add_ln46_reg_916}, {1'd0}};

assign tmp_5_fu_713_p3 = {{trunc_ln46_reg_921}, {4'd0}};

assign tmp_fu_549_p3 = {{select_ln36_fu_429_p3}, {1'd0}};

assign trunc_ln38_fu_567_p1 = add_ln38_fu_561_p2[8:0];

assign trunc_ln46_fu_611_p1 = add_ln46_fu_605_p2[8:0];

assign xor_ln35_fu_254_p2 = (icmp_ln36_reg_844 ^ 1'd1);

assign zext_ln38_1_fu_557_p1 = tmp_fu_549_p3;

assign zext_ln38_2_fu_682_p1 = tmp_2_fu_668_p3;

assign zext_ln38_3_fu_692_p1 = shl_ln_reg_907;

assign zext_ln38_4_fu_701_p1 = add_ln38_1_fu_695_p2;

assign zext_ln38_fu_539_p1 = tmp_1_fu_531_p3;

assign zext_ln40_fu_591_p1 = select_ln40_fu_515_p3;

assign zext_ln41_fu_615_p1 = k_col_mid2_fu_493_p3;

assign zext_ln46_1_fu_720_p1 = tmp_4_fu_706_p3;

assign zext_ln46_2_fu_730_p1 = add_ln44_reg_926;

assign zext_ln46_3_fu_739_p1 = add_ln46_1_fu_733_p2;

assign zext_ln46_fu_601_p1 = empty_fu_595_p2;

always @ (posedge ap_clk) begin
    add_ln38_reg_897[0] <= 1'b0;
    trunc_ln38_reg_902[0] <= 1'b0;
    shl_ln_reg_907[0] <= 1'b0;
end

endmodule //layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4_2
