// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool0_to_conv1_din,
        pool0_to_conv1_full_n,
        pool0_to_conv1_write,
        pool0_to_conv1_num_data_valid,
        pool0_to_conv1_fifo_cap,
        IN_r_address0,
        IN_r_ce0,
        IN_r_q0,
        IN_r_address1,
        IN_r_ce1,
        IN_r_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] pool0_to_conv1_din;
input   pool0_to_conv1_full_n;
output   pool0_to_conv1_write;
input  [31:0] pool0_to_conv1_num_data_valid;
input  [31:0] pool0_to_conv1_fifo_cap;
output  [12:0] IN_r_address0;
output   IN_r_ce0;
input  [7:0] IN_r_q0;
output  [12:0] IN_r_address1;
output   IN_r_ce1;
input  [7:0] IN_r_q1;

reg ap_idle;
reg pool0_to_conv1_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln41_2_reg_933;
reg   [0:0] icmp_ln41_2_reg_933_pp0_iter5_reg;
reg   [0:0] icmp_ln40_1_reg_937;
reg   [0:0] icmp_ln40_1_reg_937_pp0_iter5_reg;
reg    ap_predicate_op149_write_state7;
reg    ap_block_state7_pp0_stage0_iter6_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_204_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pool0_to_conv1_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [0:0] icmp_ln35_reg_839;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln35_reg_839_pp0_iter1_reg;
wire   [0:0] icmp_ln36_fu_227_p2;
reg   [0:0] icmp_ln36_reg_843;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln36_reg_843_pp0_iter2_reg;
wire   [0:0] xor_ln35_fu_233_p2;
reg   [0:0] xor_ln35_reg_852;
reg   [0:0] xor_ln35_reg_852_pp0_iter2_reg;
wire   [0:0] icmp_ln37_fu_239_p2;
reg   [0:0] icmp_ln37_reg_858;
wire   [0:0] and_ln35_2_fu_245_p2;
reg   [0:0] and_ln35_2_reg_863;
reg   [0:0] and_ln35_2_reg_863_pp0_iter2_reg;
wire   [0:0] empty_48_fu_251_p2;
reg   [0:0] empty_48_reg_870;
reg   [0:0] empty_48_reg_870_pp0_iter2_reg;
wire   [0:0] not_exitcond_flatten38_mid295_fu_325_p2;
reg   [0:0] not_exitcond_flatten38_mid295_reg_876;
wire   [0:0] exitcond_flatten23_mid260_fu_335_p2;
reg   [0:0] exitcond_flatten23_mid260_reg_881;
wire   [3:0] select_ln36_fu_341_p3;
reg   [3:0] select_ln36_reg_889;
wire   [0:0] empty_50_fu_353_p2;
reg   [0:0] empty_50_reg_894;
wire   [8:0] add_ln38_fu_565_p2;
reg   [8:0] add_ln38_reg_899;
wire   [7:0] trunc_ln38_fu_571_p1;
reg   [7:0] trunc_ln38_reg_904;
wire   [4:0] shl_ln_fu_575_p3;
reg   [4:0] shl_ln_reg_909;
wire   [0:0] and_ln41_fu_589_p2;
reg   [0:0] and_ln41_reg_914;
reg   [0:0] and_ln41_reg_914_pp0_iter4_reg;
wire   [8:0] add_ln46_fu_609_p2;
reg   [8:0] add_ln46_reg_918;
wire   [7:0] trunc_ln46_fu_615_p1;
reg   [7:0] trunc_ln46_reg_923;
wire   [4:0] add_ln44_fu_623_p2;
reg   [4:0] add_ln44_reg_928;
wire   [0:0] icmp_ln41_2_fu_635_p2;
reg   [0:0] icmp_ln41_2_reg_933_pp0_iter4_reg;
wire   [0:0] icmp_ln40_1_fu_641_p2;
reg   [0:0] icmp_ln40_1_reg_937_pp0_iter4_reg;
reg   [7:0] IN_load_reg_951;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln38_8_fu_700_p1;
wire   [63:0] zext_ln46_6_fu_738_p1;
reg   [1:0] k_col_fu_84;
wire   [1:0] add_ln41_fu_629_p2;
wire    ap_loop_init;
reg   [1:0] k_row_fu_88;
wire   [1:0] select_ln40_fu_520_p3;
reg   [3:0] indvar_flatten21_fu_92;
wire   [3:0] select_ln40_2_fu_364_p3;
reg   [3:0] ocol_fu_96;
wire   [3:0] select_ln37_fu_475_p3;
reg   [6:0] indvar_flatten36_fu_100;
wire   [6:0] select_ln37_1_fu_263_p3;
reg   [3:0] orow_fu_104;
reg   [9:0] indvar_flatten61_fu_108;
wire   [9:0] select_ln36_1_fu_277_p3;
reg   [3:0] och_fu_112;
wire   [3:0] select_ln35_2_fu_417_p3;
reg   [12:0] indvar_flatten96_fu_116;
wire   [12:0] add_ln35_1_fu_210_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten96_load;
wire    ap_block_pp0_stage0;
reg   [7:0] max_2_fu_120;
wire   [7:0] max_5_fu_756_p3;
reg    ap_block_pp0_stage0_01001_grp1;
reg    IN_r_ce1_local;
reg    IN_r_ce0_local;
wire   [6:0] add_ln37_1_fu_257_p2;
wire   [9:0] add_ln36_1_fu_271_p2;
wire   [3:0] select_ln35_fu_301_p3;
wire   [0:0] exitcond_flatten38_not_fu_320_p2;
wire   [0:0] icmp_ln40_fu_308_p2;
wire   [0:0] and_ln35_1_fu_330_p2;
wire   [3:0] add_ln36_fu_314_p2;
wire   [0:0] empty_49_fu_348_p2;
wire   [3:0] add_ln40_1_fu_358_p2;
wire   [0:0] first_iter_3138_fu_400_p2;
wire   [3:0] add_ln35_fu_394_p2;
wire   [0:0] or_ln35_fu_406_p2;
wire   [0:0] icmp_ln41_fu_411_p2;
wire   [3:0] ocol_mid243_fu_424_p3;
wire   [0:0] first_iter_3_mid254_fu_431_p2;
wire   [0:0] and_ln35_fu_436_p2;
wire   [0:0] icmp_ln41_mid256_fu_464_p2;
wire   [0:0] not_exitcond_flatten23_mid260_fu_459_p2;
wire   [3:0] add_ln37_fu_441_p2;
wire   [1:0] k_row_mid228_fu_447_p3;
wire   [0:0] empty_51_fu_488_p2;
wire   [0:0] icmp_ln41_mid235_fu_469_p2;
wire   [0:0] empty_52_fu_492_p2;
wire   [1:0] add_ln40_fu_482_p2;
wire   [0:0] first_iter_3_mid1_fu_506_p2;
wire   [0:0] first_iter_3_mid233_fu_454_p2;
wire   [5:0] tmp_8_fu_536_p3;
wire   [8:0] p_shl_fu_528_p3;
wire   [8:0] zext_ln38_fu_544_p1;
wire   [4:0] tmp_fu_554_p3;
wire   [8:0] sub_ln38_fu_548_p2;
wire   [8:0] zext_ln38_5_fu_561_p1;
wire   [1:0] k_col_mid2_fu_498_p3;
wire   [0:0] first_iter_3_mid2_fu_512_p3;
wire   [0:0] icmp_ln41_1_fu_583_p2;
wire   [4:0] zext_ln40_fu_595_p1;
wire   [4:0] empty_fu_599_p2;
wire   [8:0] zext_ln46_fu_605_p1;
wire   [4:0] zext_ln41_fu_619_p1;
wire   [10:0] tmp_9_fu_667_p3;
wire   [12:0] tmp_10_fu_674_p3;
wire   [12:0] zext_ln38_6_fu_681_p1;
wire   [12:0] sub_ln38_2_fu_685_p2;
wire   [12:0] zext_ln38_7_fu_691_p1;
wire   [12:0] add_ln38_1_fu_694_p2;
wire   [10:0] tmp_11_fu_705_p3;
wire   [12:0] tmp_12_fu_712_p3;
wire   [12:0] zext_ln46_4_fu_719_p1;
wire   [12:0] sub_ln41_fu_723_p2;
wire   [12:0] zext_ln46_5_fu_729_p1;
wire   [12:0] add_ln46_1_fu_732_p2;
wire   [0:0] icmp_ln46_fu_751_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 k_col_fu_84 = 2'd0;
#0 k_row_fu_88 = 2'd0;
#0 indvar_flatten21_fu_92 = 4'd0;
#0 ocol_fu_96 = 4'd0;
#0 indvar_flatten36_fu_100 = 7'd0;
#0 orow_fu_104 = 4'd0;
#0 indvar_flatten61_fu_108 = 10'd0;
#0 och_fu_112 = 4'd0;
#0 indvar_flatten96_fu_116 = 13'd0;
#0 max_2_fu_120 = 8'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten21_fu_92 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_839_pp0_iter1_reg == 1'd0))) begin
            indvar_flatten21_fu_92 <= select_ln40_2_fu_364_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten36_fu_100 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_reg_839 == 1'd0))) begin
            indvar_flatten36_fu_100 <= select_ln37_1_fu_263_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten61_fu_108 <= 10'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_reg_839 == 1'd0))) begin
            indvar_flatten61_fu_108 <= select_ln36_1_fu_277_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten96_fu_116 <= add_ln35_1_fu_210_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten96_fu_116 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_col_fu_84 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_col_fu_84 <= add_ln41_fu_629_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_row_fu_88 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_row_fu_88 <= select_ln40_fu_520_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'd1 == and_ln41_reg_914_pp0_iter4_reg) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            max_2_fu_120 <= IN_r_q1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            max_2_fu_120 <= max_5_fu_756_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            och_fu_112 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            och_fu_112 <= select_ln35_2_fu_417_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ocol_fu_96 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ocol_fu_96 <= select_ln37_fu_475_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            orow_fu_104 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_839_pp0_iter1_reg == 1'd0))) begin
            orow_fu_104 <= select_ln36_fu_341_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        IN_load_reg_951 <= IN_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln38_reg_899[8 : 1] <= add_ln38_fu_565_p2[8 : 1];
        add_ln44_reg_928 <= add_ln44_fu_623_p2;
        add_ln46_reg_918 <= add_ln46_fu_609_p2;
        and_ln35_2_reg_863_pp0_iter2_reg <= and_ln35_2_reg_863;
        and_ln41_reg_914 <= and_ln41_fu_589_p2;
        and_ln41_reg_914_pp0_iter4_reg <= and_ln41_reg_914;
        empty_48_reg_870_pp0_iter2_reg <= empty_48_reg_870;
        empty_50_reg_894 <= empty_50_fu_353_p2;
        exitcond_flatten23_mid260_reg_881 <= exitcond_flatten23_mid260_fu_335_p2;
        icmp_ln36_reg_843_pp0_iter2_reg <= icmp_ln36_reg_843;
        icmp_ln40_1_reg_937 <= icmp_ln40_1_fu_641_p2;
        icmp_ln40_1_reg_937_pp0_iter4_reg <= icmp_ln40_1_reg_937;
        icmp_ln40_1_reg_937_pp0_iter5_reg <= icmp_ln40_1_reg_937_pp0_iter4_reg;
        icmp_ln41_2_reg_933 <= icmp_ln41_2_fu_635_p2;
        icmp_ln41_2_reg_933_pp0_iter4_reg <= icmp_ln41_2_reg_933;
        icmp_ln41_2_reg_933_pp0_iter5_reg <= icmp_ln41_2_reg_933_pp0_iter4_reg;
        not_exitcond_flatten38_mid295_reg_876 <= not_exitcond_flatten38_mid295_fu_325_p2;
        select_ln36_reg_889 <= select_ln36_fu_341_p3;
        shl_ln_reg_909[4 : 1] <= shl_ln_fu_575_p3[4 : 1];
        trunc_ln38_reg_904[7 : 1] <= trunc_ln38_fu_571_p1[7 : 1];
        trunc_ln46_reg_923 <= trunc_ln46_fu_615_p1;
        xor_ln35_reg_852_pp0_iter2_reg <= xor_ln35_reg_852;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln35_2_reg_863 <= and_ln35_2_fu_245_p2;
        empty_48_reg_870 <= empty_48_fu_251_p2;
        icmp_ln36_reg_843 <= icmp_ln36_fu_227_p2;
        icmp_ln37_reg_858 <= icmp_ln37_fu_239_p2;
        xor_ln35_reg_852 <= xor_ln35_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln35_reg_839 <= icmp_ln35_fu_204_p2;
        icmp_ln35_reg_839_pp0_iter1_reg <= icmp_ln35_reg_839;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        IN_r_ce0_local = 1'b1;
    end else begin
        IN_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        IN_r_ce1_local = 1'b1;
    end else begin
        IN_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_839_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten96_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten96_load = indvar_flatten96_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op149_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        pool0_to_conv1_blk_n = pool0_to_conv1_full_n;
    end else begin
        pool0_to_conv1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op149_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        pool0_to_conv1_write = 1'b1;
    end else begin
        pool0_to_conv1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_r_address0 = zext_ln46_6_fu_738_p1;

assign IN_r_address1 = zext_ln38_8_fu_700_p1;

assign IN_r_ce0 = IN_r_ce0_local;

assign IN_r_ce1 = IN_r_ce1_local;

assign add_ln35_1_fu_210_p2 = (ap_sig_allocacmp_indvar_flatten96_load + 13'd1);

assign add_ln35_fu_394_p2 = (och_fu_112 + 4'd1);

assign add_ln36_1_fu_271_p2 = (indvar_flatten61_fu_108 + 10'd1);

assign add_ln36_fu_314_p2 = (select_ln35_fu_301_p3 + 4'd1);

assign add_ln37_1_fu_257_p2 = (indvar_flatten36_fu_100 + 7'd1);

assign add_ln37_fu_441_p2 = (ocol_mid243_fu_424_p3 + 4'd1);

assign add_ln38_1_fu_694_p2 = (sub_ln38_2_fu_685_p2 + zext_ln38_7_fu_691_p1);

assign add_ln38_fu_565_p2 = (sub_ln38_fu_548_p2 + zext_ln38_5_fu_561_p1);

assign add_ln40_1_fu_358_p2 = (indvar_flatten21_fu_92 + 4'd1);

assign add_ln40_fu_482_p2 = (k_row_mid228_fu_447_p3 + 2'd1);

assign add_ln41_fu_629_p2 = (k_col_mid2_fu_498_p3 + 2'd1);

assign add_ln44_fu_623_p2 = (shl_ln_fu_575_p3 + zext_ln41_fu_619_p1);

assign add_ln46_1_fu_732_p2 = (sub_ln41_fu_723_p2 + zext_ln46_5_fu_729_p1);

assign add_ln46_fu_609_p2 = (sub_ln38_fu_548_p2 + zext_ln46_fu_605_p1);

assign and_ln35_1_fu_330_p2 = (xor_ln35_reg_852 & icmp_ln40_fu_308_p2);

assign and_ln35_2_fu_245_p2 = (xor_ln35_fu_233_p2 & icmp_ln37_fu_239_p2);

assign and_ln35_fu_436_p2 = (xor_ln35_reg_852_pp0_iter2_reg & icmp_ln41_fu_411_p2);

assign and_ln41_fu_589_p2 = (icmp_ln41_1_fu_583_p2 & first_iter_3_mid2_fu_512_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6_grp1 = ((ap_predicate_op149_write_state7 == 1'b1) & (pool0_to_conv1_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op149_write_state7 = ((icmp_ln40_1_reg_937_pp0_iter5_reg == 1'd1) & (icmp_ln41_2_reg_933_pp0_iter5_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign empty_48_fu_251_p2 = (icmp_ln36_fu_227_p2 | and_ln35_2_fu_245_p2);

assign empty_49_fu_348_p2 = (exitcond_flatten23_mid260_fu_335_p2 | and_ln35_2_reg_863);

assign empty_50_fu_353_p2 = (icmp_ln36_reg_843 | empty_49_fu_348_p2);

assign empty_51_fu_488_p2 = (exitcond_flatten23_mid260_reg_881 | empty_48_reg_870_pp0_iter2_reg);

assign empty_52_fu_492_p2 = (icmp_ln41_mid235_fu_469_p2 | empty_51_fu_488_p2);

assign empty_fu_599_p2 = (tmp_fu_554_p3 + zext_ln40_fu_595_p1);

assign exitcond_flatten23_mid260_fu_335_p2 = (not_exitcond_flatten38_mid295_fu_325_p2 & and_ln35_1_fu_330_p2);

assign exitcond_flatten38_not_fu_320_p2 = (icmp_ln37_reg_858 ^ 1'd1);

assign first_iter_3138_fu_400_p2 = ((k_row_fu_88 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid1_fu_506_p2 = ((add_ln40_fu_482_p2 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_3_mid233_fu_454_p2 = (first_iter_3_mid254_fu_431_p2 | exitcond_flatten23_mid260_reg_881);

assign first_iter_3_mid254_fu_431_p2 = (or_ln35_fu_406_p2 | and_ln35_2_reg_863_pp0_iter2_reg);

assign first_iter_3_mid2_fu_512_p3 = ((icmp_ln41_mid235_fu_469_p2[0:0] == 1'b1) ? first_iter_3_mid1_fu_506_p2 : first_iter_3_mid233_fu_454_p2);

assign icmp_ln35_fu_204_p2 = ((ap_sig_allocacmp_indvar_flatten96_load == 13'd6272) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_227_p2 = ((indvar_flatten61_fu_108 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_239_p2 = ((indvar_flatten36_fu_100 == 7'd56) ? 1'b1 : 1'b0);

assign icmp_ln40_1_fu_641_p2 = ((select_ln40_fu_520_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_308_p2 = ((indvar_flatten21_fu_92 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln41_1_fu_583_p2 = ((k_col_mid2_fu_498_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_2_fu_635_p2 = ((add_ln41_fu_629_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_411_p2 = ((k_col_fu_84 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_mid235_fu_469_p2 = (not_exitcond_flatten23_mid260_fu_459_p2 & icmp_ln41_mid256_fu_464_p2);

assign icmp_ln41_mid256_fu_464_p2 = (not_exitcond_flatten38_mid295_reg_876 & and_ln35_fu_436_p2);

assign icmp_ln46_fu_751_p2 = (($signed(max_2_fu_120) < $signed(IN_load_reg_951)) ? 1'b1 : 1'b0);

assign k_col_mid2_fu_498_p3 = ((empty_52_fu_492_p2[0:0] == 1'b1) ? 2'd0 : k_col_fu_84);

assign k_row_mid228_fu_447_p3 = ((empty_50_reg_894[0:0] == 1'b1) ? 2'd0 : k_row_fu_88);

assign max_5_fu_756_p3 = ((icmp_ln46_fu_751_p2[0:0] == 1'b1) ? IN_load_reg_951 : max_2_fu_120);

assign not_exitcond_flatten23_mid260_fu_459_p2 = (exitcond_flatten23_mid260_reg_881 ^ 1'd1);

assign not_exitcond_flatten38_mid295_fu_325_p2 = (icmp_ln36_reg_843 | exitcond_flatten38_not_fu_320_p2);

assign ocol_mid243_fu_424_p3 = ((empty_48_reg_870_pp0_iter2_reg[0:0] == 1'b1) ? 4'd0 : ocol_fu_96);

assign or_ln35_fu_406_p2 = (icmp_ln36_reg_843_pp0_iter2_reg | first_iter_3138_fu_400_p2);

assign p_shl_fu_528_p3 = {{select_ln35_2_fu_417_p3}, {5'd0}};

assign pool0_to_conv1_din = ((icmp_ln46_fu_751_p2[0:0] == 1'b1) ? IN_load_reg_951 : max_2_fu_120);

assign select_ln35_2_fu_417_p3 = ((icmp_ln36_reg_843_pp0_iter2_reg[0:0] == 1'b1) ? add_ln35_fu_394_p2 : och_fu_112);

assign select_ln35_fu_301_p3 = ((icmp_ln36_reg_843[0:0] == 1'b1) ? 4'd0 : orow_fu_104);

assign select_ln36_1_fu_277_p3 = ((icmp_ln36_fu_227_p2[0:0] == 1'b1) ? 10'd1 : add_ln36_1_fu_271_p2);

assign select_ln36_fu_341_p3 = ((and_ln35_2_reg_863[0:0] == 1'b1) ? add_ln36_fu_314_p2 : select_ln35_fu_301_p3);

assign select_ln37_1_fu_263_p3 = ((empty_48_fu_251_p2[0:0] == 1'b1) ? 7'd1 : add_ln37_1_fu_257_p2);

assign select_ln37_fu_475_p3 = ((exitcond_flatten23_mid260_reg_881[0:0] == 1'b1) ? add_ln37_fu_441_p2 : ocol_mid243_fu_424_p3);

assign select_ln40_2_fu_364_p3 = ((empty_50_fu_353_p2[0:0] == 1'b1) ? 4'd1 : add_ln40_1_fu_358_p2);

assign select_ln40_fu_520_p3 = ((icmp_ln41_mid235_fu_469_p2[0:0] == 1'b1) ? add_ln40_fu_482_p2 : k_row_mid228_fu_447_p3);

assign shl_ln_fu_575_p3 = {{select_ln37_fu_475_p3}, {1'd0}};

assign sub_ln38_2_fu_685_p2 = (tmp_10_fu_674_p3 - zext_ln38_6_fu_681_p1);

assign sub_ln38_fu_548_p2 = (p_shl_fu_528_p3 - zext_ln38_fu_544_p1);

assign sub_ln41_fu_723_p2 = (tmp_12_fu_712_p3 - zext_ln46_4_fu_719_p1);

assign tmp_10_fu_674_p3 = {{trunc_ln38_reg_904}, {5'd0}};

assign tmp_11_fu_705_p3 = {{add_ln46_reg_918}, {2'd0}};

assign tmp_12_fu_712_p3 = {{trunc_ln46_reg_923}, {5'd0}};

assign tmp_8_fu_536_p3 = {{select_ln35_2_fu_417_p3}, {2'd0}};

assign tmp_9_fu_667_p3 = {{add_ln38_reg_899}, {2'd0}};

assign tmp_fu_554_p3 = {{select_ln36_reg_889}, {1'd0}};

assign trunc_ln38_fu_571_p1 = add_ln38_fu_565_p2[7:0];

assign trunc_ln46_fu_615_p1 = add_ln46_fu_609_p2[7:0];

assign xor_ln35_fu_233_p2 = (icmp_ln36_fu_227_p2 ^ 1'd1);

assign zext_ln38_5_fu_561_p1 = tmp_fu_554_p3;

assign zext_ln38_6_fu_681_p1 = tmp_9_fu_667_p3;

assign zext_ln38_7_fu_691_p1 = shl_ln_reg_909;

assign zext_ln38_8_fu_700_p1 = add_ln38_1_fu_694_p2;

assign zext_ln38_fu_544_p1 = tmp_8_fu_536_p3;

assign zext_ln40_fu_595_p1 = select_ln40_fu_520_p3;

assign zext_ln41_fu_619_p1 = k_col_mid2_fu_498_p3;

assign zext_ln46_4_fu_719_p1 = tmp_11_fu_705_p3;

assign zext_ln46_5_fu_729_p1 = add_ln44_reg_928;

assign zext_ln46_6_fu_738_p1 = add_ln46_1_fu_732_p2;

assign zext_ln46_fu_605_p1 = empty_fu_599_p2;

always @ (posedge ap_clk) begin
    add_ln38_reg_899[0] <= 1'b0;
    trunc_ln38_reg_904[0] <= 1'b0;
    shl_ln_reg_909[0] <= 1'b0;
end

endmodule //layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4
