// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_pool_layer_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv1_to_pool1_dout,
        conv1_to_pool1_empty_n,
        conv1_to_pool1_read,
        conv1_to_pool1_num_data_valid,
        conv1_to_pool1_fifo_cap,
        IN_2_address1,
        IN_2_ce1,
        IN_2_we1,
        IN_2_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] conv1_to_pool1_dout;
input   conv1_to_pool1_empty_n;
output   conv1_to_pool1_read;
input  [14:0] conv1_to_pool1_num_data_valid;
input  [14:0] conv1_to_pool1_fifo_cap;
output  [12:0] IN_2_address1;
output   IN_2_ce1;
output   IN_2_we1;
output  [7:0] IN_2_d1;

reg ap_idle;
reg conv1_to_pool1_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln23_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    conv1_to_pool1_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln24_fu_170_p2;
reg   [0:0] icmp_ln24_reg_402;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [3:0] icol_mid2_fu_214_p3;
reg   [3:0] icol_mid2_reg_407;
reg   [3:0] icol_mid2_reg_407_pp0_iter2_reg;
wire   [3:0] select_ln24_fu_222_p3;
reg   [3:0] select_ln24_reg_412;
wire   [9:0] add_ln27_fu_310_p2;
reg   [9:0] add_ln27_reg_417;
wire   [8:0] trunc_ln27_fu_316_p1;
reg   [8:0] trunc_ln27_reg_422;
wire   [63:0] zext_ln27_4_fu_358_p1;
reg   [3:0] icol_fu_72;
wire   [3:0] add_ln25_fu_230_p2;
wire    ap_loop_init;
reg   [3:0] irow_fu_76;
reg   [7:0] indvar_flatten_fu_80;
wire   [7:0] select_ln24_1_fu_242_p3;
reg   [5:0] ich_fu_84;
wire   [5:0] select_ln23_1_fu_274_p3;
reg   [12:0] indvar_flatten14_fu_88;
wire   [12:0] add_ln23_1_fu_150_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten14_load;
wire    ap_block_pp0_stage0;
reg    IN_2_we1_local;
reg    IN_2_ce1_local;
wire   [0:0] icmp_ln25_fu_190_p2;
wire   [0:0] xor_ln23_fu_184_p2;
wire   [3:0] select_ln23_fu_176_p3;
wire   [0:0] and_ln23_fu_196_p2;
wire   [0:0] empty_fu_208_p2;
wire   [3:0] add_ln24_fu_202_p2;
wire   [7:0] add_ln24_1_fu_236_p2;
wire   [5:0] add_ln23_fu_268_p2;
wire   [6:0] tmp_fu_289_p3;
wire   [9:0] p_shl8_fu_281_p3;
wire   [9:0] zext_ln27_fu_297_p1;
wire   [9:0] sub_ln27_fu_301_p2;
wire   [9:0] zext_ln27_1_fu_307_p1;
wire   [10:0] tmp_13_fu_325_p3;
wire   [12:0] tmp_14_fu_332_p3;
wire   [12:0] zext_ln27_2_fu_339_p1;
wire   [12:0] sub_ln25_fu_343_p2;
wire   [12:0] zext_ln27_3_fu_349_p1;
wire   [12:0] add_ln27_1_fu_352_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 icol_fu_72 = 4'd0;
#0 irow_fu_76 = 4'd0;
#0 indvar_flatten_fu_80 = 8'd0;
#0 ich_fu_84 = 6'd0;
#0 indvar_flatten14_fu_88 = 13'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            ich_fu_84 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ich_fu_84 <= select_ln23_1_fu_274_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            icol_fu_72 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            icol_fu_72 <= add_ln25_fu_230_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln23_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten14_fu_88 <= add_ln23_1_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_88 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_80 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten_fu_80 <= select_ln24_1_fu_242_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            irow_fu_76 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            irow_fu_76 <= select_ln24_fu_222_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln27_reg_417 <= add_ln27_fu_310_p2;
        icol_mid2_reg_407_pp0_iter2_reg <= icol_mid2_reg_407;
        trunc_ln27_reg_422 <= trunc_ln27_fu_316_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln24_reg_402 <= icmp_ln24_fu_170_p2;
        icol_mid2_reg_407 <= icol_mid2_fu_214_p3;
        select_ln24_reg_412 <= select_ln24_fu_222_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        IN_2_ce1_local = 1'b1;
    end else begin
        IN_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        IN_2_we1_local = 1'b1;
    end else begin
        IN_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten14_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten14_load = indvar_flatten14_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_to_pool1_blk_n = conv1_to_pool1_empty_n;
    end else begin
        conv1_to_pool1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        conv1_to_pool1_read = 1'b1;
    end else begin
        conv1_to_pool1_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_2_address1 = zext_ln27_4_fu_358_p1;

assign IN_2_ce1 = IN_2_ce1_local;

assign IN_2_d1 = conv1_to_pool1_dout;

assign IN_2_we1 = IN_2_we1_local;

assign add_ln23_1_fu_150_p2 = (ap_sig_allocacmp_indvar_flatten14_load + 13'd1);

assign add_ln23_fu_268_p2 = (ich_fu_84 + 6'd1);

assign add_ln24_1_fu_236_p2 = (indvar_flatten_fu_80 + 8'd1);

assign add_ln24_fu_202_p2 = (select_ln23_fu_176_p3 + 4'd1);

assign add_ln25_fu_230_p2 = (icol_mid2_fu_214_p3 + 4'd1);

assign add_ln27_1_fu_352_p2 = (sub_ln25_fu_343_p2 + zext_ln27_3_fu_349_p1);

assign add_ln27_fu_310_p2 = (sub_ln27_fu_301_p2 + zext_ln27_1_fu_307_p1);

assign and_ln23_fu_196_p2 = (xor_ln23_fu_184_p2 & icmp_ln25_fu_190_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((conv1_to_pool1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((conv1_to_pool1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((conv1_to_pool1_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_208_p2 = (icmp_ln24_fu_170_p2 | and_ln23_fu_196_p2);

assign icmp_ln23_fu_144_p2 = ((ap_sig_allocacmp_indvar_flatten14_load == 13'd6272) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_170_p2 = ((indvar_flatten_fu_80 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_190_p2 = ((icol_fu_72 == 4'd14) ? 1'b1 : 1'b0);

assign icol_mid2_fu_214_p3 = ((empty_fu_208_p2[0:0] == 1'b1) ? 4'd0 : icol_fu_72);

assign p_shl8_fu_281_p3 = {{select_ln23_1_fu_274_p3}, {4'd0}};

assign select_ln23_1_fu_274_p3 = ((icmp_ln24_reg_402[0:0] == 1'b1) ? add_ln23_fu_268_p2 : ich_fu_84);

assign select_ln23_fu_176_p3 = ((icmp_ln24_fu_170_p2[0:0] == 1'b1) ? 4'd0 : irow_fu_76);

assign select_ln24_1_fu_242_p3 = ((icmp_ln24_fu_170_p2[0:0] == 1'b1) ? 8'd1 : add_ln24_1_fu_236_p2);

assign select_ln24_fu_222_p3 = ((and_ln23_fu_196_p2[0:0] == 1'b1) ? add_ln24_fu_202_p2 : select_ln23_fu_176_p3);

assign sub_ln25_fu_343_p2 = (tmp_14_fu_332_p3 - zext_ln27_2_fu_339_p1);

assign sub_ln27_fu_301_p2 = (p_shl8_fu_281_p3 - zext_ln27_fu_297_p1);

assign tmp_13_fu_325_p3 = {{add_ln27_reg_417}, {1'd0}};

assign tmp_14_fu_332_p3 = {{trunc_ln27_reg_422}, {4'd0}};

assign tmp_fu_289_p3 = {{select_ln23_1_fu_274_p3}, {1'd0}};

assign trunc_ln27_fu_316_p1 = add_ln27_fu_310_p2[8:0];

assign xor_ln23_fu_184_p2 = (icmp_ln24_fu_170_p2 ^ 1'd1);

assign zext_ln27_1_fu_307_p1 = select_ln24_reg_412;

assign zext_ln27_2_fu_339_p1 = tmp_13_fu_325_p3;

assign zext_ln27_3_fu_349_p1 = icol_mid2_reg_407_pp0_iter2_reg;

assign zext_ln27_4_fu_358_p1 = add_ln27_1_fu_352_p2;

assign zext_ln27_fu_297_p1 = tmp_fu_289_p3;

endmodule //layers_test_pool_layer_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3
