// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool2_to_fc0_din,
        pool2_to_fc0_full_n,
        pool2_to_fc0_write,
        pool2_to_fc0_num_data_valid,
        pool2_to_fc0_fifo_cap,
        IN_1_address0,
        IN_1_ce0,
        IN_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] pool2_to_fc0_din;
input   pool2_to_fc0_full_n;
output   pool2_to_fc0_write;
input  [31:0] pool2_to_fc0_num_data_valid;
input  [31:0] pool2_to_fc0_fifo_cap;
output  [10:0] IN_1_address0;
output   IN_1_ce0;
input  [7:0] IN_1_q0;

reg ap_idle;
reg pool2_to_fc0_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln41_3_reg_843;
reg   [0:0] icmp_ln41_3_reg_843_pp0_iter6_reg;
reg   [0:0] icmp_ln40_2_reg_847;
reg   [0:0] icmp_ln40_2_reg_847_pp0_iter6_reg;
reg    ap_predicate_op135_write_state8;
reg    ap_block_state8_pp0_stage0_iter7_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_214_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pool2_to_fc0_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [0:0] icmp_ln35_reg_778;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln35_reg_778_pp0_iter1_reg;
wire   [0:0] icmp_ln36_fu_226_p2;
reg   [0:0] icmp_ln36_reg_782;
reg   [0:0] icmp_ln36_reg_782_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_782_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_782_pp0_iter3_reg;
wire   [0:0] xor_ln35_fu_259_p2;
reg   [0:0] xor_ln35_reg_792;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] xor_ln35_reg_792_pp0_iter2_reg;
wire   [0:0] icmp_ln37_fu_264_p2;
reg   [0:0] icmp_ln37_reg_798;
wire   [0:0] and_ln35_4_fu_270_p2;
reg   [0:0] and_ln35_4_reg_803;
reg   [0:0] and_ln35_4_reg_803_pp0_iter2_reg;
wire   [0:0] empty_fu_276_p2;
reg   [0:0] empty_reg_809;
reg   [0:0] empty_reg_809_pp0_iter2_reg;
wire   [0:0] not_exitcond_flatten36_mid293_fu_314_p2;
reg   [0:0] not_exitcond_flatten36_mid293_reg_815;
wire   [0:0] exitcond_flatten21_mid258_fu_324_p2;
reg   [0:0] exitcond_flatten21_mid258_reg_820;
wire   [0:0] empty_44_fu_335_p2;
reg   [0:0] empty_44_reg_827;
reg   [0:0] empty_44_reg_827_pp0_iter3_reg;
reg   [0:0] empty_44_reg_827_pp0_iter4_reg;
reg   [0:0] empty_44_reg_827_pp0_iter5_reg;
wire   [2:0] empty_47_fu_497_p2;
reg   [2:0] empty_47_reg_833;
wire   [2:0] add_ln44_fu_507_p2;
reg   [2:0] add_ln44_reg_838;
reg   [2:0] add_ln44_reg_838_pp0_iter4_reg;
wire   [0:0] icmp_ln41_3_fu_519_p2;
reg   [0:0] icmp_ln41_3_reg_843_pp0_iter4_reg;
reg   [0:0] icmp_ln41_3_reg_843_pp0_iter5_reg;
wire   [0:0] icmp_ln40_2_fu_525_p2;
reg   [0:0] icmp_ln40_2_reg_847_pp0_iter4_reg;
reg   [0:0] icmp_ln40_2_reg_847_pp0_iter5_reg;
wire   [8:0] add_ln49_fu_588_p2;
reg   [8:0] add_ln49_reg_851;
wire   [7:0] trunc_ln49_fu_594_p1;
reg   [7:0] trunc_ln49_reg_856;
reg   [0:0] tmp_7_reg_866;
reg   [7:0] trunc_ln52_1_reg_871;
reg   [7:0] trunc_ln52_2_reg_876;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln49_4_fu_628_p1;
reg   [15:0] acc_1_fu_98;
wire   [15:0] acc_fu_647_p2;
wire    ap_loop_init;
reg   [1:0] k_col_fu_102;
wire   [1:0] add_ln41_fu_513_p2;
reg   [1:0] k_row_fu_106;
wire   [1:0] select_ln40_fu_469_p3;
reg   [3:0] indvar_flatten19_fu_110;
wire   [3:0] select_ln40_2_fu_346_p3;
reg   [1:0] ocol_fu_114;
wire   [1:0] select_ln37_fu_438_p3;
reg   [4:0] indvar_flatten34_fu_118;
wire   [4:0] select_ln37_2_fu_287_p3;
reg   [1:0] orow_fu_122;
wire   [1:0] select_ln36_fu_407_p3;
reg   [5:0] indvar_flatten59_fu_126;
wire   [5:0] select_ln36_2_fu_238_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten59_load;
wire    ap_block_pp0_stage0;
reg   [5:0] och_fu_130;
wire   [5:0] select_ln35_2_fu_560_p3;
reg   [10:0] indvar_flatten94_fu_134;
wire   [10:0] add_ln35_2_fu_220_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten94_load;
reg    ap_block_pp0_stage0_01001_grp1;
reg    IN_1_ce0_local;
wire   [5:0] add_ln36_2_fu_232_p2;
wire   [4:0] add_ln37_2_fu_281_p2;
wire   [0:0] exitcond_flatten36_not_fu_309_p2;
wire   [0:0] icmp_ln40_fu_303_p2;
wire   [0:0] and_ln35_3_fu_319_p2;
wire   [0:0] empty_43_fu_330_p2;
wire   [3:0] add_ln40_2_fu_340_p2;
wire   [0:0] icmp_ln41_fu_378_p2;
wire   [1:0] select_ln35_fu_371_p3;
wire   [0:0] and_ln35_fu_384_p2;
wire   [1:0] add_ln36_fu_389_p2;
wire   [1:0] ocol_mid241_fu_395_p3;
wire   [0:0] icmp_ln41_mid254_fu_402_p2;
wire   [0:0] not_exitcond_flatten21_mid258_fu_427_p2;
wire   [1:0] add_ln37_fu_414_p2;
wire   [1:0] k_row_mid226_fu_420_p3;
wire   [0:0] empty_45_fu_451_p2;
wire   [0:0] icmp_ln41_mid233_fu_432_p2;
wire   [0:0] empty_46_fu_455_p2;
wire   [1:0] add_ln40_fu_445_p2;
wire   [2:0] tmp_fu_477_p3;
wire   [2:0] zext_ln40_fu_493_p1;
wire   [1:0] k_col_mid2_fu_461_p3;
wire   [2:0] tmp_1_fu_485_p3;
wire   [2:0] zext_ln41_fu_503_p1;
wire   [5:0] add_ln35_fu_554_p2;
wire   [8:0] p_shl8_fu_571_p3;
wire   [8:0] zext_ln49_fu_567_p1;
wire   [8:0] sub_ln49_fu_579_p2;
wire   [8:0] zext_ln49_1_fu_585_p1;
wire   [10:0] tmp_6_fu_603_p3;
wire   [10:0] zext_ln49_2_fu_610_p1;
wire   [10:0] sub_ln41_fu_613_p2;
wire   [10:0] zext_ln49_3_fu_619_p1;
wire   [10:0] add_ln49_1_fu_622_p2;
wire  signed [15:0] sext_ln49_fu_643_p1;
wire   [15:0] acc_2_mid229_fu_636_p3;
wire   [9:0] trunc_ln40_fu_653_p1;
wire   [9:0] sub_ln52_fu_665_p2;
wire   [7:0] sub_ln52_1_fu_696_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 acc_1_fu_98 = 16'd0;
#0 k_col_fu_102 = 2'd0;
#0 k_row_fu_106 = 2'd0;
#0 indvar_flatten19_fu_110 = 4'd0;
#0 ocol_fu_114 = 2'd0;
#0 indvar_flatten34_fu_118 = 5'd0;
#0 orow_fu_122 = 2'd0;
#0 indvar_flatten59_fu_126 = 6'd0;
#0 och_fu_130 = 6'd0;
#0 indvar_flatten94_fu_134 = 11'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_1_fu_98 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_1_fu_98 <= acc_fu_647_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten19_fu_110 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_778_pp0_iter1_reg == 1'd0))) begin
            indvar_flatten19_fu_110 <= select_ln40_2_fu_346_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten34_fu_118 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_reg_778 == 1'd0))) begin
            indvar_flatten34_fu_118 <= select_ln37_2_fu_287_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten59_fu_126 <= select_ln36_2_fu_238_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten59_fu_126 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten94_fu_134 <= add_ln35_2_fu_220_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten94_fu_134 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_col_fu_102 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_col_fu_102 <= add_ln41_fu_513_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_row_fu_106 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            k_row_fu_106 <= select_ln40_fu_469_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            och_fu_130 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            och_fu_130 <= select_ln35_2_fu_560_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ocol_fu_114 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ocol_fu_114 <= select_ln37_fu_438_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            orow_fu_122 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            orow_fu_122 <= select_ln36_fu_407_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln44_reg_838 <= add_ln44_fu_507_p2;
        add_ln44_reg_838_pp0_iter4_reg <= add_ln44_reg_838;
        add_ln49_reg_851 <= add_ln49_fu_588_p2;
        and_ln35_4_reg_803_pp0_iter2_reg <= and_ln35_4_reg_803;
        empty_44_reg_827 <= empty_44_fu_335_p2;
        empty_44_reg_827_pp0_iter3_reg <= empty_44_reg_827;
        empty_44_reg_827_pp0_iter4_reg <= empty_44_reg_827_pp0_iter3_reg;
        empty_44_reg_827_pp0_iter5_reg <= empty_44_reg_827_pp0_iter4_reg;
        empty_47_reg_833 <= empty_47_fu_497_p2;
        empty_reg_809_pp0_iter2_reg <= empty_reg_809;
        exitcond_flatten21_mid258_reg_820 <= exitcond_flatten21_mid258_fu_324_p2;
        icmp_ln40_2_reg_847 <= icmp_ln40_2_fu_525_p2;
        icmp_ln40_2_reg_847_pp0_iter4_reg <= icmp_ln40_2_reg_847;
        icmp_ln40_2_reg_847_pp0_iter5_reg <= icmp_ln40_2_reg_847_pp0_iter4_reg;
        icmp_ln40_2_reg_847_pp0_iter6_reg <= icmp_ln40_2_reg_847_pp0_iter5_reg;
        icmp_ln41_3_reg_843 <= icmp_ln41_3_fu_519_p2;
        icmp_ln41_3_reg_843_pp0_iter4_reg <= icmp_ln41_3_reg_843;
        icmp_ln41_3_reg_843_pp0_iter5_reg <= icmp_ln41_3_reg_843_pp0_iter4_reg;
        icmp_ln41_3_reg_843_pp0_iter6_reg <= icmp_ln41_3_reg_843_pp0_iter5_reg;
        not_exitcond_flatten36_mid293_reg_815 <= not_exitcond_flatten36_mid293_fu_314_p2;
        tmp_7_reg_866 <= acc_fu_647_p2[32'd15];
        trunc_ln49_reg_856 <= trunc_ln49_fu_594_p1;
        trunc_ln52_1_reg_871 <= {{sub_ln52_fu_665_p2[9:2]}};
        trunc_ln52_2_reg_876 <= {{acc_fu_647_p2[9:2]}};
        xor_ln35_reg_792_pp0_iter2_reg <= xor_ln35_reg_792;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln35_4_reg_803 <= and_ln35_4_fu_270_p2;
        empty_reg_809 <= empty_fu_276_p2;
        icmp_ln37_reg_798 <= icmp_ln37_fu_264_p2;
        xor_ln35_reg_792 <= xor_ln35_fu_259_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln35_reg_778 <= icmp_ln35_fu_214_p2;
        icmp_ln35_reg_778_pp0_iter1_reg <= icmp_ln35_reg_778;
        icmp_ln36_reg_782 <= icmp_ln36_fu_226_p2;
        icmp_ln36_reg_782_pp0_iter1_reg <= icmp_ln36_reg_782;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln36_reg_782_pp0_iter2_reg <= icmp_ln36_reg_782_pp0_iter1_reg;
        icmp_ln36_reg_782_pp0_iter3_reg <= icmp_ln36_reg_782_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        IN_1_ce0_local = 1'b1;
    end else begin
        IN_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_214_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln35_reg_778_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten59_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten59_load = indvar_flatten59_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten94_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten94_load = indvar_flatten94_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op135_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool2_to_fc0_blk_n = pool2_to_fc0_full_n;
    end else begin
        pool2_to_fc0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op135_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool2_to_fc0_write = 1'b1;
    end else begin
        pool2_to_fc0_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_1_address0 = zext_ln49_4_fu_628_p1;

assign IN_1_ce0 = IN_1_ce0_local;

assign acc_2_mid229_fu_636_p3 = ((empty_44_reg_827_pp0_iter5_reg[0:0] == 1'b1) ? 16'd0 : acc_1_fu_98);

assign acc_fu_647_p2 = ($signed(sext_ln49_fu_643_p1) + $signed(acc_2_mid229_fu_636_p3));

assign add_ln35_2_fu_220_p2 = (ap_sig_allocacmp_indvar_flatten94_load + 11'd1);

assign add_ln35_fu_554_p2 = (och_fu_130 + 6'd1);

assign add_ln36_2_fu_232_p2 = (ap_sig_allocacmp_indvar_flatten59_load + 6'd1);

assign add_ln36_fu_389_p2 = (select_ln35_fu_371_p3 + 2'd1);

assign add_ln37_2_fu_281_p2 = (indvar_flatten34_fu_118 + 5'd1);

assign add_ln37_fu_414_p2 = (ocol_mid241_fu_395_p3 + 2'd1);

assign add_ln40_2_fu_340_p2 = (indvar_flatten19_fu_110 + 4'd1);

assign add_ln40_fu_445_p2 = (k_row_mid226_fu_420_p3 + 2'd1);

assign add_ln41_fu_513_p2 = (k_col_mid2_fu_461_p3 + 2'd1);

assign add_ln44_fu_507_p2 = (tmp_1_fu_485_p3 + zext_ln41_fu_503_p1);

assign add_ln49_1_fu_622_p2 = (sub_ln41_fu_613_p2 + zext_ln49_3_fu_619_p1);

assign add_ln49_fu_588_p2 = (sub_ln49_fu_579_p2 + zext_ln49_1_fu_585_p1);

assign and_ln35_3_fu_319_p2 = (xor_ln35_reg_792 & icmp_ln40_fu_303_p2);

assign and_ln35_4_fu_270_p2 = (xor_ln35_fu_259_p2 & icmp_ln37_fu_264_p2);

assign and_ln35_fu_384_p2 = (xor_ln35_reg_792_pp0_iter2_reg & icmp_ln41_fu_378_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7_grp1 = ((ap_predicate_op135_write_state8 == 1'b1) & (pool2_to_fc0_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op135_write_state8 = ((icmp_ln40_2_reg_847_pp0_iter6_reg == 1'd1) & (icmp_ln41_3_reg_843_pp0_iter6_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign empty_43_fu_330_p2 = (exitcond_flatten21_mid258_fu_324_p2 | and_ln35_4_reg_803);

assign empty_44_fu_335_p2 = (icmp_ln36_reg_782_pp0_iter1_reg | empty_43_fu_330_p2);

assign empty_45_fu_451_p2 = (exitcond_flatten21_mid258_reg_820 | empty_reg_809_pp0_iter2_reg);

assign empty_46_fu_455_p2 = (icmp_ln41_mid233_fu_432_p2 | empty_45_fu_451_p2);

assign empty_47_fu_497_p2 = (tmp_fu_477_p3 + zext_ln40_fu_493_p1);

assign empty_fu_276_p2 = (icmp_ln36_reg_782 | and_ln35_4_fu_270_p2);

assign exitcond_flatten21_mid258_fu_324_p2 = (not_exitcond_flatten36_mid293_fu_314_p2 & and_ln35_3_fu_319_p2);

assign exitcond_flatten36_not_fu_309_p2 = (icmp_ln37_reg_798 ^ 1'd1);

assign icmp_ln35_fu_214_p2 = ((ap_sig_allocacmp_indvar_flatten94_load == 11'd1152) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_226_p2 = ((ap_sig_allocacmp_indvar_flatten59_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_264_p2 = ((indvar_flatten34_fu_118 == 5'd12) ? 1'b1 : 1'b0);

assign icmp_ln40_2_fu_525_p2 = ((select_ln40_fu_469_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_303_p2 = ((indvar_flatten19_fu_110 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln41_3_fu_519_p2 = ((add_ln41_fu_513_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_378_p2 = ((k_col_fu_102 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln41_mid233_fu_432_p2 = (not_exitcond_flatten21_mid258_fu_427_p2 & icmp_ln41_mid254_fu_402_p2);

assign icmp_ln41_mid254_fu_402_p2 = (not_exitcond_flatten36_mid293_reg_815 & and_ln35_fu_384_p2);

assign k_col_mid2_fu_461_p3 = ((empty_46_fu_455_p2[0:0] == 1'b1) ? 2'd0 : k_col_fu_102);

assign k_row_mid226_fu_420_p3 = ((empty_44_reg_827[0:0] == 1'b1) ? 2'd0 : k_row_fu_106);

assign not_exitcond_flatten21_mid258_fu_427_p2 = (exitcond_flatten21_mid258_reg_820 ^ 1'd1);

assign not_exitcond_flatten36_mid293_fu_314_p2 = (icmp_ln36_reg_782_pp0_iter1_reg | exitcond_flatten36_not_fu_309_p2);

assign ocol_mid241_fu_395_p3 = ((empty_reg_809_pp0_iter2_reg[0:0] == 1'b1) ? 2'd0 : ocol_fu_114);

assign p_shl8_fu_571_p3 = {{select_ln35_2_fu_560_p3}, {3'd0}};

assign pool2_to_fc0_din = ((tmp_7_reg_866[0:0] == 1'b1) ? sub_ln52_1_fu_696_p2 : trunc_ln52_2_reg_876);

assign select_ln35_2_fu_560_p3 = ((icmp_ln36_reg_782_pp0_iter3_reg[0:0] == 1'b1) ? add_ln35_fu_554_p2 : och_fu_130);

assign select_ln35_fu_371_p3 = ((icmp_ln36_reg_782_pp0_iter2_reg[0:0] == 1'b1) ? 2'd0 : orow_fu_122);

assign select_ln36_2_fu_238_p3 = ((icmp_ln36_fu_226_p2[0:0] == 1'b1) ? 6'd1 : add_ln36_2_fu_232_p2);

assign select_ln36_fu_407_p3 = ((and_ln35_4_reg_803_pp0_iter2_reg[0:0] == 1'b1) ? add_ln36_fu_389_p2 : select_ln35_fu_371_p3);

assign select_ln37_2_fu_287_p3 = ((empty_fu_276_p2[0:0] == 1'b1) ? 5'd1 : add_ln37_2_fu_281_p2);

assign select_ln37_fu_438_p3 = ((exitcond_flatten21_mid258_reg_820[0:0] == 1'b1) ? add_ln37_fu_414_p2 : ocol_mid241_fu_395_p3);

assign select_ln40_2_fu_346_p3 = ((empty_44_fu_335_p2[0:0] == 1'b1) ? 4'd1 : add_ln40_2_fu_340_p2);

assign select_ln40_fu_469_p3 = ((icmp_ln41_mid233_fu_432_p2[0:0] == 1'b1) ? add_ln40_fu_445_p2 : k_row_mid226_fu_420_p3);

assign sext_ln49_fu_643_p1 = $signed(IN_1_q0);

assign sub_ln41_fu_613_p2 = (tmp_6_fu_603_p3 - zext_ln49_2_fu_610_p1);

assign sub_ln49_fu_579_p2 = (p_shl8_fu_571_p3 - zext_ln49_fu_567_p1);

assign sub_ln52_1_fu_696_p2 = (8'd0 - trunc_ln52_1_reg_871);

assign sub_ln52_fu_665_p2 = (10'd0 - trunc_ln40_fu_653_p1);

assign tmp_1_fu_485_p3 = {{select_ln37_fu_438_p3}, {1'd0}};

assign tmp_6_fu_603_p3 = {{trunc_ln49_reg_856}, {3'd0}};

assign tmp_fu_477_p3 = {{select_ln36_fu_407_p3}, {1'd0}};

assign trunc_ln40_fu_653_p1 = acc_fu_647_p2[9:0];

assign trunc_ln49_fu_594_p1 = add_ln49_fu_588_p2[7:0];

assign xor_ln35_fu_259_p2 = (icmp_ln36_reg_782 ^ 1'd1);

assign zext_ln40_fu_493_p1 = select_ln40_fu_469_p3;

assign zext_ln41_fu_503_p1 = k_col_mid2_fu_461_p3;

assign zext_ln49_1_fu_585_p1 = empty_47_reg_833;

assign zext_ln49_2_fu_610_p1 = add_ln49_reg_851;

assign zext_ln49_3_fu_619_p1 = add_ln44_reg_838_pp0_iter4_reg;

assign zext_ln49_4_fu_628_p1 = add_ln49_1_fu_622_p2;

assign zext_ln49_fu_567_p1 = select_ln35_2_fu_560_p3;

endmodule //layers_test_pool_layer_Pipeline_VITIS_LOOP_35_4_VITIS_LOOP_36_5_VITIS_LOOP_37_6_VITIS_LOOP_4_1
