// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_argmax_10_Pipeline_VITIS_LOOP_72_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fc0_to_argmax0_dout,
        fc0_to_argmax0_empty_n,
        fc0_to_argmax0_read,
        fc0_to_argmax0_num_data_valid,
        fc0_to_argmax0_fifo_cap,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_ap_vld,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9,
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] fc0_to_argmax0_dout;
input   fc0_to_argmax0_empty_n;
output   fc0_to_argmax0_read;
input  [7:0] fc0_to_argmax0_num_data_valid;
input  [7:0] fc0_to_argmax0_fifo_cap;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_ap_vld;
output  [7:0] void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9;
output   void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_ap_vld;

reg ap_idle;
reg fc0_to_argmax0_read;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_ap_vld;
reg void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln72_fu_84_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    fc0_to_argmax0_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [3:0] ich_7_reg_190;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [3:0] ich_fu_66;
wire   [3:0] add_ln72_fu_90_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_ich_7;
wire    ap_block_pp0_stage0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ich_fu_66 = 4'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln72_fu_84_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ich_fu_66 <= add_ln72_fu_90_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ich_fu_66 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ich_7_reg_190 <= ap_sig_allocacmp_ich_7;
    end
end

always @ (*) begin
    if (((icmp_ln72_fu_84_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ich_7 = 4'd0;
    end else begin
        ap_sig_allocacmp_ich_7 = ich_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc0_to_argmax0_blk_n = fc0_to_argmax0_empty_n;
    end else begin
        fc0_to_argmax0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc0_to_argmax0_read = 1'b1;
    end else begin
        fc0_to_argmax0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(ich_7_reg_190 == 4'd2) & ~(ich_7_reg_190 == 4'd1) & ~(ich_7_reg_190 == 4'd0) & ~(ich_7_reg_190 == 4'd8) & ~(ich_7_reg_190 == 4'd7) & ~(ich_7_reg_190 == 4'd6) & ~(ich_7_reg_190 == 4'd5) & ~(ich_7_reg_190 == 4'd4) & ~(ich_7_reg_190 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ich_7_reg_190 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_ap_vld = 1'b1;
    end else begin
        void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln72_fu_90_p2 = (ap_sig_allocacmp_ich_7 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((fc0_to_argmax0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((fc0_to_argmax0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((fc0_to_argmax0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln72_fu_84_p2 = ((ap_sig_allocacmp_ich_7 == 4'd10) ? 1'b1 : 1'b0);

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_1 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_2 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_3 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_4 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_5 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_6 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_7 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_8 = fc0_to_argmax0_dout;

assign void_argmax_10_stream_ap_int_8_0_stream_ap_int_8_0_IN_9 = fc0_to_argmax0_dout;

endmodule //layers_test_argmax_10_Pipeline_VITIS_LOOP_72_1
