// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layers_test_conv_layer_1_28_3_1_8_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_to_conv0_dout,
        input_to_conv0_empty_n,
        input_to_conv0_read,
        input_to_conv0_num_data_valid,
        input_to_conv0_fifo_cap,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_d1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_address1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1,
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] input_to_conv0_dout;
input   input_to_conv0_empty_n;
output   input_to_conv0_read;
input  [10:0] input_to_conv0_num_data_valid;
input  [10:0] input_to_conv0_fifo_cap;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_d1;
output  [6:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_address1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1;
output   p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1;
output  [7:0] p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_d1;

reg ap_idle;
reg input_to_conv0_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln34_fu_293_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_to_conv0_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln34_fu_328_p3;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [4:0] select_ln34_2_fu_336_p3;
reg   [3:0] tmp_reg_509;
reg   [3:0] tmp_80_reg_515;
wire   [6:0] add_ln37_fu_439_p2;
reg   [6:0] add_ln37_reg_520;
reg   [6:0] add_ln37_reg_520_pp0_iter3_reg;
reg   [6:0] add_ln37_reg_520_pp0_iter4_reg;
reg   [6:0] add_ln37_reg_520_pp0_iter5_reg;
reg   [6:0] add_ln37_reg_520_pp0_iter6_reg;
reg   [6:0] add_ln37_reg_520_pp0_iter7_reg;
reg   [6:0] add_ln37_reg_520_pp0_iter8_reg;
wire   [63:0] zext_ln37_5_fu_449_p1;
reg   [4:0] icol_fu_88;
wire   [4:0] add_ln35_fu_396_p2;
wire    ap_loop_init;
reg   [4:0] irow_fu_92;
reg   [9:0] indvar_flatten_fu_96;
wire   [9:0] add_ln34_2_fu_299_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1_local;
wire   [1:0] trunc_ln34_fu_445_p1;
wire   [1:0] trunc_ln35_fu_461_p1;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1_local;
reg    p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1_local;
wire   [0:0] icmp_ln35_fu_322_p2;
wire   [4:0] add_ln34_fu_316_p2;
wire   [4:0] mul_ln34_fu_348_p0;
wire   [6:0] mul_ln34_fu_348_p1;
wire   [10:0] mul_ln34_fu_348_p2;
wire   [2:0] grp_fu_364_p1;
wire   [4:0] mul_ln35_fu_374_p0;
wire   [6:0] mul_ln35_fu_374_p1;
wire   [10:0] mul_ln35_fu_374_p2;
wire   [2:0] grp_fu_390_p1;
wire   [4:0] tmp_79_fu_419_p3;
wire   [6:0] tmp_78_fu_412_p3;
wire   [6:0] zext_ln34_2_fu_426_p1;
wire   [6:0] add_ln34_3_fu_430_p2;
wire   [6:0] zext_ln37_fu_436_p1;
wire   [1:0] grp_fu_364_p2;
wire   [1:0] grp_fu_390_p2;
reg    grp_fu_364_ce;
reg    grp_fu_390_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] mul_ln34_fu_348_p00;
wire   [10:0] mul_ln35_fu_374_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 icol_fu_88 = 5'd0;
#0 irow_fu_92 = 5'd0;
#0 indvar_flatten_fu_96 = 10'd0;
#0 ap_done_reg = 1'b0;
end

layers_test_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U10(
    .din0(mul_ln34_fu_348_p0),
    .din1(mul_ln34_fu_348_p1),
    .dout(mul_ln34_fu_348_p2)
);

layers_test_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln34_2_fu_336_p3),
    .din1(grp_fu_364_p1),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p2)
);

layers_test_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U12(
    .din0(mul_ln35_fu_374_p0),
    .din1(mul_ln35_fu_374_p1),
    .dout(mul_ln35_fu_374_p2)
);

layers_test_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln34_fu_328_p3),
    .din1(grp_fu_390_p1),
    .ce(grp_fu_390_ce),
    .dout(grp_fu_390_p2)
);

layers_test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            icol_fu_88 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            icol_fu_88 <= add_ln35_fu_396_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln34_fu_293_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_96 <= add_ln34_2_fu_299_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_96 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            irow_fu_92 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            irow_fu_92 <= select_ln34_2_fu_336_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln37_reg_520 <= add_ln37_fu_439_p2;
        add_ln37_reg_520_pp0_iter3_reg <= add_ln37_reg_520;
        add_ln37_reg_520_pp0_iter4_reg <= add_ln37_reg_520_pp0_iter3_reg;
        add_ln37_reg_520_pp0_iter5_reg <= add_ln37_reg_520_pp0_iter4_reg;
        add_ln37_reg_520_pp0_iter6_reg <= add_ln37_reg_520_pp0_iter5_reg;
        add_ln37_reg_520_pp0_iter7_reg <= add_ln37_reg_520_pp0_iter6_reg;
        add_ln37_reg_520_pp0_iter8_reg <= add_ln37_reg_520_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_80_reg_515 <= {{mul_ln35_fu_374_p2[10:7]}};
        tmp_reg_509 <= {{mul_ln34_fu_348_p2[10:7]}};
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_293_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_390_ce = 1'b1;
    end else begin
        grp_fu_390_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        input_to_conv0_blk_n = input_to_conv0_empty_n;
    end else begin
        input_to_conv0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        input_to_conv0_read = 1'b1;
    end else begin
        input_to_conv0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln34_fu_445_p1 == 2'd0) & ~(trunc_ln34_fu_445_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln34_fu_445_p1 == 2'd0) & ~(trunc_ln34_fu_445_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd0))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln35_fu_461_p1 == 2'd0) & ~(trunc_ln35_fu_461_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln34_fu_445_p1 == 2'd1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd1) & (trunc_ln34_fu_445_p1 == 2'd1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd0) & (trunc_ln34_fu_445_p1 == 2'd1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln35_fu_461_p1 == 2'd0) & ~(trunc_ln35_fu_461_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln34_fu_445_p1 == 2'd0))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd1) & (trunc_ln34_fu_445_p1 == 2'd0))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln35_fu_461_p1 == 2'd0) & (trunc_ln34_fu_445_p1 == 2'd0))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln34_fu_445_p1 == 2'd0) & ~(trunc_ln35_fu_461_p1 == 2'd0) & ~(trunc_ln35_fu_461_p1 == 2'd1) & ~(trunc_ln34_fu_445_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1_local = 1'b1;
    end else begin
        p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_2_fu_299_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln34_3_fu_430_p2 = (tmp_78_fu_412_p3 + zext_ln34_2_fu_426_p1);

assign add_ln34_fu_316_p2 = (irow_fu_92 + 5'd1);

assign add_ln35_fu_396_p2 = (select_ln34_fu_328_p3 + 5'd1);

assign add_ln37_fu_439_p2 = (add_ln34_3_fu_430_p2 + zext_ln37_fu_436_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((input_to_conv0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((input_to_conv0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((input_to_conv0_empty_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_364_p1 = 5'd3;

assign grp_fu_390_p1 = 5'd3;

assign icmp_ln34_fu_293_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_322_p2 = ((icol_fu_88 == 5'd28) ? 1'b1 : 1'b0);

assign mul_ln34_fu_348_p0 = mul_ln34_fu_348_p00;

assign mul_ln34_fu_348_p00 = select_ln34_2_fu_336_p3;

assign mul_ln34_fu_348_p1 = 11'd43;

assign mul_ln35_fu_374_p0 = mul_ln35_fu_374_p00;

assign mul_ln35_fu_374_p00 = select_ln34_fu_328_p3;

assign mul_ln35_fu_374_p1 = 11'd43;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_1_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_2_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_3_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_4_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_5_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_6_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_7_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_8_we1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_address1 = zext_ln37_5_fu_449_p1;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_ce1_local;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_d1 = input_to_conv0_dout;

assign p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1 = p_ZZ10conv_layerILi1ELi28ELi3ELi1ELi8EEvRN3hls6streamI6ap_intILi8EELi0EEEPAT_AT1_we1_local;

assign select_ln34_2_fu_336_p3 = ((icmp_ln35_fu_322_p2[0:0] == 1'b1) ? add_ln34_fu_316_p2 : irow_fu_92);

assign select_ln34_fu_328_p3 = ((icmp_ln35_fu_322_p2[0:0] == 1'b1) ? 5'd0 : icol_fu_88);

assign tmp_78_fu_412_p3 = {{tmp_reg_509}, {3'd0}};

assign tmp_79_fu_419_p3 = {{tmp_reg_509}, {1'd0}};

assign trunc_ln34_fu_445_p1 = grp_fu_364_p2[1:0];

assign trunc_ln35_fu_461_p1 = grp_fu_390_p2[1:0];

assign zext_ln34_2_fu_426_p1 = tmp_79_fu_419_p3;

assign zext_ln37_5_fu_449_p1 = add_ln37_reg_520_pp0_iter8_reg;

assign zext_ln37_fu_436_p1 = tmp_80_reg_515;

endmodule //layers_test_conv_layer_1_28_3_1_8_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3
